app/containers/MainLayout.js, app/stores/TransactionsStore.js, app/stores/UserStore.js, app/stores/WalletsStore.js
This PR refactors the wallet logic so that we only have an `active` wallet when we are on a wallet screen. This way the sidebar does not show any wallet as "active" when we are on settings etc.
=> make no wallet active when on other screens

app/api/fixtures.js
This PR removes all floating point numbers from amounts in the fixtures since we are only working with integers now.
=> convert all floats to integers in fixtures

electron/main.development.js, electron/menus/osx.js, electron/menus/win-linux.js, webpack/package.js
This PR enables dev tools in production mode!
Note: this was still only achieved by not minifying the JS files … but since Daedalus is a desktop app and open source, this does not matter much.
=> enable dev tools in production

app/api/fixtures.js, app/containers/wallet/WalletHomePage.js
This PR fixes the UX bug that search field appeared shortly before it was clear that there are no transactions. Additionally it makes the "no transactions found" message work correctly (only when searched). To test this I just made one of the stub wallets empty and without any transactions.
=> fixes 'search appearing when transactions' bug

appveyor.yml
Manually ran `npm run package` locally with the updated path and the resulting
Daedalus.exe in the release directory ends up with the specified icon.
Without this change the program had the default Electron icon.
In case there's concern that the path doesn't correspond to an actual file, the
.ico extension (in Windows) is appended in webpack/package.js.
=> CSL-705: fix icon path passed to electron-package

installers/WindowsInstaller.hs
Daedalus.exe is a 64-bit application and therefore must be installed to
`C:\Program Files` rather than `C:\Program Files (x86)`, as explained in NSIS'
docs: http://nsis.sourceforge.net/Docs/Chapter4.html#varconstant
The change may also fix the Windows Desktop link icon, but that must be
verified.
=> [CSL-705] Fix Windows install path (x86/x64)

installers/WindowsInstaller.hs, installers/stack.yaml
Until the ndmitchell/nsis#11 PR (or similar) is merged and published in the NSIS DSL package, we can use [my fork](https://github.com/jmitchell/nsis/tree/feature/escape-hatch) with the `injectLiteral` and `injectGlobalLiteral` functions. They're used in this PR to set `Unicode true` (replacing my earlier ugly hack) and the appropriate `VIProductVersion`.
=> [CSL-531] Use NSIS DSL fork to inject unsupported options

app/components/wallet/home/WalletNoTransactions.scss, app/components/wallet/home/WalletTransactionsList.scss, app/components/wallet/summary/WalletSummary.scss
Fixes cut-off text in the wallet summary on small window sizes:
**BEFORE:**
**NOW**
=> fixes small ui glitch on wallet summary

installers/WindowsInstaller.hs
WACK's UAC checks suggested signing may resolve this issue, so I'm starting by ensuring the installed EXEs are signed. The installer and uninstaller are already getting signed.
=> [CSL-807] Sign cardano-node.exe and cardano-launcher.exe

app/components/widgets/Transaction.scss
=> [daef-59] fixes broken transactions list styles on small window sizes

app/components/loading/Loading.js, app/stores/NetworkStatusStore.js
As discussed showing the absolute percent provides better UX since it is confusing that syncing always drops back to `0%` with relative percentages (on app restarts). The 2 decimal points should provide enough fine grained info about sub-percentage loading to remain informative.
=> [DAEF-66] show absolute syncing percentage with 2 decimals

app/actions/sidebar-actions.js, app/components/sidebar/Sidebar.js, app/components/sidebar/Sidebar.scss, app/containers/MainLayout.js, app/stores/SidebarStore.js
This PR fixes the UX of the app-bar toggle to only toggle the sub menus and always keep the app-bar visible (minimized)
=> [DAEF-69] never completely hide the app bar

app/components/wallet/transactions/WalletTransactionsList.js, app/components/widgets/Transaction.js
This PR fixes transaction ordering and introduces transaction time in the transaction list.
=> [DAEF-77] Fixes transaction ordering and displays transaction date

app/stores/SidebarStore.js
This PR fixes the button for expanding the sidebar which was not working on initial app launch. 
To verify this fix, launch the app and click on "hamburger" icon to expand the sidebar.
=> [DAEF-84] Fix button for expanding the sidebar

.eslintrc, app/actions/dialogs-actions.js, app/actions/index.js, app/actions/wallets-actions.js, app/api/CardanoClientApi.js, app/api/index.js, app/components/wallet/WalletSettings.js, app/components/wallet/WalletSettings.scss, app/components/wallet/settings/DeleteWalletButton.js, app/components/wallet/settings/DeleteWalletButton.scss, app/components/wallet/settings/DeleteWalletConfirmationDialog.js, app/components/wallet/settings/DeleteWalletConfirmationDialog.scss, app/components/widgets/forms/CheckboxWithLongLabel.scss, app/containers/wallet/WalletSettingsPage.js, app/containers/wallet/dialogs/DeleteWalletDialogContainer.js, app/domain/Wallet.js, app/i18n/global-messages.js, app/i18n/locales/en-US.json, app/stores/UIDialogsStore.js, app/stores/WalletsStore.js, app/stores/index.js, app/themes/daedalus/_theme.scss, app/themes/daedalus/button.scss, app/themes/daedalus/dialog.scss, app/themes/index.global.scss, stories/WalletDeleteConfirmationDialog.stories.js, stories/index.js
This PR adds the wallet deletion feature to the settings page:
(note: i made the checkbox red after taking the screenshots)
- Introduced `UiDialogsStore` to manage active dialog visibility and data
- The data handling of dialogs is greatly simplified with this change (no need to store properties on other stores)
- Used a dedicated container component for the delete wallet dialog -> this means the other containers remain light-weight and we don't have to pass around so much data (please follow that in future PRs and let's refactor existing dialogs to this pattern.
- Fixed the styling / proportions of dialogs in our app
=> [daef-57] add wallet deletion feature

.eslintrc, app/Routes.js, app/actions/router-actions.js, app/containers/wallet/Wallet.js, app/containers/wallet/WalletSettingsPage.js, app/containers/wallet/dialogs/DeleteWalletDialogContainer.js, app/lib/routing-helpers.js, app/stores/AppStore.js, app/stores/NetworkStatusStore.js, app/stores/UiDialogsStore.js, app/stores/WalletsStore.js, app/stores/index.js
This PR improves and simplifies the way we construct routes for redirecting / matching.
Instead of this:
```js
`${wallets.BASE_ROUTE}/${wallets.active.id}/${screen}`
```
you can now do this:
```js
buildRoute(ROUTES.WALLETS.PAGE, { id: wallets.active.id, page })
```
This is less error prone and will be easier to refactor later on.
All the route paths are defined in one place with params etc. so you can just look up what to pass in and it will automatically generate the correct route for you.
=> [DAEF-125] improve the way we construct dynamic route paths

app/api/CardanoClientApi.js, app/stores/AdaRedemptionStore.js, app/stores/NetworkStatusStore.js, app/stores/WalletsStore.js, electron/lib/getLogFilePath.js, electron/main.development.js, package.json
This PR introduces file and main process logging via [electron-log](https://www.npmjs.com/package/electron-log) and configures them like this:
```js
Log.transports.console.level = 'warn';
Log.transports.file.level = 'debug';
```
The result is that we don't have any unnecessary outputs in the dev tools anymore (yeah!) and by default everything is logged to the file and only `warn` messages are appearing in the terminal where you started the app (e.g: with `npm run dev`). Any normal `console.log` messages will still appear in the dev tool console (handy for development).
This also means that we can now log on the main process (e.g: when decrypting files / reading PDFs etc.)
The log files will be written into the same folder as the other logs (from cardano-node etc.) are:
osx: …
=> [daef-23] introduce file logging

app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
User should not be able to go back or clear the mnemonic after he/she entered it correctly:
=> [DAEF-74] removes back and clear button from recovery phrase dialog

.eslintrc, app/api/CardanoClientApi.js, app/components/layout/TopBar.js, app/components/wallet/summary/WalletSummary.js, app/components/widgets/Transaction.js, app/config/numbersConfig.js, app/containers/wallet/WalletSummaryPage.js, app/domain/Wallet.js, app/domain/WalletTransaction.js, app/stores/SettingsStore.js, app/stores/SidebarStore.js, app/stores/TransactionsStore.js, package.json
This PR fixes the current bug that we treat the lovelace amounts from backend like ADA in the frontend. It introduces the [bignumber.js](https://github.com/MikeMcl/bignumber.js/) package to work with arbitrary numbers and formatting.
=> [DAEF-138] convert lovelace amounts from backend into ada on frontend

electron/lib/getLogsFolderPath.js
This PR introduces Linux configuration for the logger and fixes Daedalus not working on Linux issue.
=> [DAEF-146] Add linux support for logger

app/api/CardanoClientApi.js, app/components/loading/Loading.js, app/containers/LoadingPage.js, package.json
This PR replaces API storing loading and saving users locale from the backend with local storage. This is temporary workaround before we implement `BackendReady` notification.
=> fix/daef-160 Save users locale to local storage

app/api/CardanoClientApi.js, app/components/wallet/ada-redemption/AdaRedemptionForm.js, app/components/wallet/ada-redemption/AdaRedemptionSuccessOverlay.js, app/containers/wallet/AdaRedemptionPage.js, app/stores/AdaRedemptionStore.js
This PR updates API calls to renamed Ada redemption endpoints. It also fixes two smaller issues: Backend now returns a string in the transaction with redeemed Ada, not number. And parsing error specific to regular vending is now only displayed when the user is doing the redemption for regular vended Ada.
=> [DAEF-158] Update to renamed endpoints for ada redemption

installers/WindowsInstaller.hs
The batch script shortcut target introduced in CSLA-62 causes a
minimized CMD window to spawn when opening the Daedalus shortcut.
This approach for suppressing it has been tested manually on Windows
Server 2012 r2.
=> [DEVOPS-38] Hide minimized CMD window

CHANGELOG.md, app/i18n/locales/ja-JP.json
Wallet name was hardcoded to "Shopping" in Japanese translation. This PR fixes that.
=> [DAEF-170] Fix wallet name hardcoded in japanese translation issue

CHANGELOG.md, app/components/layout/TopBar.js, app/components/layout/TopBar.scss, app/containers/MainLayout.js, app/containers/profile/LanguageSelectionPage.js
This PR Introduces a fix for displaying hamburger button and wallet name in header only on wallet pages.
=> Fix/daef 165 hamburger button and wallets name are present on the Ada redemption and Settings screens.

.travis.yml, installers/MacInstaller.hs
If users don't have write access, CI will now fail since it won't be able to get the installer certificate.
Let's just sign for branch builds.
=> [DEVOPS-64] dont sign macos installer for PRs

.gitignore, README.md, appveyor.yml, scripts/build-installer-win64.bat, scripts/windows-build-fresh-daedalus.bat
- move most contents of the `appveyor.yml` build script into `scripts/windows-build-fresh-daedalus.bat`, adding some sanity checks on the way
- scripts/windows-build-fresh-daedalus.bat, for a shortcuttable easy builds on Windows
cc @domenkozar, @jmitchell
=> Windows build refactoring

.flowconfig
This PR configures Flow typings for MobX.
=> [DAEF-150] Chore / Set-up flow typings for mobx

.travis.yml, README.md, scripts/build-installer-unix.sh, scripts/osx-build-fresh-daedalus.sh
This completes the Daedalus local build automation (the first half of the effort was on Windows):
1. The build sequence is extracted into a stand-alone script, that is both invoked by CI and available for developer use.
2. A convenience script that allows a single-launch build of a fresh Daedalus version on OS X, that checks out a fresh version from git in a clean directory, installs Nix and invokes the build.
3. The `README.md` is revised in an attempt to provide better structure.
Known issues:
=> [DEVOPS-10]  OS X local build automation

installers/WindowsInstaller.hs
Installer currently fails to run for non-admin users without explicitly running it as an admin. To avoid the error we should preemptively request admin permission.
Manually verified using a local build on Windows Server 2012 r2.
=> [DEVOPS-118] Windows installer: escalate to admin exec level

appveyor.yml, installers/WindowsInstaller.hs, installers/cardano-launcher.exe.manifest
Necessary for getting an update Installer.exe to elevate to admin
execution level when run by an admin user.
DEVOPS-118 tried to address this by setting requestExecutionLevel
to admin, but it doesn't take take effect when executed by a
non-elevated exe (in this case cardano-launcher.exe).
This approach has been verified on a Windows 10 Pro VM.
=> [DEVOPS-102] Run cardano-launcher at highestAvailable level

CHANGELOG.md, app/components/wallet/WalletCreateDialog.js, app/components/wallet/WalletCreateDialog.scss, app/i18n/locales/en-US.json, package.json
This PR adds upcoming currencies to the create wallet dialog, as disabled options in the select component:
=> [DAEF-212] show upcoming currencies as disabled on create wallet dialog

scripts/build-installer-unix.sh
Fixes the URL for downloading daedalus bridge assets from S3 when
branch name has a / in it. Already tested in branch
nh2/csl-1004-node-catchup-improvements.
=> Fix builds on branches that have `/` in their name

CHANGELOG.md, app/components/wallet/settings/ChangeWalletPasswordDialog.js, app/components/wallet/settings/ChangeWalletPasswordDialog.scss, app/containers/wallet/dialogs/ChangeWalletPasswordDialogContainer.js, app/stores/WalletSettingsStore.js
This PR introduces improved error handling on "Set / Change / Remove wallet password" dialogs.
=> Fix/daef 286 Add error message handling on change password dialog

CHANGELOG.md, app/api/CardanoClientApi.js
This PR introduces improved API nextUpdate response errors handling by no longer logging "No updates available" response as an error (default success logger is used instead).
=> Fix/daef 317 Improve nextUpdate error handling

CHANGELOG.md, app/stores/WalletsStore.js
This PR resets last generated address and fixes the bug with showing the address of the different wallet on the receive page
=> [DAEF-328] Reset last generated address after switching wallets

CHANGELOG.md, app/stores/WalletsStore.js
This PR disables polling for wallet data while the wallet node is syncing. Polling while syncing is slowing dow the node.
To do:
=> [DAEF-325] Disable polling for wallet data while syncing

CHANGELOG.md, app/stores/NodeUpdateStore.js
We have disabled polling for wallet data while the node is syncing to reduce the load on the wallet node. This PR does the same for polling for the system update.
=> Fix - [DAEF-337] Disable polling for system update while connecting and syncing

CHANGELOG.md, app/api/CardanoClientApi.js
This PR removes temporary workaround for creating accounts during wallet create or wallet restore features.
=> Fix/daef 348 Remove create-account API call from wallet restore handler

CHANGELOG.md, app/components/widgets/Transaction.js
This PR prevents React key duplicates in transaction from/to addresses lists.
=> Fix/daef 351 Fix React key bug in transaction list

CHANGELOG.md, app/i18n/locales/ja-JP.json, app/i18n/locales/terms-of-use/ja-JP.md
This PR updates label for accepting terms of use for Japanese locale to: "I understand that Terms of User are available in English only and I agree with Terms of Use.", translated into Japanese. This will be removed tomorrow but in case Japanese translations are not delivered this will serve as a workaround.
=> [DAEF-350] Accepting terms of use in English for Japanese locale

CHANGELOG.md, app/api/CardanoClientApi.js
This PR introduces a fix which presents more specific error message on Change password dialog.
=> Fix/daef 354 Show more specific error messages on Change password dialog

CHANGELOG.md, app/components/wallet/ada-redemption/AdaRedemptionForm.js
This PR introduces a fix which prevents selected wallet reset on Ada redemption screen on tab change and certificate add/remove events.
=> Fix/daef 357 Prevent selected wallet reset on "Ada redemption" screen on tab or certificate change

installers/Launcher.hs, installers/MacInstaller.hs, installers/WindowsInstaller.hs
Appveyor build tested on Win64, Travis Mac build verified (by looking at the launcher script) but not tested.
=> [CSL-1303] Include `updater-windows-runner` into Daedalus launcher for Windows 

CHANGELOG.md, app/components/wallet/WalletReceive.scss
This PR introduces updated "used" address styling on Wallet's receive screen.
=> Fix/daef 362 Update used addresses styling on wallet receive screen

CHANGELOG.md, electron/main.development.js
This PR fixes the behavior on osx to close the whole Daedalus app when the last window is closed.
=> [DAEF-202] properly shutdown app when closing window on osx

CHANGELOG.md, package.json
This PR updates react-polymorph plugin to latest release which contains Numeric input component fix for caret positioning bug.
=> Fix/daef 374 Numeric input component caret position bug

CHANGELOG.md, README.md, features/README.md
This PR introduced Daedalus frontend acceptance tests README file where it is documented how to run acceptance tests.
=> Chore/daef 382 Write documentation for running Daedalus frontend acceptance tests

CHANGELOG.md, electron/main.development.js
This PR introduces support for Cmd+H hotkey on OSX which hides the application window.
=> Feature/daef 385 Implement CMD+H hotkey

scripts/build-installer-win64.bat
In stack v1.4.0 the stack executable was in the root of the downloaded
zip, but now in stack v1.5.0 it's under the stack.exe directory. The
link we're using now resolves to stack v1.5.0.
=> [DEVOPS-223] AppVeyor: stack 1.5.0 upgrade

CHANGELOG.md, app/components/wallet/PaperWalletImportDialog.scss, app/components/wallet/WalletCreateDialog.scss, app/components/wallet/WalletRestoreDialog.scss, app/components/wallet/key-import/WalletKeyImportDialog.scss, app/components/widgets/forms/FileUploadWidget.scss, app/themes/mixins/place-form-field-error-below-input.scss
This PR introduces a fix for spending-password field error positioning in order to avoid label/error-message text overlapping in Japanese translations. The issue was solved by moving error messages below the input fields:
=> Fix/daef 360 Japanese translation bugs

scripts/build-installer-win64.bat
When stack-1.5.0 was initially released the zip file for the Windows
build put stack.exe in a different place. They've since reverted that
change, so this reverts the now outdated fix as well.
=> [DEVOPS-223] AppVeyor: revert stack.exe fix

CHANGELOG.md, README.md
This PR updates README file's "Development - network options" section. `staging` option is removed from available options list.
=> Chore/daef 389 Update README file's NETWORK env variable options

CHANGELOG.md, app/actions/wallet-settings-actions.js, app/components/wallet/WalletSettings.js, app/components/wallet/WalletSettings.scss, app/components/widgets/forms/InlineEditingDropdown.js, app/components/widgets/forms/InlineEditingDropdown.scss, app/components/widgets/forms/InlineEditingInput.js, app/components/widgets/forms/InlineEditingInput.scss, app/components/widgets/forms/ReadOnlyInput.scss, app/containers/wallet/WalletSettingsPage.js, app/i18n/locales/de-DE.json, app/i18n/locales/defaultMessages.json, app/i18n/locales/en-US.json, app/i18n/locales/hr-HR.json, app/i18n/locales/ja-JP.json, app/i18n/locales/ko-KR.json, app/i18n/locales/zh-CN.json, app/stores/WalletSettingsStore.js, features/step_definitions/settings-steps.js
This PR introduces a fix for success-messages issues on wallet setting screen.
As a part of this PR InlineEditingDropdown component has been refactored and WalletSettingsStore code simplified.
=> Fix/daef 333 Settings page wallet name success message is shown on transaction assurance update

CHANGELOG.md, app/components/wallet/PaperWalletImportDialog.js, app/components/wallet/WalletAddDialog.js, app/components/wallet/WalletCreateDialog.js, app/components/wallet/WalletRestoreDialog.js, app/components/wallet/key-import/WalletKeyImportDialog.js, app/components/widgets/Dialog.js, app/containers/wallet/WalletAddPage.js
This small PR solves the issue of dialogs being closable while wallet import/creation/restoring is happening, which could lead to problems if users are trying to use the not-yet-imported wallet (like sending transactions).
https://issues.serokell.io/issue/DAEF-393
=> [DAEF-393] force user to wait for dialog actions to be completed

CHANGELOG.md, app/components/wallet/WalletReceive.js, app/components/wallet/WalletReceive.scss, app/containers/wallet/WalletReceivePage.js
This PR implements missing 'used address' styling for default wallet address on wallet receive screen.
=> Fix/daef 411 Used address is not styled as used when it is the default

electron/main.development.js, electron/tls-workaround.js, package.json
Refactors the tls workaround from cardano-sl into the daedalus repo to (hopefully) fix the build issue:
```
Error: Cannot find module "daedalus-client-api/src/tls_workaround"
at webpackMissingModule (C:\Program Files\Daedalus2584\resources\app\dist\webpack:\electron\main.development.js:12:1)
at Object.<anonymous> (C:\Program Files\Daedalus2584\resources\app\dist\webpack:\electron\main.development.js:12:1)
at __webpack_require__ (C:\Program Files\Daedalus2584\resources\app\dist\webpack:\webpack\bootstrap a1c555050b822396d3a8:19:1)
at Object.<anonymous> (C:\Program Files\Daedalus2584\resources\app\dist\main.js:50:19)
at __webpack_require__ (C:\Program Files\Daedalus2584\resources\app\dist\webpack:\webpack\bootstrap a1c555050b822396d3a8:19:1)
at C:\Program …
```
=> [DAEF-427] move tls workaround into daedalus repo to fix build issue

.travis.yml, appveyor.yml, webpack/webpack.config.production.js
We had issues with latest builds where some api endpoints were missing and after some investigation i figured that we are building all releases against the old `cardano-sl-0.5` branch.
This PR updates the backend target branch to `master`
=> [DAEF-431] target latest master branch of cardano-sl for ci builds

CHANGELOG.md, app/api/CardanoClientApi.js, app/api/errors.js, app/i18n/locales/de-DE.json, app/i18n/locales/defaultMessages.json, app/i18n/locales/en-US.json, app/i18n/locales/hr-HR.json, app/i18n/locales/ja-JP.json, app/i18n/locales/ko-KR.json, app/i18n/locales/zh-CN.json
This PR implements correct error message shown for A -> A transaction error.
=> Fix/daef 376 Handle new backend error message for A -> A 

electron/lib/getRuntimeFolderPath.js, electron/main.development.js, installers/Launcher.hs, installers/MacInstaller.hs
=> [DEVOPS-299] Fix TLS certificate path

app/api/CardanoClientApi.js, app/api/js-api/lib/request.js, app/api/js-api/makePayment.js
This PR introduces a fix for broken send-money feature for wallets with spending password.
This is a temporary workaround until js-api makePayment call is fixed.
=> Fix/daef 465 Revert makePayment api call

CHANGELOG.md, app/components/widgets/WalletTestEnvironmentLabel.js, app/containers/TopBarContainer.js, app/i18n/locales/de-DE.json, app/i18n/locales/defaultMessages.json, app/i18n/locales/en-US.json, app/i18n/locales/hr-HR.json, app/i18n/locales/ja-JP.json, app/i18n/locales/ko-KR.json, app/i18n/locales/zh-CN.json
This PR replaces "Testnet v0.5" label with "Release candidate"  and refractors hardcoded value to be loaded from the translations.
=> Chore/DAEF 454 Testnet label for Release candidate

CHANGELOG.md, electron/main.development.js
This PR introduces a fix which prevents automatic application window focusing during acceptance testing.
Please note that the window still sets itself on top of other windows which can not be prevented BUT the good thing is that focus remains intact. Easy way to get around this is to simply drag the application window out of sight.
=> Fix/daef 395 Suppress electron window from forcing focus during acceptance testing

CHANGELOG.md, app/components/sidebar/wallets/SidebarWalletMenuItem.js, app/components/sidebar/wallets/SidebarWalletMenuItem.scss, app/i18n/global-messages.js, app/i18n/locales/de-DE.json, app/i18n/locales/defaultMessages.json, app/i18n/locales/en-US.json, app/i18n/locales/hr-HR.json, app/i18n/locales/ja-JP.json, app/i18n/locales/ko-KR.json, app/i18n/locales/zh-CN.json, app/lib/validations.js
This PR introduces maximum length validation (and limiting) of wallet name attribute.
Wallet name maximum length is set to 40 characters.
In the scope of this PR sidebar styling was updated - until now wallet name shown sidebar items was truncated via char count (which has different results based on width of individual characters) and now we use more precise CSS method (text-oveflow: ellipsis).
```
"global.errors.invalidWalletName": "Requires at least 3 and at most 40 letters."
```
=> Fix/daef 466 Limit and validate Wallet name max length

installers/WindowsInstaller.hs
It's possible for the Windows installer to "finish" before the build
certificates script has finished. This change may fix it, although it
hasn't yet been tested.
Before merging test the resulting CI build manually.
=> [DEVOPS-317] Windows installer: build cert synchronously

installers/WindowsInstaller.hs
This fixes log writing in case `%APPDATA%` has spaces in it -- mostly due to user name.
=> build-certificates-win64.bat:  fix logging for space-ful %APPDATA%.

installers/WindowsInstaller.hs
It's possible for the Windows installer to "finish" before the build
certificates script has finished.
=> [DEVOPS-317] Windows installer: build cert synchronously (#475)

installers/WindowsInstaller.hs
Primary motivation is to avoid an update installation clashing with an older version.
=> [DEVOPS-304] Subsequent Windows installs reuse install dir

CHANGELOG.md, app/stores/NetworkStatusStore.js, package.json
This bumps the version of react-polymorph to 0.3.3 which includes a fix for the dropdown label clicking issue (did open but not close on label click).
Todo:
=> Fix/daef 480 Fix minor react-polymorph dropdown bugs

CHANGELOG.md, app/api/CardanoClientApi.js, app/api/index.js, app/stores/NodeUpdateStore.js, flow/declarations/DaedalusClientApi.js
These changes should make Daedalus query `postponeUpdate` endpoint on postponing the update. The endpoint is introduced in https://github.com/input-output-hk/cardano-sl/pull/1586. This is needed to avoid problem with postponing the update described in https://issues.serokell.io/issue/CSM-458?query=%23CSM%20-Resolved
=> [CSM-458] Query `postponeUpdate` endpoint when postponing the update

CHANGELOG.md, app/stores/AppStore.js
This PR sets the dark theme as the default one for the `mainnet`.
To see this change while testing don't forget to run Daedalus with `NETWORK=mainnet npm run dev`.
=> Chore/daef 494 Set dark-theme as default one for the mainnet

CHANGELOG.md, app/api/CardanoClientApi.js
This PR changes how preferences are stored to local storage. Keys used for saving and loading preferences are now prefixed with network type (testnet, mainnet, development) so preferences for one network will not be reused for other networks.
=> [DAEF-497] Save preferences to local storage prefixed with network

CHANGELOG.md, app/components/wallet/WalletAddDialog.js, app/components/wallet/WalletSettings.js
This PR disables wallet file import AND export features for mainnet only. The features will still work in TN.
=> Fix/daef 508 Disable wallet file imports for mainnet

CHANGELOG.md, app/lib/logger.js
This PR changes the logging logic so that we only send errors to papertrail.
=> [DAEF-513] only send error logs to papertrail

electron/main.development.js
Limiting setMaximumSize does not really serve a purpose. It is actually more annoying to not being able to maximize the window on a 13" retina display.
=> Remove maximum window size limitations

installers/Launcher.hs, installers/MacInstaller.hs, installers/WindowsInstaller.hs
**Note: this PR shouldn't be merged until https://github.com/input-output-hk/cardano-sl/pull/1840 is merged.**
This PR does two things:
* it instructs the launcher to write its logs into `Logs/pub`
* it increases the node killing timeout to 30s (from 5s) because now the launcher uses SIGKILL and sigkilling the node after it's been given only 5×2 seconds to terminate is too harsh
=> [CSL-1747] Adapt to newer launcher features

CHANGELOG.md, app/stores/WalletsStore.js
This PR introduces a fix which takes care of hiding import/restore in-progress notification once this process is done. The issue was exposed in development mode where import/restore is finished within 500ms.
=> Fix/daef 544 Hide wallet import/restore notification message once process is done

CHANGELOG.md, electron/main.development.js
This PR introduces feature for starting and stopping Mantis client from Daedalus main process.
Currently it is implemented so that it can work with local Mantis client in development mode.
To start it use the following command: `API=etc MANTIS_PATH={path-to-mantis} npm run dev`
=> Feature/ddw 3 Launch mantis as part of startup

installers/WindowsInstaller.hs, installers/build-certificates-win64.bat, installers/cardano-installer.cabal, installers/cardano-installer.nix
This fixes #664 by removing the logic that used to choose the OpenSSL MD on OS X -- this sometimes breaks on Windows in an obscure way, apparently due to Powershell incompatibilities.
This also essentially breaks OS X Yosemite (circa 2014 and earlier) -- but those are arguably insecure to use: the last update, 10.10.5 is dated 13 Aug 2015.
Tested on Windows 7.
Sister mainnet hot-fix is https://github.com/input-output-hk/daedalus/pull/666
=> [DEVOPS-622/github #664]:  deprecate non-sha256 MD support in the cert generator

CHANGELOG.md, features/step_definitions/ada-redemption-steps.js
This PR modifies Ada redemption tests to run in `mainnet` mode, where Ada redemption warning is not shown.
To run the tests in mainnet mode use: `NETWORK=mainnet npm run test`
This PR contains ported work from the original PR: https://github.com/input-output-hk/daedalus/pull/498 which is to be closed in favour of this one.
=> Chore/ddw 82 Ada redemption tests in mainnnet mode

CHANGELOG.md, app/api/ada/index.js, app/stores/NetworkStatusStore.js
This PR introduces an improved connected/disconnected state detection which tracks `networkDifficulty` value and in case it remains unchanged for more than `2 minutes` redirects the user to the Connecting screen.
Described scenario happens when the Internet connection is lost and Api is unaware of new blocks and therefore sends the same `networkDifficulty` value to the UI.
=> Fix/ddw 61 Detect when wallet is out of sync

CHANGELOG.md, app/api/ada/lib/request.js, app/api/etc/lib/request.js, app/components/loading/Loading.js, app/stores/NetworkStatusStore.js
This PR introduces proper handling of Loading screen text messages for connecting and reconnecting scenarios:
- during initial application start `Connecting...` message is displayed
- later during any connection problems `Network connection lost - reconnecting...` message is displayed.
This PR also contains a very important fix for proper handling of `HTTP 500 Internal server errors` in Api responses. To replicate this problems exit/kill local backend node processes which will result in the following response errors:
...which break our requests as this message is returned as a string and the code expects a JSON object.
=> Fix/ddw 84 Improve connecting reconnecting messages on Loading screen

.nonsense, CHANGELOG.md, app/stores/NetworkStatusStore.js
This PR changes the logic for polling for local time difference:
- polling is started when connected
- polling is stopped when disconnected
- the polling interval is one hour
Changing the polling interval to one hour is a temporary measure needed since `/api/settings/time/difference` endpoint is consulting the NTP server every time and frequent polling is spamming. Later on, this endpoint will be fixed so the response from the NTP server will be cached. After that, we can poll more frequently.
=> Fix/DDW-93 Poll local time difference every 1 hour when connected

package.json, webpack/webpack.config.base.js
before:
```
import environment from '../../environment';
alert(process.env.REPORT_URL);
const messages = defineMessages({
```
after:
```
var n,o,i,s=a(7),l=r(s),u=a(3),c=r(u),d=a(2),f=r(d),h=a(4),p=r(h),m=a(6),g=r(m),v=a(5),y=r(v),b=a(1),w=(r(b),a(37)),A=r(w),k=a(9),T=a(12),L=a(11),x=r(L),M=a(567),C=r(M),N=a(171),S=r(N),D=a(961),P=r(D),E=a(1403),O=r(E),I=a(23),R=r(I);
alert("http://report-server.cardano-mainnet.iohk.io:8080");
var B=(0,T.defineMessages)({connecting:{id:"loading.screen.connectingToNetworkM...
```
after webpack has had its way with the source, the environment lookup is just gone and it becomes a hard-coded string
but if your running daedalus via `npm`, it will be untouched, and obey whatever you have manually set with `export REPORT_URL=foo` prior to running npm
=> [DEVOPS-676] bake the REPORT_URL into the binary at build time

CHANGELOG.md, app/stores/WalletStore.js, app/stores/ada/AdaWalletsStore.js
This PR improves async restore/import dialogs closing logic by enforcing the following:
```
Once restore/import is under way we need to either:
A) show the 'Add wallet' dialog (in case we don't have any wallets) or
B) just close the active dialog and unblock the UI
```
...which prevents the following situation:
=> Fix/ddw 119 Fix wallet restore reactions configuration

CHANGELOG.md, app/components/wallet/WalletReceive.js
This PR fixes a minor UI issue on the receive screen when generating new address for a wallet that has a spending password set. After submit the password field was cleared and remained in an error state … this is now fixed by simplifying the setup and removing the validation debounce (which doesn't have any positive UX effect in this case anyway)
=> [DDW-124] dont show validation error after clearing spending password field

installers/MacInstaller.hs, scripts/build-installer-unix.sh
Because with Buildkite we don't make builds for untrusted users.
=> [DEVOPS-685] installers: always sign Mac builds on Buildkite

default.nix, nixpkgs-src.json, scripts/build-installer-unix.sh, scripts/nix-shell.sh
This adds the full list of build dependencies required for building to the nix-shell.
There is also a change to make the `buildkite-agent` program available when running on nix-darwin.
I'm not sure I like the `nix-shell.sh` script. Perhaps if all build agents are configured with nix available and the pipelines specify `NIX_PATH`, then it wouldn't be required?
=> [DEVOPS-643] Fix nix-shell dependencies

CHANGELOG.md, app/components/loading/Loading.js
This PR fixes `Time sync error notification` display logic which had a flaw in terms of not displaying the error notification in case block syncing has not stated (or to be more precise - when `networkDifficulty` is not greater than `1`.
This is a minor change which has no impact on the data handling logic - the only change is in placement of `Time sync error notification` element within the Loading page.
=> Fix/ddw 139 Show time sync error even if the syncing has not started

default.nix, nixpkgs-src.json, scripts/build-installer-unix.sh, scripts/nix-shell.sh
Same as #746, for release branch so that there won't be build errors with the nix-darwin buildkite agents.
=> [DEVOPS-643] Fix nix-shell dependencies -- release branch

installers/launcher-config-mac.yaml, installers/launcher-config-windows.yaml
Previously all output from cardano-node was redirected to `cardano-node.log`.
Now we don't want it, because this file became quite big after several months.
Now output won't be redirected, cardano-node will inherit cardano-launcher's
stdout and stderr.
It should be tested though.
Note: there will still be logs in `node` and `node.pub` files.
`cardano-node.log` was duplicating them.
=> [CSL-2307] Do not redirect cardano-node's logs to a file

app/components/loading/Loading.js
This PR fixes a display logic of 'Having trouble syncing?' message on the Syncing screen.
Because of wrong comparison operator this message would show up 5 minutes after syncing percentage reached 9.99% and it would stay shown regardless of the syncing progress until syncing is done.
=> Fix/ddw 154 Show 'Having trouble syncing?' message only if syncing has stalled for 5 minutes

CHANGELOG.md, app/stores/TransactionsStore.js
This PR increases the limit of `get-all-transactions` call from `5` to `1000`.
We limit number of transactions on Summary screen, but on the Transactions screen all transactions should be shown.
=> Fix/ddw 166 Remove 5 transactions limit from transactions screen

appveyor.yml
Release 1.1.0 branch is not merged to master yet.
=> [DDW-169] Windows: move cardano-sl branch back to release/1.1.0

source/renderer/app/components/widgets/forms/InlineEditingInput.scss, source/renderer/app/components/widgets/forms/ReadOnlyInput.scss, source/renderer/app/themes/daedalus/cardano.js, source/renderer/app/themes/daedalus/dark-blue.js, source/renderer/app/themes/daedalus/light-blue.js, source/renderer/app/themes/simple/SimpleFormField.scss, source/renderer/app/themes/simple/SimpleInput.scss, source/renderer/app/themes/simple/_config.scss
This PR fixes bad styling of the disabled form input elements which was the result of React-Polymorph misconfiguration.
=> Fix/ddw 199 fix disabled form-fields background color

.buildkite/pipeline.yml, README.md, appveyor.yml, cardano-sl-src.json, cardano-sl.nix, default.nix, installers/AppVeyor.hs, installers/Config.hs, installers/MacInstaller.hs, installers/README.md, installers/RewriteLibs.hs, installers/Types.hs, installers/WindowsInstaller.hs, installers/daedalus-installer.cabal, installers/daedalus-installer.nix, installers/default.nix, installers/dhall-haskell.nix, installers/dhall-json.nix, installers/github.nix, installers/shell.nix, installers/stack.yaml, lib.nix, scripts/build-installer-unix.sh, scripts/build-installer-win64.bat, scripts/link-bridge.sh, scripts/osx-build-fresh-daedalus.sh, scripts/unlink-bridge.sh, scripts/windows-build-fresh-daedalus.bat, shell.nix
With input-output-hk/cardano-sl#2671, there is a `daedalus-bridge` which provides cardano-sl programs and config files.
This change integrates that cardano-sl built by nix into the installer build, according to a specific git revision, rather than downloading the latest build from a branch.
=> [DEVOPS-673] Pin cardano-sl to git revision instead of branch

CHANGELOG.md, electron/main.development.js, electron/menus/osx.js, electron/menus/win-linux.js
This PR fixes broken copy&past context menu actions on Windows.
It also adds an `Edit` tab with various options to the application menu:
=> Fix/ddw 160 Debug context menu copy & paste actions on Windows [HOTFIX]

CHANGELOG.md, source/main/menus/osx.js, source/main/menus/win-linux.js, source/main/windows/main.js
This PR fixes broken copy&past context menu actions on Windows.
It also adds an `Edit` tab with various options to the application menu:
=> Fix/ddw 160 Debug context menu copy & paste actions on Windows

electron/menus/win-linux.js
This PR fixes missing application menu (Daedalus/Edit/View) on Windows build.
**Before the fix:**
**After the fix:**
=> Fix/ddw 212 Fix missing application menu on Windows build

installers/WindowsInstaller.hs
This PR fixes the broken Daedalus shortcut icon on Windows platform:
=> [DEVOPS-775] create the shortcut on the desktop after copying the binaries and creating certs

CHANGELOG.md, source/main/utils/setupLogging.js
This PR updates the date in Daedalus logs so that it is always shown in UTC instead of local time.
Before (local time - UTC+2):
```
[2018-04-03 21:37:34.0478] [debug] Local difficulty changed: 1124
```
After (UTC time - no timezone info:
```
[2018-04-03T19:37:34.0478Z] [debug] Local difficulty changed: 1124
```
=> Chore/ddw 165 Daedalus logs should be in UTC instead of local time

source/renderer/app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.js, source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseDisplayDialog.js, source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
This PR prevents the closing of the wallet backup dialogs on a click outside of the dialog content.
=> Chore/ddw 156 Clicking outside of the dialogs should not close them during wallet creation

source/renderer/app/components/static/About.js, source/renderer/app/i18n/locales/defaultMessages.json, source/renderer/app/i18n/locales/en-US.json, source/renderer/app/i18n/locales/ja-JP.json
This PR updates the list of Daedalus members shown in the About dialog:
=> Chore/ddw 193 About dialog micro issue

source/common/environment.js, source/main/windows/main.js, source/renderer/app/components/static/About.js, source/renderer/app/i18n/locales/de-DE.json, source/renderer/app/i18n/locales/defaultMessages.json, source/renderer/app/i18n/locales/en-US.json, source/renderer/app/i18n/locales/hr-HR.json, source/renderer/app/i18n/locales/ja-JP.json, source/renderer/app/i18n/locales/ko-KR.json, source/renderer/app/i18n/locales/zh-CN.json
This PR adds Daedalus version into application title. The title will no longer show `current` environment in production.
It also removes version info from localization files and refactors the code to use `environment.version` which is derived from `package.json` version info. This simplifies the version changes as you only need to update the one in `package.json`.
=> Chore/ddw 171 Print Daedalus version in application title

source/renderer/app/components/profile/bug-report/BugReportDialog.scss
This PR fixes text color issues within Manual bug report dialog in Dark blue theme.
The color for this part of UI was hardcoded which means all 3 themes used the same value (appropriate for Light blue theme).
=> Fix/ddw 150 Send manual bug report wrong text color in Dark blue theme

source/renderer/app/components/wallet/transactions/Transaction.js
This PR fixes an issue where transaction with 0 confirmations shows in `low` transaction assurance state instead of `transaction pending` state.
=> Fix/ddw 155 Transaction with 0 confirmations should be in pending

source/main/ipc-api/get-logs.js, source/renderer/app/themes/daedalus/dark-blue.js
This PR enforces correct ordering of log files within the Bug report dialog:
=> Chore/ddw 126 Bug report dialog logs alphabetical ordering

source/renderer/app/actions/profile-actions.js, source/renderer/app/components/profile/bug-report/BugReportDialog.js, source/renderer/app/containers/profile/dialogs/BugReportDialogContainer.js, source/renderer/app/stores/ProfileStore.js
This PR sets the "Attach logs" switch by default to true within the support dialog:
...it also fixed several flow-type issues.
=> Chore/ddw 146 "Attach logs" should be on by default for support requests

CHANGELOG.md, app/api/ada/lib/request.js, features/wallet-settings.feature
JavaScript length method (with ES6) actually counts unicode punycodes of the UTF-16 encoding of the given string. Apart from messing up with surrogate pairs (counting for instance 💩 as two characters because encoded with a pair or punycodes), it also leads to unexpected results when characters have a different UTF-8 and UTF-16 encoding.
Since requests are made using UTF-8 encoding, the Content-Length of these requests should match the actual length when payloads are UTF-8 encoded.
This PR is a port of https://github.com/input-output-hk/daedalus/pull/839
**Before the fix:**
**After the fix:**
=> [CSL-2435] Use 'TextEncoder' to measure correct length of UTF-8 strings

appveyor.yml, installers/AppVeyor.hs
To find `CardanoSL.zip` on Appveyor it uses the GitHub commit status API. This is subject to rate limiting. So provide an OAuth token in an environment variable.
=> [DEVOPS-776] make-installers: avoid GitHub rate limiting

CHANGELOG.md, source/renderer/app/api/ada/index.js, source/renderer/app/components/loading/Loading.js, source/renderer/app/components/loading/SystemTimeErrorOverlay.js, source/renderer/app/containers/LoadingPage.js, source/renderer/app/containers/etc/LoadingPage.js, source/renderer/app/i18n/locales/defaultMessages.json, source/renderer/app/i18n/locales/en-US.json, source/renderer/app/i18n/locales/ja-JP.json, source/renderer/app/stores/NetworkStatusStore.js
This PR updates the error message shown on the NTP time synchronisation error screen.
The message now covers both possible error cases - being `behind` and `ahead` of actual time.
Handling for positive and negative time offset is added and both are handled the same way (absolute time offset is used). The polling interval for NTP time check has been reduced from 60 to 30 mins.
=> Chore/ddw 204 Update NTP Api endpoint handling

CHANGELOG.md, source/renderer/app/components/settings/categories/SupportSettings.scss, source/renderer/app/components/sidebar/Sidebar.js, source/renderer/app/containers/MainLayout.js, source/renderer/app/containers/etc/MainLayout.js, source/renderer/app/themes/daedalus/cardano.js, source/renderer/app/themes/daedalus/dark-blue.js, source/renderer/app/themes/daedalus/light-blue.js
This PR changes the click action on bug icon in the sidebar. Click on this icon opens Settings > Support page instead of the Support Request dialog.
Also, the styling of the links on the Settings > Support page has been improved (links are now more noticeable).
=> Chore/ddw 215 Bug reporting feature should display support page

CHANGELOG.md, source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.js, source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.scss, source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.js, source/renderer/app/components/widgets/ProgressBar.js, source/renderer/app/components/widgets/ProgressBar.scss, source/renderer/app/stores/SidebarStore.js, source/renderer/app/themes/daedalus/cardano.js, source/renderer/app/themes/daedalus/dark-blue.js, source/renderer/app/themes/daedalus/light-blue.js
This PR adds a linear progress bar restore indicator in the sidebar. This way it is straight away visible if user has an active wallet restore running or not.
=> Feature/ddw 228 Wallet restore indicator in sidebar

.buildkite/pipeline.yml, appveyor.yml, installers/WindowsInstaller.hs, release.nix, scripts/build-installer-nix.sh, scripts/build-installer-unix.sh, scripts/build-installer-win64.bat
This is a proposed RC bugfix with the full fix going on the develop branch. The change only affects CI.
It changes the AppVeyor config so that Windows installer filename is up to date with the cardano-sl version of this release.
=> [DEVOPS-807] Installer filename consistency and bump version 1.1 -> 1.2.0

CHANGELOG.md, features/step_definitions/wallets-steps.js, features/support/helpers/notifications-helpers.js
This PR fixes the fragile step definition by checking the actual sync status of the active wallet before testing the DOM. If the restoration was too fast, the sync status will not be 'restoring'  anymore and thus we can't test the DOM anymore.
=> Fix/ddw 242 Step for active restore notification is too fragile

source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.js
This PR fixes issues with recognition of QR code displayed on the last dialog within the Paper wallet certificate generator feature. In order to increase compatibility the size of the QR code had to be slightly reduced to match the size of the QR code we already use on the Receive screen (and we are 100% sure that this one works correctly).
=> Fix/ddw 247 Fix paper wallet QR code issues on Confirmation dialog

source/renderer/app/actions/profile-actions.js, source/renderer/app/components/profile/bug-report/BugReportDialog.js, source/renderer/app/containers/profile/dialogs/BugReportDialogContainer.js, source/renderer/app/containers/settings/categories/SupportSettingsPage.js, source/renderer/app/stores/ProfileStore.js
This PR fixes few issues:
- **General > Support** page "Download logs" link now on every click packs fresh `logs.zip` file which is then downloaded to the user's machine
- **Support Request** dialog now on *will-mount* event deletes existing `logs.zip` file in order to pack a fresh one on dialog submit (if user selected to attach the logs)
=> Fix/ddw 244 Delete logs.zip on support dialog mount

cardano-sl-src.json
This PR bumps `Cardano SL` version used in Daedalus to the latest `release/1.2.0` revision.
=> cardano-sl:  bump to 44fa9a8b/release/1.2.0

installers/dhall/linux64.dhall, installers/dhall/macos64.dhall, installers/dhall/os.type, installers/dhall/win64.dhall
For some reason, on macOS 10.11 electron won't start if its stdout is closed.
For example, this won't work:
/Applications/Daedalus.app/Contents/MacOS/Frontend 1>&- 2>&-
And it happens that cardano-launcher closes stdout, unless walletLogging in the launcher config is true.
So, only for macOS, enable the walletLogging option.
=> [DDW-253] installer configs: Work around macOS 10.11 launcher error

CHANGELOG.md, README.md, features/README.md
This PR adds `Author` and `Status` information to all Daedalus GitHub README files:
- Main [README file](https://github.com/input-output-hk/daedalus/blob/chore/ddw-258-add-owner-info-to-all-daedalus-github-documents/README.md)
- Features [README file](https://github.com/input-output-hk/daedalus/blob/chore/ddw-258-add-owner-info-to-all-daedalus-github-documents/features/README.md)
---
=> Chore/ddw 258 Add owner info to all Daedalus GitHub documents

appveyor.yml
The installer filenames have correct versions derived from cabal files and `package.json`.
PR #874 removed all versions from `appveyor.yml`. However the AppVeyor "build version" defaults to `1.0.{build}` which is almost always wrong. So this change removes the `1.0.` prefix.
=> [DEVOPS-771] AppVeyor: remove 1.0. prefix from build version

CHANGELOG.md, source/renderer/app/api/ada/index.js, source/renderer/app/api/etc/index.js
This PR improves our error handling by logging expected error cases only as debug messages instead of spamming our dev console.
=> [DDW-231] log expected errors as debug messages only

.buildkite/pipeline.yml, appveyor.yml, installers/Installer.hs, installers/Types.hs
Since we now generate both mainnet and staging installers from a single CI build, the NETWORK environment variable can no longer be set in the CI pipeline config.
=> [DDW-265] installers: fix network setting of staging build

.buildkite/pipeline.yml, scripts/build-installer-nix.sh, scripts/build-installer-unix.sh
This makes it possible to download all the installer artifacts without being logged into Buildkite.
=> [DEVOPS-788] buildkite: Put linux installers in public S3 bucket

CHANGELOG.md, source/renderer/app/api/ada/sendAdaBugReport.js, source/renderer/app/api/etc/sendEtcBugReport.js
This PR fixes broken bug report requests that used a fixed `0.0.1` version. This is replaced with the `environment.version` constant now.
---
=> [DDW-292] use correct daedalus version in bug requests

CHANGELOG.md, source/renderer/app/api/ada/getAdaWallets.js, source/renderer/app/components/wallet/WalletAdd.js, source/renderer/app/components/wallet/WalletAdd.scss, source/renderer/app/config/numbersConfig.js, source/renderer/app/containers/wallet/WalletAddPage.js, source/renderer/app/i18n/locales/de-DE.json, source/renderer/app/i18n/locales/defaultMessages.json, source/renderer/app/i18n/locales/en-US.json, source/renderer/app/i18n/locales/hr-HR.json, source/renderer/app/i18n/locales/ja-JP.json, source/renderer/app/i18n/locales/ko-KR.json, source/renderer/app/i18n/locales/zh-CN.json, source/renderer/app/stores/ada/AdaWalletsStore.js
Fixed presentation bug that caused only ten wallets to be shown in the wallets list, even though there were more than ten wallets in the application.
---
=> [DDW-300] Increase wallets limit to 50

CHANGELOG.md, installers/nix/linux.nix, yarn2nix.nix
This PR fixes reporting server URL used for submitting support requests for the Linux build of Daedalus.
---
=> [DEVOPS-796] fix cp interactive in nix scripts

CHANGELOG.md, installers/dhall/launcher.dhall
This PR fixes the missing launcher log files.
=> [DEVOPS-888] set a logs prefix for launcher

CHANGELOG.md, cardano-sl-src.json, installers/WindowsInstaller.hs, installers/dhall/linux64.dhall, installers/dhall/macos64.dhall, installers/dhall/os.type, installers/dhall/win64.dhall
This PR disables allow skip files so users can't ignore errors if cardano-node is already running. It also adds a lockfile to cardano-launcher so multiple launchers can't be running at the same time.
=> [DEVOPS-872] disable allow skip files and adds a launcher lock file

cardano-sl-src.json
Pulls in the latest Cardano 1.2.1 release revision, including applicationVersion and cabal version bumps.
N/A
N/A
---
=> Cardano 1.2.1 release bump

.buildkite/pipeline.yml, appveyor.yml, installers/WindowsInstaller.hs, release.nix, scripts/build-installer-unix.sh, scripts/build-installer-win64.bat
This PR changes the installer filenames to reflect the current version.
It's a manual search&replace process on for the 0.10.x series, but will be automatic starting with 0.11.0.
Have checked it with the following commands:
git grep --color '1\.2\.0' | grep -v '[.-]lock'
git grep --color '0\.10\.0' | grep -v '[.-]lock' | grep -v '\.svg'
=> [DEVOPS-900] Bump version to 0.10.1-cardano-sl-1.2.1

CHANGELOG.md, source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseMnemonic.scss, source/renderer/app/components/wallet/paper-wallet-certificate/SecuringPasswordDialog.scss, source/renderer/app/components/widgets/Dialog.scss, source/renderer/app/themes/index.global.scss
This PR improves text display by reducing letter-spacing.
Since a new NotoSans font was introduced we need to slightly modify the `letter-spacing` in order to make the new font look more compact and to save space.
We need to do the following:
- remove global body CSS `letter-spacing: 1px` rule
- change Dialog title CSS `letter-spacing` from 2px to 1px
- add `word-spacing: 2px` to Mnemonics box on both Wallet create and Paper wallet create dialogs
---
=> [DDW-317] Font display improvements

cardano-sl-src.json
Cardano SL release/1.3.0 branch exists now. This is the current version of that branch.
=> [DEVOPS-906] Update cardano-sl to tip of release/1.3.0

CHANGELOG.md, features/step_definitions/wallets-limit.js, features/step_definitions/wallets-steps.js, features/support/helpers/shared-helpers.js, features/support/helpers/wallets-helpers.js, features/wallets-limit.feature
This PR adds acceptance tests for maximum wallets limit.
---
=> [DDW-302] Add acceptance tests for maximum wallets limit

CHANGELOG.md, source/renderer/app/components/profile/bug-report/BugReportDialog.js, source/renderer/app/components/profile/language-selection/LanguageSelectionForm.js, source/renderer/app/components/profile/terms-of-use/TermsOfUseForm.js, source/renderer/app/components/wallet/WalletCreateDialog.js, source/renderer/app/components/wallet/WalletReceive.js, source/renderer/app/components/wallet/WalletRestoreDialog.js, source/renderer/app/components/wallet/WalletSendConfirmationDialog.js, source/renderer/app/components/wallet/WalletSendForm.js, source/renderer/app/components/wallet/ada-redemption/AdaRedemptionForm.js, source/renderer/app/components/wallet/etc/WalletSendForm.js, source/renderer/app/components/wallet/settings/ChangeWalletPasswordDialog.js, source/renderer/app/components/wallet/settings/DeleteWalletConfirmationDialog.js, source/renderer/app/components/wallet/settings/export-to-file/WalletExportToFileDialog.js, source/renderer/app/components/widgets/Dialog.js, source/renderer/app/components/widgets/Dialog.scss, source/renderer/app/components/widgets/DialogCloseButton.js, source/renderer/app/themes/daedalus/cardano.js, source/renderer/app/themes/daedalus/dark-blue.js, source/renderer/app/themes/daedalus/light-blue.js, source/renderer/app/themes/simple/SimpleButton.scss, source/renderer/app/utils/form.js
This PR enables submitting forms on Enter key press.
---
=> [DDW-173] Submit forms on Enter key

.eslintrc, default.nix, installers/Spec.hs, installers/common/MacInstaller.hs, installers/common/Util.hs, installers/common/WindowsInstaller.hs, release.nix, scripts/build-installer-nix.sh, scripts/build-installer-win64.bat, source/common/environment.js, source/main/webpack.config.js, source/renderer/app/components/static/About.js, source/renderer/app/i18n/global-messages.js, source/renderer/app/i18n/locales/de-DE.json, source/renderer/app/i18n/locales/defaultMessages.json, source/renderer/app/i18n/locales/en-US.json, source/renderer/app/i18n/locales/hr-HR.json, source/renderer/app/i18n/locales/ja-JP.json, source/renderer/app/i18n/locales/ko-KR.json, source/renderer/app/i18n/locales/zh-CN.json, source/renderer/webpack.config.js, yarn2nix.nix
* Renames the variable `DAEDALUS_VERSION` to `BUILD_NUMBER` because that's what it contains.
* Makes sure that `BUILD_NUMBER` is set for the Windows and macOS builds.
* Adds new variable `API_VERSION` and sets to the cardano-sl version known at build time.
* Uses these new ENV variables in place of hardcoded translation key files versions
=> [DEVOPS-919] installers: provide BUILD_NUMBER and API_VERSION

cardano-sl-src.json, installers/README.md, installers/common/Config.hs, installers/dhall/linux64.dhall, installers/dhall/testnet.dhall, installers/nix/linux.nix, scripts/build-installer-unix.sh
Configures the testnet installer so that the wallet can connect to the public testnet.
=> [DEVOPS-398] installers: Add config for public testnet

installers/Spec.hs, installers/common/Config.hs, installers/common/MacInstaller.hs, installers/common/Types.hs, installers/common/WindowsInstaller.hs
I forgot to update the installer filenames to add the backend name which was removed from the get version function.
=> [DEVOPS-919] installers: fix missing backend in filenames

CHANGELOG.md, source/renderer/app/stores/ada/AdaWalletsStore.js
This PR prevents wallet data polling during wallet deletion in order to prevent data refresh for deleted wallet (due deletion/refresh requests race conditions).
In the scope of this PR some of the `AdaWalletsStore` methods which were not declared as `@actions` have been fixed as well.
---
=> [DDW-221] Prevent wallet data polling during wallet deletion

source/renderer/app/components/static/About.js, source/renderer/app/components/static/About.scss, source/renderer/app/containers/static/AboutDialog.js
This PR fixes the links in the About dialog. Currently, they get open in the Daedalus window and thus prevents the user from using Daedalus once they are open (no way back).
---
=> [DDW-349] Open About dialog links in a new browser window

installers/dhall/linux64.dhall, installers/dhall/macos64.dhall, installers/dhall/os.type, installers/dhall/win64.dhall
This PR makes the nodelLogPath entry in launcher-config.yaml optional , this will have the effect of disabling logging to cardano-node.log which was deamed to be causing a performance issue
=> [DDW-369] Disable nodeLogPath in dhall files

CHANGELOG.md
This PR adds missing changelog entries for PR: https://github.com/input-output-hk/daedalus/pull/1027
=> [DDW-369] Add missing entries to the changelog

installers/Spec.hs, installers/dhall/staging.dhall, installers/dhall/testnet.dhall, yarn2nix.nix
Ports for cardano-node backend:
- 8090 - mainnet
- 8092 - staging
- 8094 - testnet
- 8091 - api docs server
Next version will have dynamic ports.
=> [DEVOPS-922] Choose backend ports for staging and testnet which don't conflict

cardano-sl-src.json
This PR bumps `cardano-sl` version to HEAD of 1.3.1 branch.
=> [DEVOPS-998] bump cardano-sl to HEAD of 1.3.1

.gitignore, shell.nix, source/main/utils/getRuntimeFolderPath.js
These are some basic changes to help QA with running daedalus with a demo cluster.
Overrides runTimePath to "./" when ran with `yarn dev` so logs are written to `Logs/pub/Daedalus.log` in current directory.
Improves nix shell code to give instructions on how to use.
Minor refactor to support multiple derivations in `shell.nix` using `passthru`.
=> [DEVOPS-1020] add logs in dev mode and nix improvements

cardano-sl-src.json
Cardano SL 1.3.1 will have configuration and genesis data for the public testnet.
~Once input-output-hk/cardano-sl#3265 is merged then the cardano-sl rev can be updated again to latest `release/1.3.1` and this can be merged.~ Cardano SL release/1.3.1 is ready to go.
The installers built in CI from this PR should be able to connect to the public testnet.
Then you can get Testnet Ada from http://cardano-faucet.cardano-testnet.iohkdev.io/
It should be possible to install and run mainnet and testnet Daedalus simultaneously, and the testnet version should be clearly marked as such.
- [daedalus-0.11.1-cardano-sl-1.3.1-testnet-windows-9114.exe](https://appveyor-ci-deploy.s3-ap-northeast-1.amazonaws.com/installers/daedalus-0.11.1-cardano-sl-1.3.1-testnet-windows-9114.exe)
- …
=> [DEVOPS-398] Update to cardano-sl 1.3.1

.gitignore, default.nix, shell.nix, source/main/windows/main.js
Fix the startup hang on Linux, which looks like the following in the console:
```
$ /nix/store/rlp0drkvym62aljwrfj2nzs4z6dz3zdd-daedalus/bin/daedalus
+ export PATH=/nix/store/xrq40a9c4lv20p4a69js1y1gm43kdsgp-daedalus-frontend/bin/:/nix/store/vcnsd7mqcbmfzcwnp6slz6i25f9yic4p-cardano-daedalus-bridge-1.3.0/bin:/home/deepfire/Applications/.bin:/nix/store/lcin62a066vz93jn8ac9vj9qnjl2cdhy-enlightenment-0.22.4/bin:/home/deepfire/bin:/run/wrappers/bin:/home/deepfire/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/etc/profiles/per-user/deepfire/bin:/home/deepfire/bin
+ PATH=/nix/store/xrq40a9c4lv20p4a69js1y1gm43kdsgp-daedalus-frontend/bin/:/nix/store/vcnsd7mqcbmfzcwnp6slz6i25f9yic4p-cardano-daedalus-bridge-1.3.0/bin:/home/deepfire/Applications/.bin:/nix/store/lcin62a0 …
```
=> main window on Linux:  icon relative to process.env.DAEDALUS_INSTALL_DIRECTORY

package.json, source/main/cardano/CardanoNode.js, source/main/index.js, source/main/utils/lockFiles.js, source/main/utils/processes.js
This PR improves the logic that ensures only a single instance of Daedalus is running per cluster.
Several common cases are handled now:
- The current process name is used to generate the lockfiles.
- In case there is an existing lockfile when starting Daedalus, it now also checks if there is really another instance running with the same before concluding that the lock is taken.
- If no other Daedalus instance with the same name is running (but the lockfile exists) it deletes the existing lock and creates a new one for the current instance.
---
=> [DDW 436] Improve Daedalus lock file handling

.gitignore, shell.nix, source/main/cardano/config.js, source/main/config.js
This PR adds `--log-config` argument to Cardano spawn call and updates `shell.nix` so that it exposes `log-config-prod.yaml` file in local development.
---
=> [DDW-438] Fix missing Cardano node pub logs

CHANGELOG.md, source/renderer/app/components/notifications/AntivirusRestaurationSlowdownNotification.scss
This PR makes the close button full height within the `AntivirusRestaurationSlowdownNotification` component so that when the button is in a `:hover` state, the dark red background assumes the full height of the AntiVirus notification.
=> [DDW-443] Fix Antivirus Notification Close Button Hover Color

default.nix, installers/nix/nix-installer.nix
This PR allows `xdg-open` to work from within the sandbox, so electron can now open links
this also changes the error `nix-user-chroot` gives when user namespaces need to be enabled, it now shows how to correctly run it with `sudo`.
this handles DEVOPS-1105, the `~/.local/bin/daedalus` is only mainnet from now on
---
=> [DEVOPS-1095] allow opening links when in the sandbox

cardano-sl-src.json
Another cardano-sl revision bump due to the late merge of input-output-hk/cardano-sl#3742.
=> [DEVOPS-1112] Update cardano-sl to latest release/2.0.0 branch

CHANGELOG.md, source/main/config.js, source/main/index.js
This PR fixes main process error when launcher-config is missing - as in a situation where you start Daedalus using `Daedalus.exe` instead of the `Launcher.exe` on Windows.
It also fixes a problem with orphaned processes after Daedalus quits in the case of missing launcher-config as well as after realizing there is already one Daedalus instance running `[DDW-485]`.
In the scope of the same PR Daedalus lockfile handling was updated so that instead of a silent exit 2nd Daedalus instance will show the following dialog:
---
=> [DDW-483, DDW-485] Fix missing launcher config error message and prevent orphan processes after app quit

cardano-sl-src.json
This new commit contains a bump of the `applicationVersion` and `lastKnownBlockVersion` for the testnet wallet.
=> [DEVOPS-1141] Bump cardano-sl to latest release/1.3.2

CHANGELOG.md, package.json, source/renderer/app/components/status/NetworkStatus.js, source/renderer/app/containers/status/NetworkStatusPage.js, source/renderer/app/stores/NetworkStatusStore.js
This PR improves blocks stalling detection logic by tracking both network and local block heights.
This way the "Network connection lost - reconnecting..." screen is **NOT** shown in case network block height is stalling while local block height is still increasing and vice versa. It will only be shown in case both block heights remain unchanged for more than 120 seconds.
---
=> [DDW-529] Blocks stalling logic improvement

cardano-sl-src.json
Updates cardano-sl to latest `release/2.0.1`.
Appveyor build passes: https://ci.appveyor.com/project/input-output/daedalus/builds/21449642
=> [DEVOPS-1203] Update cardano-sl to latest release/2.0.1

CHANGELOG.md, shell.nix, source/main/cardano/setup.js, source/main/config.js
This PR fixes the handling of the `frontendOnlyMode` variable picked up from the `launcherConfig`.
Launcher treats this variable in an opposite way than what Daedalus code expects.
From the Launcher's perspective, setting `frontendOnlyMode` to `true` means that Launcher is responsible for launching only Daedalus and then Daedalus is responsible for launching the cardano-node. If `frontendOnlyMode` is set to `false`, Launcher tries to launch both Daedalus and cardano-node.
This is unexpected from Daedalus perspective as we treat `frontendOnlyMode` set to `true` as a case where Daedalus connects to manually started instances of cardano-node for advanced debugging purposes.
In order to avoid big refactorings on both ends (Launcher and Daedalus), @cleverca22 and @nikolaglumac agreed to invert …
=> [DDW-558] Fix handling of the 'frontendOnlyMode'  variable

CHANGELOG.md, source/renderer/app/components/status/NetworkStatus.js, source/renderer/app/config/timingConfig.js, source/renderer/app/stores/NetworkStatusStore.js
This PR improves the user experience for the NTP check: When starting Daedalus there is a 30 seconds grace period for failing / not finished NTP checks before showing the big red warning screen. That improves the UX because atm the big red warning screen is for many users one of the first things they see when starting Daedalus, which is not a nice start (and unnecessary).
This PR also:
- prevents forced NTP checks while `isConnected = false` (including our forced NTP check poller)
- disables "Check time" link on the "Network Status" screen while `isConnected = false`
- triggers forced NTP check as soon as `isConnected` turns to `true` (regardless if we are connected for the first time or re-connected)
This new setup covers both of the currently broken scenarios:
1. Daedalus starts while …
=> [DDW-514] Improve NTP check UX

cardano-sl-src.json
This PR bumps the Cardano SL revision to the tip of `release/2.0.1` branch: https://github.com/input-output-hk/cardano-sl/commits/release/2.0.1
=> Bump Cardano SL revision to the tip of release/2.0.1 branch

cardano-sl-src.json
Updates cardano-sl to latest release/2.0.1.
=> [DEVOPS-1203] Bump cardano-sl to latest release/2.0.1

CHANGELOG.md, source/renderer/app/api/api.js
This PR adds more detailed logging for API errors by replacing `stringifyError` with `stringifyData` method which outputs more than just shallow objects.
---
=> [DDW-546] Add more logging for API errors

cardano-sl-src.json, installers/.gitignore, installers/Spec.hs, installers/common/AppVeyor.hs, installers/daedalus-installer.cabal, installers/shell.nix
This modifies the Windows installer builder so that it fetches `CardanoSL.zip` from Hydra rather than S3 or AppVeyor.
Set to WIP because before merging we need:
- input-output-hk/cardano-sl#4001
- input-output-hk/iohk-ops#521
- https://appveyor-ci-deploy.s3-ap-northeast-1.amazonaws.com/installers/daedalus-0.12.1-cardano-sl-2.0.0-mainnet-windows-11494.exe
- https://appveyor-ci-deploy.s3-ap-northeast-1.amazonaws.com/installers/daedalus-0.12.1-cardano-sl-2.0.0-staging-windows-11494.exe
- https://appveyor-ci-deploy.s3-ap-northeast-1.amazonaws.com/installers/daedalus-0.12.1-cardano-sl-2.0.0-testnet-windows-11494.exe
=> [DEVOPS-1208] installers: Get cross-compiled windows exes from Hydra

cardano-sl-src.json
This is just an `applicationVersion` increment for testnet. This version will only be proposed on testnet. It contains a change for the linux platform so that it checks for updates correctly.
=> [DEVOPS-1219] Bump cardano-sl to latest release/2.0.1

CHANGELOG.md, source/renderer/app/api/api.js
This PR adds support for newly introduced `UtxoNotEnoughFragmented` API error message.
---
=> [DDW-573] Update transactions API error handling

CHANGELOG.md, installers/common/WindowsInstaller.hs
(cherry picked from commit a3baf33f7b511c27133bdb275da49235bd143cd6)
This PR fixes the uninstaller translations.
---
=> [DEVOPS-1237] Character encoding issues in Windows uninstaller

installers/common/WindowsInstaller.hs
https://github.com/input-output-hk/daedalus/pull/1321 (the PR that was closed) was the one with the fix
https://github.com/input-output-hk/daedalus/pull/1322 (the PR that was merged in favor of it), was not yet updated, and lacked the fix
this new PR applies the fix to release branch
- Screenshot
---
=> [DEVOPS-1237] Fix uninstaller unicode

CHANGELOG.md, features/step_definitions/wallets-steps.js, source/renderer/app/assets/images/ada-symbol-smallest-dark.inline.svg, source/renderer/app/assets/images/ada-symbol.inline.svg, source/renderer/app/components/wallet/ada-redemption/AdaRedemptionSuccessOverlay.js, source/renderer/app/components/wallet/ada-redemption/AdaRedemptionSuccessOverlay.scss, source/renderer/app/components/wallet/summary/WalletSummary.js, source/renderer/app/components/wallet/summary/WalletSummary.scss, source/renderer/app/components/wallet/transactions/Transaction.js, source/renderer/app/components/wallet/transactions/Transaction.scss, source/renderer/app/i18n/global-messages.js, source/renderer/app/i18n/locales/defaultMessages.json, source/renderer/app/i18n/locales/en-US.json, source/renderer/app/i18n/locales/ja-JP.json, source/renderer/app/utils/formatters.js
This PR reverts part of [PR 1317](https://github.com/input-output-hk/daedalus/pull/1317), which replaced ada symbol images with unicode character.
---
=> [DDW-581] Revert ada symbol images with unicode character

installers/dhall/win64.dhall
This PR fixes the unicode issue with cardano state directory introduced by DDW-572.
- Screenshot
---
=> [RCD-56] Fix Windows unicode problem

CHANGELOG.md, source/renderer/app/Routes.js, source/renderer/app/containers/Root.js, source/renderer/app/stores/ProfileStore.js
This PR fixes the routing logic which allowed the display of "Settings" screens before the wallet data is fully loaded.
[Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1553269152256100)
A) While being on the Settings screen use "Restart node" option from the Network status screen - the Settings screen should be restored only after Daedalus has loaded wallet data.
B) Test profile actions (setting language, terms of use), Check the display of "Node is shutting down" message etc...
---
=> [DDW-613] Settings screen shown during wallet-loading phase

CHANGELOG.md, source/renderer/app/components/wallet/receive/WalletReceive.js
This PR fixes spending password being asked on Receive screen when clicking on "Copy address" link.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1557949796171100)
---
=> [DDW-643] Spending password is asked when clicking on 'Copy address' link

CHANGELOG.md, package.json, yarn.lock
This PR introduces a fix for vulnerability issue caused by `marked` package version.
Package is used as required sub-dependency for storybook addon and markdown packages with version that cause warning and is fixed to requested/recommended version.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1559732494007800)
---
=> [DDW-686] Fix vulnerability warning

CHANGELOG.md, source/renderer/app/components/status/BlockConsolidationStatus.scss
This PR fixes the Block consolidation status screen not fully shown in minimized mode when the Japanese language is selected
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1559846551080600)
---
=> [DDW-671] Block consolidation status screen is not fully shown

CHANGELOG.md, source/renderer/app/themes/daedalus/cardano.js, source/renderer/app/themes/daedalus/dark-blue.js, source/renderer/app/themes/daedalus/light-blue.js, source/renderer/app/themes/utils/createTheme.js
This PR removes files pushed without running Prettier.
---
---
=> [DDW-731] Remove non-formatted files

CHANGELOG.md, source/main/locales/en-US.json, source/main/locales/ja-JP.json, source/main/menus/MenuActions.types.js, source/main/menus/osx.js, source/main/menus/win-linux.js, source/main/utils/buildAppMenus.js
This PR removes the **No** button in the Blank Screen Fix dialog, for consistency across the OS's.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1564076056050000)
---
=> [DDW-781] Blank Screen Fix - Default Selection.

cardano-sl-src.json
This PR bumps the application version of `cardano-sl`.
---
=> [DEVOPS] RC3 cardano-sl application version bump

CHANGELOG.md, source/renderer/app/components/wallet/transactions/Transaction.js, source/renderer/app/i18n/locales/de-DE.json, source/renderer/app/i18n/locales/en-US.json, source/renderer/app/i18n/locales/hr-HR.json, source/renderer/app/i18n/locales/ja-JP.json, source/renderer/app/i18n/locales/ko-KR.json, source/renderer/app/i18n/locales/zh-CN.json
This PR fixes the small issue with message display for amount of confirmations. When there is only 1 transaction confirmation it will display "1 confirmation" instead of "1 confirmations" as it was until now.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1565610787181300)
---
=> [DDW-798] "1 confirmations" is displayed on Transaction Assurance Level

CHANGELOG.md, features/tests/e2e/documents/dummy-news.json, package.json
This PR bumps Daedalus version to `0.15.0` and updates the CHANGELOG:
- Implemented "Newsfeed" feature ([PR 1570](https://github.com/input-output-hk/daedalus/pull/1570))
- Implemented "Wallet recovery phrase verification" feature ([PR 1565](https://github.com/input-output-hk/daedalus/pull/1565))
- Implemented new "Automated update" notification design ([PR 1491](https://github.com/input-output-hk/daedalus/pull/1491))
- Improved "Wallets" list scrollbar UX ([PR 1475](https://github.com/input-output-hk/daedalus/pull/1475))
- Removed "Ada Redemption" feature ([PR 1510](https://github.com/input-output-hk/daedalus/pull/1510))
- Updated behavior of system dialogs ([PR 1494](https://github.com/input-output-hk/daedalus/pull/1494))
- Fixed the "Numeric input" component caret positioning issues …
=> [DDW-912] Bump Daedalus version

CHANGELOG.md, source/renderer/app/components/sidebar/Sidebar.js, source/renderer/app/containers/MainLayout.js, storybook/stories/Sidebar.stories.js, storybook/stories/support/StoryLayout.js
This PR removes the create paper wallet certificate feature from the sidemenu for Incentivized testnet.
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1572964424326100)
---
=> [DDW-997] Disable create a paper wallet certificate feature

source/main/cardano/CardanoWalletLauncher.js
Selfnode is identified by the unique `genesis-block` walletArg. Other cluster modes us `genesis-block-hash`, so this should be relatively reliable
=> Only create block0.bin when running in selfnode mode

CHANGELOG.md, source/renderer/app/themes/daedalus/cardano.js, source/renderer/app/themes/daedalus/dark-blue.js, source/renderer/app/themes/daedalus/dark-cardano.js, source/renderer/app/themes/daedalus/light-blue.js, source/renderer/app/themes/daedalus/white.js, source/renderer/app/themes/daedalus/yellow.js, source/renderer/app/themes/utils/createTheme.js
This PR fixes the red button disabled state color across the themes.
---
---
=> [DDW-970] Fix disabled red button color

CHANGELOG.md, source/renderer/app/containers/staking/dialogs/UndelegateDialogContainer.js
This PR introduces a fix for undelegation issue.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1576255522003600)
---
=> [DDW-1137] Fix undelegation issue

CHANGELOG.md, nix/sources.json
This PR updates `cardano-wallet` dependency to v2019-12-23 (`398565cc1a65553827834520c5a95827a7c48d41`) with a fix for Windows migration issue.
=> [DDW-1162] 2.0.1-INT1 preparation - Windows fix

CHANGELOG.md, source/renderer/app/stores/WalletsStore.js
This PR fixes a routing issue when deleting a Yoroi Balance/Rewards wallets restored from the same recovery phrase.
---
---
=> [DDW-1182] Fix routing issues when deleting wallets

CHANGELOG.md, default.nix, nix/jormungandr-bridge.nix, nix/sources.json
This PR bumps `cardano-wallet` revision to the one which includes a fix for pending delegation issue.
---
- [ ] Run general regression tests
---
=> [DDW-1210] Error is shown trying to delegate to the same wallet

CHANGELOG.md, source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.js, source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
This PR fixes the wrong rank background color within the stake pool tooltip.
Before this fix the number of stake pools was not taken into account when generating the background for the rank within the tooltip, unlike for the one on the stake pool tile/thumbnail.
---
---
=> [DDW-1232] Fix stake pool rank color within the stake pool tooltip

CHANGELOG.md, source/renderer/app/api/api.js, source/renderer/app/api/network/requests/getNetworkParameters.js, source/renderer/app/api/network/types.js, source/renderer/app/api/utils/patchAdaApi.js
This PR integrated network parameters api endpoint.
[Jira Ticket](https://jira.iohk.io/browse/DDW-80)
=> [DDW-80] Integrate network parameters api endpoint

CHANGELOG.md, source/renderer/app/api/api.js, source/renderer/app/stores/WalletsStore.js
This PR implements generation of an Byron wallet address after creating a Byron wallet
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1585842011289400)
---
=> [DDW-100] Generate an address after creating a Byron wallet

CHANGELOG.md, source/renderer/app/components/wallet/settings/WalletSettings.js
This PR disable "Force resync" feature for Byron wallets
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1585876823293200)
---
=> [DDW-101] - Disable "Force resync" feature for Byron builds

CHANGELOG.md, source/common/ipc/api.js, source/main/cardano/setup.js, source/main/index.js, source/main/ipc/getDesktopDirectoryPathChannel.js, source/renderer/app/actions/wallet-migration-actions.js, source/renderer/app/components/wallet/WalletAdd.js, source/renderer/app/components/wallet/layouts/WalletWithNavigation.scss, source/renderer/app/components/wallet/settings/WalletSettings.js, source/renderer/app/components/wallet/settings/WalletSettings.scss, source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.js, source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.scss, source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.scss, source/renderer/app/components/widgets/forms/InlineEditingInput.js, source/renderer/app/components/widgets/forms/InlineEditingInput.scss, source/renderer/app/containers/staking/StakingRewardsPage.js, source/renderer/app/containers/wallet/WalletReceivePage.js, source/renderer/app/containers/wallet/dialogs/WalletImportDialogContainer.js, source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/InstructionsDialogContainer.js, source/renderer/app/containers/wallet/dialogs/settings/ExportWalletToFileDialogContainer.js, source/renderer/app/i18n/locales/defaultMessages.json, source/renderer/app/i18n/locales/en-US.json, source/renderer/app/i18n/locales/ja-JP.json, source/renderer/app/ipc/getDesktopDirectoryPathChannel.js, source/renderer/app/stores/AppStore.js, source/renderer/app/stores/ProfileStore.js, source/renderer/app/stores/WalletMigrationStore.js, storybook/stories/wallets/import/WalletImportFile.stories.js
This PR fixes:
- Restores "learn more" link on the first "Wallet import" dialog
- Updates open/save dialogs to use "Desktop" as default path for opening/saving files
- Resets "Wallet import" dialog values on open
- Fixes wallet rename success message flashing on "Wallet settings" screen
- Fixes wallet screens scrollbar issue when active restoration notification is shown
- Fixes "Wallet import" exception dialog locale
---
---
=> [DDW-162, DDW-163] Fix 'Wallet import' UI/UX issues

CHANGELOG.md, package.json
This PR bumps Daedalus version to `1.2.0-FC1`.
=> Bumps Daedalus version to 1.2.0-FC1

CHANGELOG.md, source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.js, source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.scss, source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
This PR hides stake pool saturation info on the Stake pool Thumbnail and Stake pool tooltip elements.
---
---
=> Hide stake pool saturation info

CHANGELOG.md, source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsSuccessDialog.js, source/renderer/app/i18n/locales/en-US.json
This PR fixes double punctuation error on delegation dialog.
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1595277241270100)
---
=> [DDW-302] Double punctuation on delegation dialog

CHANGELOG.md, source/renderer/app/components/staking/widgets/TooltipPool.js, source/renderer/app/i18n/locales/defaultMessages.json, source/renderer/app/i18n/locales/en-US.json, source/renderer/app/i18n/locales/ja-JP.json
This PR updates stake pool tooltip to display 'Produced blocks' instead of 'Blocks (current epoch)'.
---
---
=> [DDW-318] Revert "Blocks (current epoch)" into "Blocks produced"

CHANGELOG.md, source/renderer/app/api/api.js
This PR reverses ordering of addresses on the 'Receive' screen so that the oldest ones are shown on the top and the newest one on the bottom of the list.
---
---
=> [DDW-339] Correct order of receiving addresses

CHANGELOG.md, source/renderer/app/components/staking/stake-pools/StakePools.js, source/renderer/app/components/staking/stake-pools/StakePools.scss, source/renderer/app/components/staking/stake-pools/StakePoolsList.js, source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js, source/renderer/app/components/staking/stake-pools/StakePoolsSearch.js, source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss, source/renderer/app/components/staking/stake-pools/StakePoolsTable.js, source/renderer/app/components/staking/stake-pools/StakePoolsTable.scss, source/renderer/app/components/staking/stake-pools/StakePoolsTableBody.js, source/renderer/app/components/staking/widgets/TooltipPool.js, source/renderer/app/components/staking/widgets/TooltipPool.scss, source/renderer/app/components/widgets/BackToTopButton.js, source/renderer/app/components/widgets/BackToTopButton.scss, source/renderer/app/i18n/locales/defaultMessages.json, source/renderer/app/themes/daedalus/cardano.js, source/renderer/app/themes/daedalus/dark-blue.js, source/renderer/app/themes/daedalus/dark-cardano.js, source/renderer/app/themes/daedalus/flight-candidate.js, source/renderer/app/themes/daedalus/incentivized-testnet.js, source/renderer/app/themes/daedalus/light-blue.js, source/renderer/app/themes/daedalus/shelley-testnet.js, source/renderer/app/themes/daedalus/white.js, source/renderer/app/themes/daedalus/yellow.js, source/renderer/app/utils/formatters.js, storybook/stories/staking/StakePoolsTable.stories.js
This PR fixes various UI/UX issues on the "Stake pools" screen:
- "Table view" header rendering over stake pool tooltip for stake pools in "Stake pools you are delegating to" section 
- Ranking shown for stake pools without nonmyopic member rewards data (should be "-") 
- "Back to top" button shown over the column explanation tooltips in the "Table view" header
- Stake pool slider not showing values in selected number formatting 
- "Produced blocks" value in stake pool tooltip and in the "Table view" displayed in "short" number format (should be the full number)
---
---
=> Fix "Stake pools" screen UI/UX issues

CHANGELOG.md, package.json, source/renderer/app/components/loading/syncing-connecting/StatusIcons.js, source/renderer/app/themes/daedalus/cardano.js, source/renderer/app/themes/daedalus/dark-blue.js, source/renderer/app/themes/daedalus/dark-cardano.js, source/renderer/app/themes/daedalus/flight-candidate.js, source/renderer/app/themes/daedalus/incentivized-testnet.js, source/renderer/app/themes/daedalus/light-blue.js, source/renderer/app/themes/daedalus/shelley-testnet.js, source/renderer/app/themes/daedalus/white.js, source/renderer/app/themes/daedalus/yellow.js, yarn.lock
This PR fixes the pop over themes after a detailed double-check from @a-rukin:
- Update to react-polymorph@0.9.6-rc3 (which sets the default pop over font to `regular`)
- Fix wrong background colors for some themes
- Handle the potentially (atm only in cardano theme) different bg color for the status icon tooltip
The cardano theme is "special" because it requires a different tooltip bg color for the status icons:
But the default tooltips should all look like this:
---
This PR is really mostly fixing tooltips styles for the work done in [[DDW-291] Smart Tooltip MVP integration](https://github.com/input-output-hk/daedalus/pull/2210), so i don't think a whole QA session is needed here but @a-rukin should take a final look and give approval (because the other PR was merged before he could do …
=> [DDW-291] Fix PopOver Themes

CHANGELOG.md, source/renderer/app/components/staking/stake-pools/StakePoolsTable.js, source/renderer/app/components/staking/stake-pools/StakePoolsTable.scss, source/renderer/app/components/staking/stake-pools/StakePoolsTableBody.js, source/renderer/app/components/staking/widgets/ThumbPoolContent.js, source/renderer/app/components/staking/widgets/ThumbPoolContent.scss, source/renderer/app/components/staking/widgets/ThumbSelectedPool.js, source/renderer/app/components/staking/widgets/TooltipPool.js, source/renderer/app/components/staking/widgets/TooltipPool.scss, source/renderer/app/i18n/locales/defaultMessages.json, source/renderer/app/i18n/locales/en-US.json, source/renderer/app/i18n/locales/ja-JP.json
This PR updates stake pool ranking logic to display the same rank for all stake pools without potential rewards.
Specification:
- Design: https://zpl.io/2p5dz9l
- Requirements: https://docs.google.com/document/d/1jgoaZ_CUXh6z66Eb7K7cXwhN-yw6Iv1fu0fgDVGwcpM/edit#heading=h.mq51cxvzrjz (last page)
- Text copy:
English:
> *Stake pools with the potential rewards estimated at zero have the same ranking. Please set the stake slider to a higher value for more pools to get potential rewards estimated at more than zero.
Japanese:
> *見込み報酬額の見積もりがゼロのステークプールはランキングが同じになります。見込み報酬額がゼロより大きなプールを増やすには、ステークスライダーをより高額に設定してください。
---
---
=> [DDW-432] Stake pool ranking logic update

CHANGELOG.md, source/main/config.js, source/main/utils/handleDiskSpace.js
The Linux installer runs Daedalus inside a chroot, which lives in a temporary directory.
Some - perhaps most - Linux distros have the temporary directory as a tmpfs (RAM drive).
So when Daedalus checks the free space in /, it is reporting the amount of free space on the tmpfs - typically only a few GB.
This change makes Daedalus check the free space for the state directory.
In any case, this is a good thing to do, because the state directory (in the user's home directory) may be on a different partition to /.
I haven't done any testing on this.
=> Fix empty disk space calculation for some Linux distributions

CHANGELOG.md, source/renderer/app/api/api.js, source/renderer/app/api/staking/types.js
This PR removes SMASH-delisted stake pools.
---
---
=> [DDW-509] Remove delisted pools

CHANGELOG.md, nix/cardano-bridge.nix, yarn2nix.nix
This PR reduces Linux installers by about 100MB.
---
[Test Document](https://docs.google.com/spreadsheets/d/1AD5FdI9UvUzp_RXiMjQjr6tKT2Nt5j9Ywf53lFGzySc/edit#gid=156185649)
---
=> [DEVOPS] Reduce the size of Linux installers

CHANGELOG.md, gulpfile.js, source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js, source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.scss, source/renderer/app/components/staking/stake-pools/helpers.js, source/renderer/app/i18n/locales/defaultMessages.json, source/renderer/app/i18n/locales/en-US.json, source/renderer/app/i18n/locales/ja-JP.json
This PR updated "Confirmation" step of the "Delegation" wizard to show stake pool ID.
[Jira Ticket](https://jira.iohk.io/browse/DDW-503)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1608199573054900)
**Scenario 1: Pool id is displayed at last delegation step**
Given I have a wallet
And the wallet contains at least the minimum ada required for delegation
And I am on Stake Pool -> Delegation Center
And I have selected (delegate|redelegate) button
And in 'DELEGATE WALLET' dialog I have selected 'Continue'
And in Step 1 of 3 - DELEGATE WALLET I have selected 'Continue'
And in Step 2 of 3 - CHOOSE A STAKE POOL I have selected a pool
When in Step 2 of 3 - CHOOSE A STAKE POOL I select Continue'
Then dialog Step 3 of 3 - CONFIRM DELEGATION is displayed
And pool id is …
=> [DDW-503] Show stake pool ID on the "Confirmation" step of the "Delegation" wizard

CHANGELOG.md, installers/overlays/required.nix, nix/sources.json
This PR fixes Daedalus development environment issues on OSX Big Sur. In order to fix the problem, `iohk-nix` had to be updated to use `nixpkgs` from the latest `nixos-unstable` branch as this one enables it to run on OSX Big Sur which has a new way of handling `dylib` cache.
---
---
The regression testing would be tracked on [this document](https://docs.google.com/spreadsheets/d/1dl1PhucTBI4C2BtzhF991D5v8BsMUAz_frOdGVUQWYw/edit#gid=0).
---
=> [DDW-531] Fix Daedalus development environment issues on OSX Big Sur

CHANGELOG.md, installers/common/MacInstaller.hs, package.json, source/renderer/app/api/api.js, source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js, source/renderer/app/components/staking/redeem-itn-rewards/Step2ConfirmationDialog.js, source/renderer/app/components/wallet/WalletSendForm.js, source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js, source/renderer/app/stores/StakingStore.js, source/renderer/app/utils/formatters.js, source/renderer/app/utils/transaction.js, source/renderer/app/utils/walletsForStakePoolsRanking.js, tests/transactions/e2e/steps/transactions.js, tests/wallets/e2e/steps/transfer-funds-wizard.js, yarn.lock, yarn2nix.nix
This PR updates the dependency `bignumber.js` from version 5 to 9 and fixes all breaking API changes summarized here: https://github.com/MikeMcl/bignumber.js/blob/master/CHANGELOG.md
**Note**: there should not be any changes in the UX / UI anywhere.
This is a preparation PR for **DDW-543 Support Any Number in Numeric Input** since it makes sense to test this in advance.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1610983003020200)
```Gherkin
Scenario 1: Transaction is the same as current production build
Given I have a fully synced <wallet_type> wallet
And the wallet has enough ada for transaction
When I send ada to another wallet
Then the transaction is correct
And the displayed transaction is the same as shown by current production build with the same …
```
=> [DDW-543] Update bignumber.js from v5 to v9

CHANGELOG.md, source/renderer/app/components/staking/rewards/StakingRewards.js, source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.js, source/renderer/app/i18n/locales/defaultMessages.json, source/renderer/app/utils/sortComparators.js
This PR adjusted sorting of table on rewards screen
[Jira Ticket](https://jira.iohk.io/browse/DDW-551)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1612300182137000)
```Gherkin
Scenario 1: Sort reward
Given I am on Staking -> Rewards screen
And there are at least 2 or more wallets displayed
And at least 2 wallets have different rewards amount
When I sort the rewards in (ascending|descending) order
Then they are sorted correctly
```
=> [DDW-551] Adjust sorting on rewards screen

CHANGELOG.md, source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js, source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.scss
This PR fixes the misalignment of the "i" icon on the "Set password" dialog.
---
---
**Scenario 1 - Check "i" icon on "Set password" dialog**
```Gherkin
Given that I am on the "Set password" dialog
When I validate the "i" icon 
Then I can see it is displayed next to "Spending password"
And it does not overlaps the text
```
**Scenario 2 - Hover "i" icon on "Set password" dialog**
```Gherkin
Given that I am on the "Set password" dialog
When I hover the "i" icon 
Then a tooltip with information about password managing is displayed over the icon
```
---
=> [DDW-528] Spacing issues with "i" icon on "Set password" dialog

CHANGELOG.md, README.md, default.nix, nix/sources.json, package.json, shell.nix, source/main/cardano/CardanoWalletLauncher.js, source/main/config.js, source/main/webpack.config.js, utils/cardano/native-tokens/registry.json, yarn.lock
This PR updates `cardano-wallet` to the latest release: https://github.com/input-output-hk/cardano-wallet/releases/tag/v2021-02-15.
It also updates `cardano-launcher` to the latest release "0.20210215.0" which includes support for passing the token metadata server argument to `cardano-wallet`.
Daedalus, by default, uses the following metadata server for all networks except for the mainnet: `https://metadata.cardano-testnet.iohkdev.io/`.
It's also possible to use a mock server locally by running the following command in `nix-shell` prior to starting Daedalus:
```
$ mock-token-metadata-server ./utils/cardano/native-tokens/registry.json
Mock metadata server running with url http://localhost:65432/
```
Then proceed to launch Daedalus and make sure to provide the mock token metadata server …
=> [DDW-574] Update cardano-wallet and cardano-launcher

CHANGELOG.md, source/renderer/app/components/staking/delegation-center/WalletRow.js, source/renderer/app/i18n/locales/defaultMessages.json
This PR fixed delegated stake pool status on Delegation Center screen
[Jira Ticket](https://jira.iohk.io/browse/DDW-579)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1614262917027700)
```Gherkin
Scenario 1: Wallet undelegated on Yoroi shown as delegated on Daedalus
Given I have undelegated a wallet on Yoroi
When I go to Daedalus Delegation Center
Then this wallet will be shown as undelegated
```
Scenario: Wallet undelegated
=> [DDW-579] Undelegated wallet shown as delegated on "Delegation center" screen

CHANGELOG.md, nix/sources.json, source/common/types/hardware-wallets.types.js, source/main/ipc/getHardwareWalletChannel.js, source/renderer/app/api/api.js, source/renderer/app/api/transactions/requests/selectCoins.js, source/renderer/app/api/transactions/types.js, source/renderer/app/stores/HardwareWalletsStore.js, source/renderer/app/utils/shelleyLedger.js, source/renderer/app/utils/shelleyTrezor.js
This PR introduces extended transaction signing / sending data with withdrawals with Hardware Wallets. Now we can use rewards along with Hardware wallets!
---
**NOTE: DO NOT MERGE**
- WBE bumped to the latest master where coin selection with withdrawals is included. We need to check this before merging @nikolaglumac  (REV: `b6810e8401b04b1d8a1a142f0b06b47cd6b51186`)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1614274478028600)
**Withdrawals Example:**
- You have a wallet "Wallet Test"
- Wallet balance is 50 ADA (shown in sidebar)
- You earned 2 ADA as rewards
- This means that you have `walletBalance = 50`, `availableWalletBalance = 48`, `rewards = 2`
- Try to send `49 ADA` - this means that you want to send your `full wallet available balance without …
=> [DDW-584] Apply withdrawals to Hardware Wallets

CHANGELOG.md, source/renderer/app/components/settings/categories/StakePoolsSettings.js
This PR Fixes the SMASH server type dropdown not appearing in the Stake Pools Settings screen when syncing.
**Incorrect**
**Correct**
---
```Gherkin
Scenario 1: Dropdown visible when app syncing
Given I am on Stake Pools settings screen
And the app is still syncing
When I observe the Smash server type dropdown
Then the dropdown is visible
And the syncing animation is presence on it
And it is disabled
```
---
=> [DDW-601] Fix dropdown not appearing in the Stake Pools Settings screen

CHANGELOG.md, package.json, yarn.lock
This PR introduces `trezor-connect` dependency update to the version `8.1.25`.
This version should include a fix for Trezor Passphrase handling mentioned in https://github.com/trezor/connect/issues/783
---
**Dedicated QA:** @ManusMcCole 
---
=> [DDW-624] Update trezor-connect dependency to version 8.1.25

source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
This PR introduces a fix for delegation issue when the wallet is not selected at first.
---
---
=> Fix delegation issue while wallet not selected at first

CHANGELOG.md, package.json, source/renderer/app/components/staking/stake-pools/StakePoolsList.js, source/renderer/app/components/staking/stake-pools/StakePoolsList.scss
This PR fixes an issue with stake pools list rendering where items get cut-off (hidden) on specific window sizes.
- Reverted to Math.floor picking of row items (to prevent overflows that caused this issue)
- Changed the way the row items are spaced (flexbox + space-between)
- Added filler items in rows that are not "complete" to ensure all rows are spaced the same way
---
---
**Scenario 1: Order of stake pools’ ranking**
```gherkin
Given I am at Staking -> Stake pools
And the stake pools are fully loaded
When I observe the stake pools’ ranking
Then they are in numerical order
And the increase in ranking from one pool to the next pool is +1
And they are ordered in ascending order
```
**Scenario 2: Order of stake …
=> [DDW-648] Fix stake pools list cutting off items

CHANGELOG.md, source/renderer/app/api/utils/localStorage.js, source/renderer/app/config/currencyConfig.js, source/renderer/app/stores/WalletsStore.js, source/renderer/app/types/currencyTypes.js
This PR fixes blank currency selection after updating to 4.0.5
**Old localStorage currency format**
```json
"staging-CURRENCY-SELECTED": {
"symbol": "brl",
"decimalDigits": 2,
"name": "Brazilian Real",
"symbolNative": ""
}
```
**New localStorage currency format**
```json
"staging-CURRENCY-SELECTED": "brl"
```
**Daedalus builds**
1. Run a Daedalus version older than 4.0.5 and set a currency different than USD;
2. Run Daedalus 4.0.5 version: the currency should be broken as described at the [Jira card](https://jira.iohk.io/browse/DDW-657);
3. Run this PR's build: the currency feature should be working normally.
**Running Daedalus locally**
1. Set the `CURRENCY-SELECTED` value at `config.json` to:
```json
"[ENVIRONMENT]-CURRENCY-SELECTED": {
"symbol": "brl",
"decimalDigits": 2,
"name": …
```
=> [DDW-657] Fix blank currency selection after updating to 4.0.5

CHANGELOG.md, source/renderer/app/components/staking/widgets/TooltipPool.scss
This PR fixes the scrollbar for stake pools pop-over descriptions which had several issues.
- The scrollbar didn't "start the top" but was positioned somewhere in the middle of the description text.
- Even if you scrolled down to the "bottom" of the text the bar was far away from the bottom of the description box.
- The scrollbar thumb was quite small
The original issue (vertical thumb position offset, reported by @miorsufianiohk) was caused by our global scrollbar styles which use scrollbar `border` to position the thin thumb within a bigger track (which might be the only way to achieve this if you want the track have some specific bg color). Since that's not required in the case of the stake pool description field (it only needs to show a thin scrollbar on the right side) this was …
=> [DDW-684] Fix stake pools pop over description scrollbar

CHANGELOG.md, source/renderer/app/components/wallet/receive/WalletReceiveDialog.js
This PR fixes issue with note field on Share Wallet Address dialog for software wallets.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1622716415102500?thread_ts=1622662562.098700&cid=GGKFXSKC6)
---
**Scenario 1 - Check notes are visible for software wallet**
```gherkin
Given that I have a software wallet
And I am on the "Share wallet address" dialog on this wallet
When I check the dialog
Then I can see that the input to insert notes in the PDF is visible
And the information inserted there is visible when I export a PDF
```
**Scenario 2 - Check notes are visible for hardware wallet**
```gherkin
Given that I have a hardware wallet
And I am on the "Share wallet address" dialog on this wallet
And I have confirmed the address with the device
When I check the …
```
=> [DDW-698] Can't insert notes on "Share Wallet Address" dialog for software wallets

CHANGELOG.md, source/renderer/app/utils/hardwareWalletUtils.js, source/renderer/app/utils/shelleyLedger.js, source/renderer/app/utils/shelleyTrezor.js
This PR introduces a fix for the Trezor transaction native tokens grouping issue.
---
Dedicated QA: @ManusMcCole 
**_Note:_** _This should be tested only with Trezor devices_
- 1 SadCoin (policy Id: 789ef8ae89617f34c07f7f6a12e4d65146f958c0bc15a97b4ff169f1)
- 1 TrueCoin (policy Id: 789ef8ae89617f34c07f7f6a12e4d65146f958c0bc15a97b4ff169f1)
- 2 TestCoin (policy Id: 6b8d07d69639e9413dd637a1a815a7323c69c86abbafb66dbfdb1aa7)
- 2 SomeCoin (policy Id: 2e6d83507419c027eac6eb9430b780c0793e2c1762b7bff56fbba6f5)
As you can see `SadCoin` and `TrueCoin`have the same Policy ID.
---
```gherkin
Scenario 1 - Send ADA
Given that I have a Wallet fully loaded in Daedalus
When I send a transaction containing only ADA
Then it is …
```
=> [DDW-699] Fix Trezor transaction native tokens grouping issue

CHANGELOG.md, source/renderer/app/components/staking/_stakingConfig.scss
Fixed font used in delegation center staking unavailable while syncing message
- Screenshot
---
---
=> [DDW-744] Adjust font for Delegation Center info message

CHANGELOG.md, source/renderer/app/components/wallet/transactions/Transaction.js
This PR immediately localizes transaction timestamps when settings language is changed
https://user-images.githubusercontent.com/7581002/136828566-480ebd60-82f8-4b18-a605-888c4dd05445.mov
---
**Scenario 1 - Validate transactions after switching to Japanese**
```gherkin
Given that Daedalus is synced
And it has a synced wallet with transaction history
And the selected language is English
And the time format is 12 hs with AM/PM indicators
When I switch the language to Japanese
And I check the timestamp of a transaction without reloading Daedalus
Then I can see that the corresponding "AM/PM" translations are displayed next to the time
```
**Scenario 2 - Validate transactions after switching to English**
```gherkin …
```
=> [DDW-747] Fix transaction localization

CHANGELOG.md, source/renderer/app/containers/wallet/dialogs/wallet-restore/StepConfigurationContainer.js, source/renderer/app/containers/wallet/dialogs/wallet-restore/StepSuccessContainer.js, source/renderer/app/stores/WalletsStore.js
This PR fixes 2 issues in restoring wallets.
- Continue button could be pressed multiple times
- Wallet restore dialog state not reset correctly
---
---
=> Fix wallet restore dialog and continue disable check

CHANGELOG.md, source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js, source/renderer/app/components/widgets/Slider.js
This PR checks whether the slider has moved, before executing the onAfterChange function.
---
---
=> [DDW-683] Prevent stake pools list reloading when slide didn't change position

nix/cardano-bridge.nix
This fixes:
```
yarn run nix:testnet
yarn dev
```
on M1 Macs
=> Used `codesign --force -s -` to sign executables in cardano-bridge

CHANGELOG.md, source/renderer/app/stores/NetworkStatusStore.ts
This PR adds a disk space check after the disk space channel listener is setup. The problem was the initial disk space check would happen before the listener was setup and there was a race condition.
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1643733959707049)
---
=> [DDW-934] Available disk space takes a long time to show

CHANGELOG.md, source/renderer/app/components/staking/stake-pools/StakePoolsRankingLoader.scss
This PR intends to fix a bug where we have the tooltip for discrete mode being partially covered by the loading screen overlay we get when adjusting stake pools.
| ------------- | Before  | After |
| ------------- | ------------- | ------------- |
| EN | <img width="1791" alt="Screenshot 2022-03-04 at 14 21 31" src="https://user-images.githubusercontent.com/27725122/156780974-56dca32a-bc7a-4190-87d9-1cd302fd895e.png"> | <img width="1792" alt="Screenshot 2022-03-01 at 14 48 36" src="https://user-images.githubusercontent.com/27725122/156190920-c12c1222-74d8-4817-b5c4-5a07bd823367.png">  |
| JP | <img width="1783" alt="Screenshot 2022-03-04 at 14 21 03" src="https://user-images.githubusercontent.com/27725122/156781227-7f62040f-d418-4e5b-bcb6-26c39aa1eeea.png"> | <img width="1333" …
=> [DDW-936] Fixes discreet tooltip appearing behind loading overlay

CHANGELOG.md, source/renderer/app/components/assets/Asset.scss, source/renderer/app/components/assets/Asset.spec.tsx, source/renderer/app/components/assets/Asset.tsx, source/renderer/app/components/wallet/tokens/wallet-token/WalletTokenHeader.scss, storybook/stories/wallets/tokens/WalletTokens.stories.tsx
This PR adds ASCII name on token display when there is no metadata name.
Before
After
```Gherkin
Scenario 1: ASCII name displayed when token has no metadata name
Given I have a token without metadata name
When I observe the token's metadata name's field
Then this field is populated with ASCII name
Scenario 2: Metadata name displayed when token has metadata name
Given I have a token with metadata name
When I observe the token's metadata name's field
Then this field is populated with metadata name
```
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1646329620217049)
---
=> [DDW-942] Design ASCII display for when a token doesn't have a name

default.nix
*Internal*
Basically what the title says:
* We didn’t wait for a merge from `develop`→https://github.com/input-output-hk/daedalus/pull/2971 to finish
* That failed, and broke `develop`.
This is a fix.
=> [DDW-1081] Fix `develop` after premature merge of `selfnode` installers

shell.nix
_Internal._
_No QA required._
@renanvalentin found out `nix-shell` → `yarn dev` no longer works, failing with broken symlinks.
I’m not sure yet why `Release`/`Debug` get switched over…
* [Slack thread](https://input-output-rnd.slack.com/archives/C02DTDJFW2Z/p1654171067947249)
=> Fix `nix-shell` on Darwin

CHANGELOG.md, default.nix, nix/sources.json, source/main/environment.ts
… which also includes `cardano-ledger` update.
Internal PR, this time targeting `develop`.
Cherry picked from release 4.12.0 – PR https://github.com/input-output-hk/daedalus/pull/3013
=> Update `cardano-node` to 1.35.1 via `cardano-wallet` PR `.patch`

CHANGELOG.md, default.nix, installers/common/Types.hs
*Internal PR*
Having the same name for both Intel and Silicon macOS is problematic during release. Also, it’s possible we’ll have `aarch64-linux` in the future.
/cc @danielmain
=> Add OS+architecture tuple to installer file names

CHANGELOG.md, nix/darwin-launcher.go
This PR requires a very basic QA run – the only thing that changes is how Daedalus is started on macOS (both Intel, and M1)
* Without this change, WebDriverIO claims that the Chromium process died – request from @marcin-mazurek and @ManusMcCole 
* And also, now Daedalus stdout/stderr is not being swallowed (and instead, written to the terminal / Console.app) – allowing easier debugging of production installations on macOS
n/a
n/a
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1658933511825369)
---
=> [DDW-1122] Fix `darwin-launcher.go` to replace its process image with `cardano-launcher` (binary), and not swallow `stdout`

CHANGELOG.md, source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.tsx, source/renderer/app/components/widgets/DialogFullSizeOverride.scss
This PR fixes translations for MnemonicInput and CSS styles at ITN rewards dialog.
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1661865559664719)
---
=> [DDW-1130] Fix blank screen when opening ITN rewards

.buildkite/pipeline.yml
This PR adds a temporary requirement to trigger macOS workers in Buildkite manually. Wait times recently have been too long, when building each commit.
*n/a*
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1672765837442719)
---
=> [DDW-1180] Trigger Darwin builds manually

installers/common/Types.hs, nix/any-darwin.nix, nix/x86_64-linux.nix, source/main/environment.ts
Internal PR, I think it's so trivial that it doesn’t require QA
It's important because of analytics – we were getting incorrect entries – the same version but with a different build counter being reported separately
=> [DDW-1224] Remove `process.env.BUILD_COUNTER` from `environment.version`

nix/internal/launcher-config.nix
This is a minimal PR to move some hotfix code from the postponed 5.4.0 release to `develop`.
=> Add `smashUrl` back after switching to configs from `cardano-playground`

CHANGELOG.md, package.json
This PR merges back the `main` branch after the 5.3.1 release into `develop`.
=> Merge main (5.3.1) into develop

CHANGELOG.md, package.json
This post-release maintenance PR merges `main` back into `develop`.
=> Merge main into develop

CHANGELOG.md, nix/internal/x86_64-linux.nix
Otherwise, it sometimes causes problems, e.g. with OpenGL, as [found](https://input-output-rnd.slack.com/archives/C7PJ29FME/p1724180523046699?thread_ts=1724177213.102339&cid=C7PJ29FME) by @johnalotoski.
_n/a_
_n/a_
---
=> [LW-10649] Unset `LD_LIBRARY_PATH` on Linux

README.md
Update readme to include info to restart nix-daemon to benefit from the cache set in the `nix.conf`
=> docs: update readme to include info to restart nix-daemon

source/renderer/app/api/api.ts, source/renderer/app/api/transactions/types.ts, source/renderer/app/components/voting/voting-governance/VotingPowerDelegation.tsx, source/renderer/app/components/voting/voting-governance/VotingPowerDelegationConfirmationDialog.tsx, source/renderer/app/stores/HardwareWalletsStore.ts, source/renderer/app/stores/VotingStore.ts, source/renderer/app/utils/dataSerialization.ts, source/renderer/app/utils/hardwareWalletUtils.ts, source/renderer/app/utils/shelleyLedger.ts, source/renderer/app/utils/shelleyTrezor.ts
This PR adds support for ledger devices. Trezor is on the way.
=> feat: add HW support for VP delegation

source/renderer/app/api/api.ts, source/renderer/app/i18n/locales/en-US.json, source/renderer/app/i18n/locales/ja-JP.json
This PR fixes some issues specified in https://input-output.atlassian.net/browse/LW-11916
=> fix: blocked staking rewards error scenario [LW-11916]

source/renderer/app/api/api.ts, source/renderer/app/stores/VotingStore.ts
https://input-output.atlassian.net/browse/LW-11920
=> fix: [LW 11920] fix VP delegation when delegating to SP

source/renderer/app/components/voting/VotingUnavailable.scss, source/renderer/app/components/voting/voting-governance/VotingPowerDelegation.tsx, source/renderer/app/components/widgets/forms/WalletsDropdown.tsx, source/renderer/app/containers/voting/VotingGovernancePage.tsx
This PR disables governance voting while cardano-node is not fully synced and disables syncing wallets in the wallet dropdown as specified in https://input-output.atlassian.net/browse/LW-11919
=> fix: disable governance voting for unsynced node and wallets [LW-11919]

source/renderer/app/utils/transactionsCsvGenerator.ts
CWB does not expose data for some assets. If we miss metadata and fingerprint, we are going to skip that data and render
`103 (unknown fingerprint)`
instead of 
`103 tHOSKY (asset15qks69wv4vk7clnhp4lq7x0rpk6vs0s6exw0ry)`
=> fix: skip missing asset data

source/renderer/app/api/api.ts
Handle blocked staking rewards api error when sending funds, for hardware wallets https://input-output.atlassian.net/browse/LW-11931
=> fix: handle blocked staking rewards error for hardware wallets [LW-11931]

CHANGELOG.md, nix/internal/cardano-bridge.nix, nix/internal/cardano-wallet--expose-musl64Packages.patch, nix/internal/common.nix, package.json
[LW-11965](https://input-output.atlassian.net/browse/LW-11965)
This PR compiles `cardano-wallet` statically.
n/a
n/a
n/a
[LW-11965]: https://input-output.atlassian.net/browse/LW-11965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LW-11965] Fix crashing of Daedalus 7.0.0 on Ubuntu

CHANGELOG.md, source/renderer/app/stores/VotingStore.ts
Workaround for https://github.com/cardano-foundation/cardano-wallet/issues/4872
https://input-output.atlassian.net/browse/LW-11980
The constructTransaction endpoint of CWB seems to fail on vote delegation for some of mnemonic wallets. We can mitigate the problem by using a pool delegation endpoint, as we do for hardware wallets.
The PR targeted to release/7.0.1 temporarily until we have a next release branch.
=> feat: use pool delegation endpoint for constructing drep tx no matter the wallet type

source/renderer/app/api/api.ts
Use the error log level for a failure in `delegateVotes` API call.
=> fix: log level of delegateVotes CWB API call

CHANGELOG.md, package.json, source/renderer/app/api/api.ts, source/renderer/app/stores/VotingStore.ts
=> Release 7.0.2

CHANGELOG.md, flake.lock, flake.nix, nix/internal/source-lib.nix
[LW-12084](https://input-output.atlassian.net/browse/LW-12084)
This PR updates `cardano-wallet` to v2025-01-09.
And `cardano-node` to 10.1.4.
_n/a_
_n/a_
---
[LW-12084]: https://input-output.atlassian.net/browse/LW-12084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LW-12084] Update `cardano-node` to 10.1.4, and `cardano-wallet` to v2025-01-09

source/renderer/app/api/wallets/types.ts, source/renderer/app/domains/Wallet.ts, source/renderer/app/utils/dataSerialization.ts, source/renderer/app/utils/shelleyLedger.ts, source/renderer/app/utils/shelleyTrezor.ts
This PR
- fixes the vote delegation form for wallets which had both: vote and pool delegation. With the recent Cardano Wallet update the form was not working properly for those wallets
- enables HW based wallets to use cip129 drep format
=> fix: vote delegation form

CHANGELOG.md
=> docs: add missing changelog entry of ledger anihillation

source/main/index.ts
This reverts commit b54a34e93e5b2cda40e626087562eed39bf3e077.
The ledger team say it’s unnecessary.
More details in [LW-12241](https://input-output.atlassian.net/browse/LW-12241).
[LW-12241]: https://input-output.atlassian.net/browse/LW-12241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "[LW-12241] Update index.ts to cater for the cleardown of ledger state"
