app/stores/UserStore.js

Application window was resizing to default size of 1024 x 768 pixels when navigating from wallets to settings and the other way back. This PR fixes that issue.

Fixes unwanted resizing of application window

---

app/api/CardanoClientApi.js
app/components/wallet/WalletRestoreDialog.js
app/containers/MainLayout.js
app/stores/WalletsStore.js

This PR fixes mnemonic validation. Validation is now done with the endpoint provided by the backend.

Mnemonic validation fix

---

installers/WindowsInstaller.hs

Without this option enabled the installer and its output are unreliable, esp.
with non-ASCII usernames.

[DAEF-12] Enable unicode installer in Windows

---

installers/.gitignore
installers/WindowsInstaller.hs

[CSL-737] Add few fixes to launcher params

---

app/components/wallet/WalletReceive.js
app/i18n/locales/en-US.json

Removes "Request a specific amount" button from the wallet receive page

---

app/components/wallet/WalletCreateDialog.js
app/components/wallet/WalletCreateDialog.scss

suppress scroll bar from create wallet dialog

---

app/api/CardanoClientApi.js
app/stores/WalletsStore.js

- Removes walletsCache from the WalletsStore
- Fixes switching to wallets after wallet is created and restored

Fix switching to wallets after wallet creation and wallet restoring

---

app/components/sidebar/Sidebar.js

Disables this state of the app bar:

Temporary disable expanding the app bar

---

app/stores/WalletsStore.js
app/stores/lib/Request.js

1. try to restore wallet with existing phrase -> shows error
2. close and reopen dialog -> error is gone!

reset wallet restore request when closing the ui dialog

---

app/components/loading/Loading.js
app/containers/LoadingPage.js
app/containers/wallet/Wallet.js
app/i18n/locales/en-US.json
app/stores/AppStore.js
app/stores/NetworkStatusStore.js
app/stores/SidebarStore.js
app/stores/WalletsStore.js

This PR introduces redirection to loading screen when the connection is lost.
It also improves router usage. We had warnings when pushing to the same route we were already on. This PR fixes that.

Back to loading screen when disconnected

---

app/components/layout/SidebarLayout.scss
app/components/wallet/layouts/WalletWithNavigation.scss
app/components/wallet/summary/WalletSummary.scss
app/components/widgets/NodeSyncStatusIcon.js
app/components/widgets/NodeSyncStatusIcon.scss
app/containers/MainLayout.js
app/i18n/locales/en-US.json
app/themes/index.global.scss

add block sync info overlay for status icon

---

app/api/CardanoClientApi.js
app/stores/NetworkStatusStore.js

- fixes NaN when node get's in sync after first local network difficulty message is received

Fix relative syncing percentage

---

appveyor.yml

Fixes https://github.com/appveyor/ci/issues/1426

appveyor: remove curl

---

installers/WindowsInstaller.hs

Forward-ports https://github.com/input-output-hk/daedalus/commit/6b25eee8aa889ef081e23f2c1774f4f0d9a084ab to master

installer: cardano-launcher use --peers-file

---

app/api/CardanoClientApi.js
app/components/wallet/ada-redemption/AdaRedemptionForm.js
app/containers/wallet/AdaRedemptionPage.js
app/stores/AdaRedemptionStore.js
electron/ipc-api/parse-redemption-code-from-pdf.js

This PR:
- introduces support for parsing version 2 of Ada redemption certificate, version 1 of the certificate is still supported
- removes temporary redemption code validation and uses endpoint for validating Ada redemption code

Feature [DAEF-102] Parsing v2 version of Ada redemption certificate

---

appveyor.yml

Let's wait for CI to confirm it works.

appveyor: use CARDANO_SL_BRANCH to set backend branch

---

features/step_definitions/lib/wallets-helpers.js
features/step_definitions/wallets-steps.js

fix wallet send tests that were broken due to markup changes

---

app/api/CardanoClientApi.js

Just small fix to avoid eslint warnings that i have overlooked

fix eslint warnings

---

app/Routes.js
app/components/settings/menu/SettingsMenu.js
app/containers/settings/Settings.js
app/stores/SidebarStore.js

Fixes https://issues.serokell.io/issue/DAEF-131

[DAEF-131] fixes settings routing

---

app/components/wallet/navigation/WalletNavigation.scss

Sets all wallet nav buttons to have the same width.

[DAEF-127] set all wallet nav buttons to equal width

---

electron/main.development.js

hopefully fixes the app name bug on Windows.

hardcode the app name for loggin folder path

---

app/components/sidebar/wallets/SidebarWalletMenuItem.js
app/containers/wallet/WalletReceivePage.js
app/lib/string-helpers.js

[DAEF-135] add ellipsis to wallet address on clipboard copy notification

---

installers/WindowsInstaller.hs

[CSLA-62] Avoid long target string in Windows shortcut

---

app/components/layout/TopBar.js
app/components/wallet/WalletSendForm.js
app/components/widgets/Transaction.js
app/config/numbersConfig.js
app/containers/wallet/WalletSummaryPage.js
app/stores/SidebarStore.js

This PR changes formatting of Ada amounts to always have 6 decimal places.

[DAEF-140] fix number decimal places when formatting ada amounts

---

app/api/CardanoClientApi.js
electron/lib/remoteLog.js
electron/main.development.js
package.json

This PR introduces tailing off `Daedalus.log` and `cardano-node.log` and sends new lines to papertrail.

Chore/daef 161 Send Daedalus and Cardano node logs to papertrail

---

app/stores/AppStore.js

This PR restricts language choices to English and Japanese in the language selection.

Chore/daef 151/Disable all languages except English and Japanese

---

app/components/wallet/settings/DeleteWalletConfirmationDialog.js
features/delete-wallet-via-settings.feature
features/step_definitions/wallets-steps.js

This PR adds wallet delete feature acceptance test.

Chore/daef 228 add Wallet Delete feature acceptance test

---

.gitignore
.travis.yml
README.md
appveyor.yml
installers/MacInstaller.hs
scripts/build-installer-unix.sh
scripts/build-installer-win64.bat
scripts/osx-build-fresh-daedalus.sh
scripts/windows-build-fresh-daedalus.bat

This is an accumulated PR for multiple PRs that were merged into the stable `cardano-sl-0.4` branch for a while (well, except PR #302, which is an one-liner fix to a problem introduced by #291):
- https://github.com/input-output-hk/daedalus/pull/269
- https://github.com/input-output-hk/daedalus/pull/285
- https://github.com/input-output-hk/daedalus/pull/291
- https://github.com/input-output-hk/daedalus/pull/302
Submitting them all together in order to reduce mgmt overhead.  Since they're already all debugged, only possible challenges are due to branch differences.
cc @domenkozar, @jmitchell, @darko-mijic

CI updates from cardano-sl-0.4

---

package.json

This PR tries to fix the travis CI integration that was broken by me with another PR.

[DAEF-247] fix the react-polymorph url in package.json

---

appveyor.yml
installers/WindowsInstaller.hs
installers/cardano-launcher.exe.manifest

Changes are already in `cardano-sl-0.4`. See PR #316.

[DEVOPS-102] Merge fix into master

---

CHANGELOG.md
app/actions/ada-redemption-actions.js
app/api/CardanoClientApi.js
app/api/index.js
app/components/wallet/ada-redemption/AdaRedemptionForm.js
app/containers/wallet/AdaRedemptionPage.js
app/i18n/locales/de-DE.json
app/i18n/locales/defaultMessages.json
app/i18n/locales/en-US.json
app/i18n/locales/hr-HR.json
app/i18n/locales/ja-JP.json
app/i18n/locales/ko-KR.json
app/i18n/locales/zh-CN.json
app/stores/AdaRedemptionStore.js

This PR introduces spending password on ada-redemption screens.

Feature/daef 271 add spending password to ada-redemption screens

---

CHANGELOG.md
app/stores/NetworkStatusStore.js

This PR introduces improved application in-sync state calculation which prevents syncing icon from being always stuck in syncing state.

Fix/daef 320 Fix syncing icon always stuck in syncing state issue

---

CHANGELOG.md
app/components/wallet/WalletSendForm.js
app/lib/validations.js

This PR introduces a fix for error with sending amount max value validation.

Fix/daef 361 Fix sending amount maximum value validation

---

CHANGELOG.md
features/step_definitions/settings-steps.js
features/step_definitions/wallets-steps.js

This PR fixes brittle acceptance test steps (wallet latest transaction amount check step).

Fix/daef 381 Detect and fix all brittle acceptance tests

---

.travis.yml

See https://github.com/NixOS/nixpkgs/issues/27493 for background

Fix travis on macOS

---

CHANGELOG.md
app/api/index.js
app/components/wallet/PaperWalletImportDialog.js
app/domain/User.js

This PR introduces a fixes for eslint code syntax warnings.

Fix/daef 387 Fix eslint warnings

---

CHANGELOG.md
app/api/CardanoClientApi.js
app/api/mocks/patchCardanoApi.js
app/lib/logger.js
app/stores/AdaRedemptionStore.js
app/stores/NetworkStatusStore.js
electron/lib/remoteLog.js
electron/main.development.js
package.json

This PR fixes ENOENT error caused by log file rotation by replacing log-file tailing logic with direct logging.

Fix/daef 408 ENOENT error

---

CHANGELOG.md
app/components/loading/Loading.scss
app/themes/daedalus/theme1.js
app/themes/daedalus/theme2.js
app/themes/daedalus/themeDefault.js
package.json

This PR introduces a theming support fix on UI which was introduced after introduction of Theming feature.

Fix/daef 430 Add theming support on UI which was introduced after introduction of Theming feature

---

CHANGELOG.md
app/api/CardanoClientApi.js
app/api/index.js
app/stores/NodeUpdateStore.js
flow/declarations/DaedalusClientApi.js

[CSM-485] `PostponeUpdate` endpoint for 0.6 branch.

---

installers/WindowsInstaller.hs

We still need to test this has the desired effect.

[DEVOPS-414] Sign cardano-launcher.exe after setting manifest

---

app/api/etc/changeEtcAccountPassphrase.js
app/api/etc/index.js
app/stores/WalletStore.js

This PR introduced integration of ETC update wallet password endpoint.

Feature/daef 532 Integrate ETC update wallet password endpoint

---

app/api/etc/changeEtcAccountPassphrase.js
app/api/etc/createEtcAccount.js
app/api/etc/deleteEtcAccount.js
app/api/etc/getEtcAccountBalance.js
app/api/etc/getEtcAccounts.js
app/api/etc/getEtcBlock.js
app/api/etc/getEtcBlockNumber.js
app/api/etc/getEtcEstimatedGas.js
app/api/etc/getEtcSyncProgress.js
app/api/etc/getEtcTransaction.js
app/api/etc/getEtcTransactions.js
app/api/etc/index.js
app/api/etc/lib/request.js
app/api/etc/sendEtcTransaction.js
app/stores/TransactionsStore.js

This PR introduces Mantis HTTPS/TLS setup.

Feature/daef 540 Setup HTTPS/TLS with Mantis

---

CHANGELOG.md
app/api/etc/changeEtcAccountPassphrase.js
app/api/etc/createEtcAccount.js
app/api/etc/deleteEtcAccount.js
app/api/etc/getEtcAccountBalance.js
app/api/etc/getEtcAccounts.js
app/api/etc/getEtcBlock.js
app/api/etc/getEtcBlockNumber.js
app/api/etc/getEtcEstimatedGas.js
app/api/etc/getEtcSyncProgress.js
app/api/etc/getEtcTransaction.js
app/api/etc/getEtcTransactions.js
app/api/etc/index.js
app/api/etc/sendEtcTransaction.js
app/components/wallet/WalletAddDialog.js
app/components/wallet/WalletSendForm.js

This PR introduces cleanup and standardization of ETC Api calls.

Chore/daef 546 Cleanup and standardize ETC Api calls

---

installers/Launcher.hs
installers/WindowsInstaller.hs

I did not test (don't know the entire procedure to build the installers), but the change is simple.

[CSL-1758] Pass Node DB path to launcher

---

.travis.yml
appveyor.yml
scripts/build-installer-unix.sh

Switch to Buildkite-provided Cardano builds.

[DEVOPS-528]  installer | OS X:  convert to the Buildkite bucket

---

CHANGELOG.md
README.md

This PR updates README with Cardano SL build & run steps.

Chore/ddw 71 Document Cardano SL build

---

CHANGELOG.md
README.md
installers/WindowsInstaller.hs
installers/build-certificates-win64.bat
installers/cardano-installer.cabal
installers/cardano-installer.nix
package.json

This PR merges latest master into our development branch as a part of the preparations for the upcoming release.

Merge master into development branch

---

CHANGELOG.md
source/renderer/app/api/ada/index.js
source/renderer/app/stores/NetworkStatusStore.js

This PR ports over the work from PR #689 to the new project setup.

[DDW-89] port ddw-61 to new build setup

---

CHANGELOG.md
source/renderer/app/stores/NetworkStatusStore.js

This ports PR #678 over to the new build setup.

[DDW-88] port over ddw-76 to new build setup

---

CHANGELOG.md
source/renderer/app/api/ada/lib/request.js
source/renderer/app/api/etc/lib/request.js
source/renderer/app/components/loading/Loading.js
source/renderer/app/stores/NetworkStatusStore.js

This PR ports #696 over to the new build setup.

[DDW-90] port ddw-84 to new build setup

---

.travis.yml
default.nix

Latest version of nixpkgs release-17.09 branch brings in Electron 1.7.11.

[DEVOPS-657] nix-shell: Update nixpkgs version

---

features/step_definitions/local-time-difference-steps.js

This PR fixes acceptance test.

Chore/ddw 101 Run acceptance tests on release/0.9.0 branch in demo mode

---

features/step_definitions/local-time-difference-steps.js

Ports the final fix https://github.com/input-output-hk/daedalus/pull/726/files#diff-5120c144d0020eccb8b324e2abe6ec58L4 over to our fork.

Chore/ddw 114 port ddw 101 to fork (FORK)

---

CHANGELOG.md
source/renderer/app/stores/NetworkStatusStore.js

This PR ports #719 over to the fork.

[DDW-113] port ddw-93 to FORK

---

CHANGELOG.md
source/renderer/app/stores/WalletStore.js
source/renderer/app/stores/ada/AdaWalletsStore.js

This PR ports #735 over to the fork.

[DDW-120] port ddw-119 to FORK

---

package.json
source/renderer/webpack.config.js

This ports #724 over to the fork.

[DDW-115] port DEVOPS-676 to fork

---

README.md
appveyor.yml

Change secrets to use new appveyor account.

[DEVOPS-679] appveyor

---

README.md
appveyor.yml

Change secrets to use new appveyor account.

release: [DEVOPS-679] appveyor

---

installers/launcher-config-mac.yaml
installers/launcher-config-windows.yaml

Reverts input-output-hk/daedalus#729

Revert "[CSL-2307] Do not redirect cardano-node's logs to a file"

---

source/renderer/app/components/loading/Loading.js

This PR ports #767 to the fork.

Chore/ddw 158 Port DDW-154 to fork

---

installers/MacInstaller.hs
scripts/build-installer-unix.sh

npm run package now needs to be after iconset conversion.

[DDW-169] Run npm install and package from MacInstaller.hs

---

CHANGELOG.md
source/renderer/app/stores/TransactionsStore.js

This PR ports #784 to the fork.

Chore/ddw 183 Port DDW-166 to fork

---

CHANGELOG.md
package-lock.json
package.json

This PR ports #782 to the fork.

Chore/ddw 182 port DDW-168 to fork

---

appveyor.yml

[DEVOPS-727]   Mitigation

---

appveyor.yml

This PR ports #800 to the fork.

Chore/ddw 192 Port DEVOPS-727 to fork

---

package-lock.json
source/main/windows/about.js
source/main/windows/main.js

This PR adds missing Daedalus icon to the About window on Linux build.
Previously we were showing a generic icon:

Fix/ddw 196 Add About window icon for Linux build

---

package-lock.json
package.json
yarn.lock

This PR updates electron to version `1.7.13` to avoid the potential security issue https://nvd.nist.gov/vuln/detail/CVE-2018-1000136

[DDW-213] updated to electron 1.7.13

---

CHANGELOG.md
source/renderer/app/components/loading/Loading.js

This PR introduces improvement for timers setup on Loading screen.

Chore/ddw 163 Improve timers setup on Loading screen

---

appveyor.yml
cardano-sl-src.json
installers/AppVeyor.hs

This PR is to overcome https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-801 and get a Daedalus build.

[DEVOPS-801]  Windows fix

---

launcher-config.yaml
source/renderer/app/components/layout/SidebarLayout.scss
source/renderer/app/components/layout/TopBar.scss
source/renderer/app/components/layout/TopBarLayout.scss
source/renderer/app/components/notifications/NodeUpdateNotification.scss
source/renderer/app/components/notifications/RestoreNotification.scss
source/renderer/app/components/settings/menu/SettingsMenuItem.scss
source/renderer/app/themes/daedalus/cardano.js
source/renderer/app/themes/daedalus/dark-blue.js
source/renderer/app/themes/daedalus/light-blue.js

This PR resolves some minor UI defects in Dark theme such as missing shadows and wrong text hover color in general settings menu.
It also adds missing `launcher-config.yaml` file as a fix for: https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-802 issue.

Fix/ddw 224 Dark blue theme UI improvements and fix for missing launcher-config.yaml in local development

---

default.nix
installers/nix/nix-installer.nix

[CSL-2472] detect a lack of SSE4 during the install

---

.github/pull_request_template.md
CHANGELOG.md

This PR adds PR template with review checklist: https://github.com/input-output-hk/daedalus/blob/chore/ddw-206-create-pr-template-with-review-checklist/.github/pull_request_template.md

Chore/ddw 206 Create PR template with review checklist

---

appveyor.yml
scripts/build-installer-win64.bat

* Apply github status api fix to develop branch.
* Fix `.bat` file error handling.

[DEVOPS-801] Improve AppVeyor CI reliability

---

cardano-sl-src.json

[R120-4] Update cardano-sl-src.json to latest release/1.2.0

---

cardano-sl-src.json

[DEVOPS-828]  cardano-sl:  bump to the tip of release/1.2.0

---

CHANGELOG.md
source/renderer/app/components/settings/categories/DisplaySettings.js
source/renderer/app/components/wallet/paper-wallet-certificate/SecuringPasswordDialog.scss
source/renderer/app/components/widgets/NodeSyncStatusIcon.scss

This PR disables dragging of static UI images elements:
- TopBar: Node sync status icon
- General Settings > Display: Theme thumbnail images
- Paper wallet certificate > 3rd dialog: Paper wallet certificate thumbnail
---

Fix/ddw 257 Prevent dragging of images within the application

---

cardano-sl-src.json
default.nix
release.nix
tests/flow.nix
tests/lint.nix
yarn2nix.nix

This PR adds hydra tests for flow and eslint which are currently both broken, but I'm opening a PR to make sure the nix integration with hydra is working properly.
---

[DEVOPS-842] hydra CI tests for flow and eslint

---

.buildkite/pipeline.yml
scripts/build-installer-nix.sh

This PR fixes failing BK Linux build.
---

[DEVOPS-855] just use the variable as-is

---

cardano-sl-src.json

Makes mainnet installers have applicationVersion 6 and staging have 11.
---

Update the `applicationVersion`s embedded in the 1.2 RC6 installers

---

CHANGELOG.md
source/renderer/app/components/wallet/transactions/WalletTransactionsList.js

This PR ports #699 to target latest `develop` branch without introducing old changes.
---

[DDW-288] ports ddw-70 to target latest develop

---

CHANGELOG.md
source/renderer/app/stores/ada/NodeUpdateStore.js

This PR fixes the node update handling code to properly wait for the request.

[DDW-283] properly wait for node update

---

package-lock.json
package.json
yarn.lock

This PR upgrades the `webpack-stream` package to fix weird crashes in the terminal, while the app continues to run (only happens in development mode).

[DDW-299] upgrade webpack-stream package to fix crashes in dev mode

---

.gitignore
default.nix
installers/build-certificates-unix.sh
scripts/build-installer-nix.sh
scripts/build-installer-unix.sh
scripts/nix-shell.sh
tests/shellcheck.nix

[DEVOPS-846] shellcheck compliance of all scripts

---

cardano-sl-src.json
installers/common/AppVeyor.hs

[DEVOPS-864] Download CardanoSL.zip from S3 if it exists

---

CHANGELOG.md
source/renderer/app/api/ada/getAdaWallets.js
source/renderer/app/config/numbersConfig.js

This PR limits the maximum number of wallets to 20.
---

[DDW-309] Limit maximum number of wallets to 20

---

README.md
features/README.md
tls/README.md

This PR changs the way documentation info is presented.
---

[DDW-324] Improved documentation info section

---

package-lock.json

This PR restores deleted `package-lock.json` file. The file was deleted by mistake and looks like we still need it...
---

[DDW-326] Restore deleted package-lock.json file

---

source/common/environment.js
source/main/windows/main.js
source/renderer/app/api/ada/sendAdaBugReport.js
source/renderer/app/api/etc/sendEtcBugReport.js
source/renderer/app/components/static/About.js
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/utils/paperWalletPdfGenerator.js

This PR fixes missing Cardano version in Daedalus titlebar.
Until recently Daedalus would receive a build number ENV variable which consisted of both Cardano and build numbers. Devops have now decided to send these two numbers separately through BUILD_NUMBER and API_VERSION ENV variables and therefore we need to construct the complete build version in Daedalus code.
---

[DDW-345] Add Cardano version to Daedalus titlebar

---

source/common/environment.js
source/main/windows/main.js
source/renderer/app/i18n/locales/defaultMessages.json

This PR adds code style improvements and requested PR changes for the following PR: https://github.com/input-output-hk/daedalus/pull/1000
Paper wallet certificate Daedalus version is also modified - the version is now presented in brackets (same as in the titlebar)...
---

[DDW-345] Add Cardano version to Daedalus titlebar - Code style improvements

---

CHANGELOG.md
source/renderer/app/utils/paperWalletPdfGenerator.js

This PR fixes the paper wallet certificate QR code compatibility/recognition issues.
The problem with the compatibility was that the old QR code was generate with too much details (it was too fragmented) and by reducing error-correction from `High` to `Low` we achive ultimate compatibility and now the QR code within the paper wallet certificate looks the same as the one on the Wallet Receive screen.
---

[DDW-341] Improve paper wallet certificate QR code compatibility

---

release.nix

Fixes the issue where Linux Daedalus was not showing the build number in the title bar.
This PR targets base branch `release/0.11.0`, if there will be another RC. If there will not be another RC, then I will shift this to `release/0.11.1`.

[DEVOPS-943] release.nix: pass buildNum to installer

---

cardano-sl-src.json

Cardano bumped to release/1.3.0 for RC5.

Bump Cardano to 1.3.0 RC5

---

gulpfile.js
package.json
yarn.lock

This PR fixates all npm dependencies as storybook ones had loose versions in package.json.
In the scope of this PR `gulp clear-cache` script name was updated to match the standard column style: `gulp clear:cache`.
---

[DDW-362] Fixate all npm dependencies and update script names

---

package.json
yarn.lock

This PR pins the `eslint-scope` package version to `3.7.1` using the [yarn version resolution feature](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/).
---

[DDW-353] pin eslint-scope version via the yarn resolutions feature

---

CHANGELOG.md
package-lock.json
package.json
source/common/ipc-api.js
source/main/index.js
source/main/ipc-api/get-gpu-status.js
source/main/ipc-api/index.js
source/main/menus/osx.js
source/main/menus/win-linux.js
source/main/utils/mainErrorHandler.js
source/main/utils/rendererErrorHandler.js
source/main/windows/main.js
source/renderer/app/actions/app-actions.js
source/renderer/app/stores/AppStore.js
source/renderer/app/types/gpuStatus.js
yarn.lock

_This is a port from the [PR 1007](https://github.com/input-output-hk/daedalus/pull/1007), which was done as a fix for `develop`, instead of `release/0.11.1`_
This PR fixes a bug in the Electron version which we use in Daedalus which results in blank/white screen rendering on some OS/Graphics-card/Drivers combinations.
It also creates a "Restart in Safe Mode" option in the app menu.
---

[DDW-342] fix white screen rendering bug

---

source/main/index.js

**This PR fixes a small bug in development:**
Currently, when you start Daedalus in dev mode (e.g: npm run dev) without backend node running, there will be two windows created instead of one main window. This is an artifact from the times where we had a separate about window, which wasn't 100% cleaned up.
The fix is very simple and risk-free (doesn't touch any other code paths or logic)
---

[DDW-372] Fix double window bug when running in dev without backend

---

cardano-sl-src.json
installers/common/WindowsInstaller.hs
installers/dhall/staging.dhall

0. Fix Daedalus/win64 build to pick up the proper topology file, so the right report-server is used.
0. Since the `report-server.awstest.iohkdev.io` _MUST_ point to the `mainnet` report-server because of the mainnet users with mis-configured Daedalus, we introduce `staging-report-server.awstest.iohkdev.io` and redirect `staging` installers to that.
- Screenshot
---

[DEVOPS-1001] copy launcher-config to root of repo

---

CHANGELOG.md
source/common/environment.js
source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.js
source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.js
source/renderer/app/components/wallet/transactions/Transaction.js
source/renderer/app/config/urlsConfig.js
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/utils/ada/network.js

This PR implements a check for the network Daedalus is running on before opening the Cardano network explorer in an external browser.
Previously each link _only_ opened the mainnet network explorer. 
With the additions in this PR, the links will now open the appropriate network explorer depending on if the user is running Daedalus on the mainnet, testnet, or staging network.
---

[DDW-385] use testnet explorer links in testnet build

---

CHANGELOG.md
source/common/environment.js
source/renderer/app/components/sidebar/Sidebar.js
source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.js
source/renderer/app/stores/SidebarStore.js
source/renderer/app/types/sidebarTypes.js
storybook/stories/SidebarCategory.stories.js
storybook/stories/WalletScreens.stories.js
storybook/stories/support/StoryDecorator.js
storybook/stories/support/StoryLayout.js

This PR fixes our broken storybook.
**PLEASE NOTE:**
The reason for this issue was that code in `environment.js` referenced the electron specific `app` module directly. This effectively results in webpack code that expects a node.js environment to be available. This of course is not the case in storybook (browser only), so we need to keep any electron/node.js reference out of the hard-compiled source -> you can see how i changed the environment.js code todo this.
This is part of the larger issue that we are still using node integration in the render processes, which we are removing in the long term. When that refactoring is done, these mistakes should happen less often and the code for electron / frontend will be more cleanly separated.
**A note on file references**
I also saw that the …

[DDW-378] fix broken storybook

---

source/renderer/webpack.config.js

This PR debugs NODE_ENV issues on CI builds.
When the installers get produced the CI it looks like the rendering process is built with `environment.current = development`. Therefore we need to inspect why the rendering process doesn't handle `process.env.NODE_ENV` correctly. 
---

[DDW-396] Debug NODE_ENV issues on CI builds

---

source/main/index.js
source/main/utils/mainErrorHandler.js

This PR implements logging GPU-crash events.
---

[DDW-403] Log GPU-crash events

---

source/main/index.js

This PR adds
```
!!! Daedalus is running on darwin version 17.7.0
with CPU: [...]
with 8589934592 total RAM !!!
```
```
!!! Daedalus (0.11.1#1.3.0) is running on darwin version 17.7.0
with CPU: [...]
with 8589934592 total RAM !!!
```
---

[DDW-416] Add Daedalus and Cardano version to Daedalus logs

---

source/renderer/app/themes/daedalus/cardano.js
source/renderer/app/themes/daedalus/dark-blue.js
source/renderer/app/themes/daedalus/light-blue.js

This PR adds the correct colors for the transaction toggle arrow in different themes.
---

[DDW-411] Transaction toggle arrow colors

---

CHANGELOG.md
source/renderer/app/i18n/locales/terms-of-use/ada/other/ja-JP.md

This PR implements Japanese Terms of use for Testnet network.

[DDW-419] Implement Japanese Terms of use for Testnet network

---

source/renderer/app/api/common.js
source/renderer/app/i18n/locales/de-DE.json
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/i18n/locales/en-US.json
source/renderer/app/i18n/locales/hr-HR.json
source/renderer/app/i18n/locales/ja-JP.json
source/renderer/app/i18n/locales/ko-KR.json
source/renderer/app/i18n/locales/zh-CN.json

This PR updates the Generic Api error message.
Before:
`An error occurred, please try again later.`
After:
`An error occurred.`
---

[DDW-389] Update Generic Api error message

---

source/renderer/app/api/common/errors.js
source/renderer/app/i18n/locales/de-DE.json
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/i18n/locales/en-US.json
source/renderer/app/i18n/locales/hr-HR.json
source/renderer/app/i18n/locales/ja-JP.json
source/renderer/app/i18n/locales/ko-KR.json
source/renderer/app/i18n/locales/zh-CN.json

This improves "Forbidden mnemonic" error message text.
---

[DDW-418] Improve 'Forbidden mnemonic' error message

---

source/renderer/app/api/common/errors.js
source/renderer/app/i18n/locales/de-DE.json
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/i18n/locales/en-US.json
source/renderer/app/i18n/locales/hr-HR.json
source/renderer/app/i18n/locales/ja-JP.json
source/renderer/app/i18n/locales/ko-KR.json
source/renderer/app/i18n/locales/zh-CN.json

This PR merges `release/0.11.1` changes into `develop` branch.
---

[DDW-422] Merge release/0.11.1 into develop

---

cardano-sl-src.json

Bumps cardano-sl to the tip of release/1.3.1.

[DEVOPS-998] [CO-354] Update cardano-sl to PR branch

---

installers/common/WindowsInstaller.hs

[DEVOPS-1084] fix unicode in uninstaller

---

CHANGELOG.md

This PR updates the CHANGELOG.
---

[DDW-434] Clean up and proof-read CHANGELOG

---

CHANGELOG.md

This PR adds all missing 0.12.0 release items to the CHANGELOG.
---

[DDW-439] Add all release items to the CHANGELOG

---

features/support/helpers/wallets-helpers.js

This PR fixes our broken sequential creation of test wallets.
---

[DDW-441] Fix broken sequential creation of test wallets

---

source/main/windows/main.js

This PR fixes the broken Daedalus icon on Linux.
---

[DEVOPS-1096] Fix Daedalus icon on Linux

---

default.nix
installers/nix/nix-installer.nix

This PR merges cherry picked code from commit c9c72a5f7ab67a4088d1776f126f239131e32986 (PR targeting `develop` branch: https://github.com/input-output-hk/daedalus/pull/1135)
---

[DEVOPS-1095] allow opening links when in the sandbox

---

CHANGELOG.md
source/main/index.js

This adds Daedalus and Cardano version to Daedalus logs.
This PR is a re-introduces the changes originally implemented in: https://github.com/input-output-hk/daedalus/pull/1094 (and lost in later merges)...
```
!!! Daedalus is running on darwin version 17.7.0
with CPU: [...]
with 8589934592 total RAM !!!
```
```
!!! Daedalus (0.11.1#1.3.0) is running on darwin version 17.7.0
with CPU: [...]
with 8589934592 total RAM !!!
```
---

[DDW-445] Add Daedalus and Cardano version to Daedalus logs

---

cardano-sl-src.json
installers/dhall/launcher.dhall

replaces PR #1141, now against `release/0.12.0`

[DEVOPS-1109] cli argument to inhibit console log: --log-console-off

---

README.md
shell.nix

This PR updates README and shell.nix.
---

[DEVOPS-1110] shell.nix/README doc updates for demo cluster

---

shell.nix

This fixes `chromedriver` issues in `nix` environment by supplying it via `nix` instead of the `npm`.
**Note:**
These changes have no impact on the way `nix-shell` is used in the development cycle - so if you are using `yarn nix:dev` and then `yarn test` to run Daedalus tests it will still use your system dependencies.
However, if you start the tests through: `nix-shell --run "yarn test"` then `nix` will purge and install all the dependencies from scratch.
---

[DDW-447] Fix yarn test in nix shell

---

package.json
source/main/cardano/setup.js
source/main/index.js
source/main/utils/lock-files/adapter.js
source/main/utils/lock-files/index.js
source/main/utils/lock-files/lockfile.js
source/main/utils/lockFiles.js
source/main/webpack.config.js
yarn.lock

This PR fixes the broken lock file strategy (especially for Windows).
- Switched from `lockfile` package to [proper-lockfile](https://github.com/moxystudio/node-proper-lockfile/) which does one important thing for us: it touches the lockfile every 2 seconds and considers any lockfile that hasn't been touched more than 5 seconds as stale. So even if Daedalus crashes badly and the lockfile sticks around - it is considered irrelevant after 5 seconds.
- Also the main window does not close immediately and waits until cardano-node is properly stopped / killed … so that the user sees a "Stopping cardano node … " message before the app quits.
- The stopping timeout for cardano-node was reduced to 10 seconds … after that it is killed.
---

[DDW-448] Fix lockfile logic

---

cardano-sl-src.json

This PR bumps Cardano version to the tip of `develop` branch.
---

[DDW-450] Bump Cardano version

---

cardano-sl-src.json

Takes the latest revision of the release/2.0.0 branch.

[DEVOPS-1112] Update cardano-sl to release/2.0.0 branch

---

cardano-sl-src.json

This keeps `applicationVersion`'s as-is, since we're going to do a testnet proposal instead of a staging one, per @alan-mcnicholas suggestion.
---

cardano-sl:  bump to latest `release/2.0.0`

---

CHANGELOG.md
source/renderer/app/components/wallet/WalletAdd.js
source/renderer/app/components/wallet/WalletSettings.js
source/renderer/app/components/wallet/WalletSettings.scss

This PR disables Wallet Import and Export functionality for "Testnet" network.
---

[DDW-486] Wallet Import & Export functionality is not implemented but UI is exposed in TestNet build.

---

CHANGELOG.md
default.nix
shell.nix

This PR fixes window icon issues on Linux which were a result of using high quality icon which was poorly downscaled in order to be used as a small window title bar icon.
---

[DDW-490] Use a small icon for the window and a large icon for the desktop

---

CHANGELOG.md
package.json
yarn.lock

This PR bumps `React-Polymorph` version used in Daedalus to the latest version (`0.7.2`) which contains fixes for the `NumericInput` component carret positioning issues introduced in: https://github.com/input-output-hk/react-polymorph/pull/94
---

[DDW-488] Amount field minor malfunction

---

CHANGELOG.md
source/renderer/app/stores/ProfileStore.js

This PR fixes an issue which caused the send bug report form in `BugReportDialog.js` to hang and not send the support request if the logs were downloaded before attempting to submit the request.

[DDW-494] Fixes send bug report form after downloading logs

---

CHANGELOG.md
source/main/index.js
source/main/ipc/compress-logs.js
source/main/utils/setupLogging.js

This PR changes API calls logging level from 'debug' to 'info'. All of our previous 'debug' log messages are important and should be kept in the Daedalus log files. Therefore, we have decided to record those same messages at 'info' level. However, we did not use info level logger for them - from the application POV they are still recorded as 'debug' error messages.
This is achieved by overriding 'debug' message level text before it is outputted to the Daedalus log file. We have kept those calls on 'debug' level as that way we can have them in the Daedalus log file and not have them in the console or the terminal window.
---

[DDW-498] Use info instead of debug logger for API calls

---

CHANGELOG.md
README.md
source/main/cardano/config.js

This PR enables Cardano Wallet API documentation server in development mode.
While Daedalus is running you can reach the documentation server using your Browser on the following URL: https://localhost:8091/docs/v1/index/
---

[DDW-499] Enable Cardano Wallet API documentation server in development mode

---

CHANGELOG.md
package.json

This PR bumps Daedalus version to `0.11.2` and improves CHANGELOG entry.
---

[DDW-501] Prepare Daedalus 0.11.2 release

---

CHANGELOG.md

This PR merges `master` code into `release/0.12.0` branch.

Merge master into release/0.12.0 branch

---

CHANGELOG.md
features/wallet-settings.feature
source/renderer/app/utils/validations.js

This PR ports https://github.com/input-output-hk/daedalus/pull/1196 to `release/0.12.0`.
---

[DDW-497] Adds support for non-Latin characters in spending password

---

installers/dhall/demo.dhall
installers/dhall/staging.dhall
installers/dhall/testnet.dhall

[DEVOPS-1166]  --metrics is also needed to start EKG

---

cardano-sl-src.json

bump cardano rev to tip of release/2.0.0

---

source/main/menus/MenuActions.types.js
source/main/menus/osx.js
source/main/menus/win-linux.js

This PR fixes the broken app menu on windows and linux and also cleans up the code on the way by adding proper flow type checks.
---

[DDW-512] Fix and improve menu code for Windows and Linux

---

CHANGELOG.md
source/renderer/app/components/status/NetworkStatus.scss

This PR fixes the flickering issue on Network Status screen syncing chart.
---

[DDW-461] Fix flickering issue on Network Status screen syncing chart

---

cardano-sl-src.json

Release 0.12 cardano bump

---

CHANGELOG.md
README.md

This PR fixes Cardano setup steps in Daedalus README file.
---

[DDW-522] Fix the Cardano setup steps in README file

---

CHANGELOG.md
source/main/windows/main.js
source/renderer/app/components/loading/SystemTimeErrorOverlay.scss
source/renderer/app/components/profile/data-layer-migration/DataLayerMigrationForm.scss
source/renderer/app/components/wallet/WalletRestoreDialog.scss
source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.scss
source/renderer/app/components/wallet/transactions/Transaction.js
source/renderer/app/components/widgets/Dialog.scss
source/renderer/app/themes/daedalus/cardano.js
source/renderer/app/themes/daedalus/dark-blue.js
source/renderer/app/themes/daedalus/light-blue.js
source/renderer/app/themes/overrides/SelectOverrides.scss
source/renderer/app/themes/overrides/index.js

This PR fixes the [following accepted](https://docs.google.com/document/d/1YU5R0rLIiacTREnCPOcsUlx_iqVmU2AUaJbnVHGgobg/edit) design issues.
---

[DDW-508] Design implementation fixes

---

yarn2nix.nix

[DEVOPS-1180] fix nuke-refs some more files

---

cardano-sl-src.json

Updates cardano-sl for staging update proposal of 2.0.0 RC7.

[DEVOPS-1112] Bump cardano-sl to latest release/2.0.0

---

CHANGELOG.md
shell.nix

This PR fixes Daedalus shell to evaluate embedded variables properly
---

[DEVOPS-1192] Eval variables in statePath for nix-shell

---

bors.toml

This PR updates bors to no longer require Appveyor build to be successful for merging as we are currently experiencing Appveryor <-> Github status communication issues.
---

[DEVOPS-1200] Disable Appveyor checks for bors

---

CHANGELOG.md
source/renderer/app/themes/mixins/animations.scss
source/renderer/app/themes/mixins/loading-spinner.scss

This PR fixes broken ellipsis `...` animation on the Loading screen. The animation got broken due to Webpack 4 / SCSS loader update.
---

[DDW-542] Fix ellipsis animation on Loading screen

---

bors.toml

This reverts commit 9df176b1e302e3006a4c8968a8df3a2226405e7a (PR: https://github.com/input-output-hk/daedalus/pull/1250).
---

[DEVOPS-1200] Disable Appveyor checks for bors - REVERT

---

installers/nix/electron.nix
installers/nix/linux.nix
package.json
source/main/windows/main.js
source/renderer/app/api/utils/localStorage.js
yarn.lock

This PR reverts Electron to version `3.0.13` and keeps the `electron-chromedriver: 4.0.0-beta.1` as this combination fixes all blank window rendering issues and keeps the acceptance tests working too.
---

[DDW-541] Fix blank window rendering issue

---

CHANGELOG.md
source/renderer/app/api/api.js

This PR fixes the transaction loading logic which prevented loading more than 50 transactions for a single wallet. Because of this issue, users would see a maximum of 50 transactions on the "Transactions" screen and a false "Total number of transactions" on the "Summary" screen.
---

[DDW-562] Fix the transaction loading logic

---

cardano-sl-src.json

[DEVOPS-1203] Update cardano-sl to latest release/2.0.1

---

CHANGELOG.md
source/renderer/app/stores/TransactionsStore.js

This PR limits the maximum number of transactions to 500.
By doing this we eliminate potential performance issues on the "Transactions" screen.
We need to implement a proper solution for this problem which will enable us to display all the transactions in the wallet regardless of their count... This is planned for the next release.
---

[DDW-563] Loading all transactions impacts performance

---

cardano-sl-src.json

Developing Daedalus on macOS Mojave currently fails as the
cardano-node that the deadalus-bridge tries to load comes from
cardano-sl @ release/2.0.1.  That in turn uses an outdate nixpkgs
version which is the underlying issue for the cardano-node crashing at
startup.
You will find something along the lines of
```
Launcher config:  /nix/store/yflym86m9j0bp8jj4mvw16n9v17mkig3-launcher-config.yaml
'./cardano-node' -> '/nix/store/c7lp8lyr38rm7vk54j9cdhx29biq06xv-cardano-daedalus-bridge-2.0.1/bin/cardano-node'
'./wallet-topology.yaml' -> '/nix/store/23vwnpfdyczbgn2d93vrsm45lq97kcgz-launcher-config/etc/wallet-topology.yaml'
'./log-config-prod.yaml' -> '/nix/store/23vwnpfdyczbgn2d93vrsm45lq97kcgz-launcher-config/etc/log-config-prod.yaml'
'./configuration.yaml' -> …
```

[DEVOPS-1090] Bump cardano-sl to current develop

---

storybook/stories/index.js
storybook/stories/support/environment.js

This PR fixes broken storybook by setting up the global environment like in the "real" environments.
---

[DDW-568] Fix broken Storybook

---

CHANGELOG.md
source/renderer/app/components/loading/Loading.js
source/renderer/app/containers/LoadingPage.js
source/renderer/app/containers/Root.js
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/stores/NetworkStatusStore.js
source/renderer/app/stores/ProfileStore.js

- This PR allows the user to set the language locale and/or accept the terms of use before the node has connected with the network or synced with the blockchain.
- Assuming the user has already set a language locale and accepted the terms of use, the changes in this PR also allow the user to load and make use of the **GeneralSettingsPage** before the node has connected or synced with the blockchain.

[DDW-566] Decouples LoadingPage and Initial Setup

---

cardano-sl-src.json

Testnet config update to fix linux auto-updating.
- Screenshot
---

[DEVOPS-1219] cardano version bump for testnet config

---

CHANGELOG.md
source/main/preload.js
source/renderer/app/components/layout/TopBar.scss
source/renderer/app/components/profile/terms-of-use/TermsOfUseText.scss
source/renderer/app/components/static/About.scss
source/renderer/app/components/wallet/WalletReceive.scss
source/renderer/app/components/wallet/WalletSendConfirmationDialog.scss
source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.scss
source/renderer/app/components/wallet/skins/AmountInputSkin.scss
source/renderer/app/components/wallet/summary/WalletSummary.scss
source/renderer/app/components/wallet/transactions/Transaction.scss

This PR fixes text selection issues (disabled drag and drop of selected text and enabled unselect option).
---

[DDW-571] Several minor issues with text selection

---

cardano-sl-src.json

This PR resolves the conflicts from https://github.com/input-output-hk/daedalus/pull/1290

Release/0.12.1 (Linux Testnet applicationVersion bump)

---

CHANGELOG.md
default.nix
installers/nix/nix-installer.nix
yarn2nix.nix

This PR fixes Japanese font rendering issues in the application menu by allowing `fontconfig` inside the sandbox to use the packaged fonts.
---

[DDW-570] Japanese text not being rendered on Linux

---

installers/common/MacInstaller.hs
installers/overlays/add-test-stubs.nix
scripts/build-installer-win64.bat

This PR updates the BK to use `yarn` for building `macOS` installers.
---

[DEVOPS-1232] Fix macOS and AppVeyor CI

---

CHANGELOG.md
source/main/windows/main.js

This PR fixes some Chrome Dev-Tools errors.
---

[DDW-556] Fix Chrome Dev-Tools errors

---

CHANGELOG.md
source/renderer/app/components/wallet/receive/WalletReceive.scss
source/renderer/app/i18n/locales/defaultMessages.json

This PR fixes issues in the Virtual lists for Transactions and Addresses.
---

[DDW-565] Improve 'Receive' screen UX

---

CHANGELOG.md
source/renderer/app/components/wallet/layouts/WalletWithNavigation.scss
source/renderer/app/components/widgets/NotificationMessage.js
source/renderer/app/components/widgets/NotificationMessage.scss
source/renderer/app/containers/wallet/WalletReceivePage.js

This PR fixes the scrollbar on WalletReceive over the copy address notification.
---

[DDW-565] Fixes scrollbar over notification 

---

cardano-sl-src.json

This PR bumps the cardano-sl version to the tip of develop branch which prevents the automatic-update notification as currently used cardano-sl revision has older applicationVersion than the one proposed to Staging and Testnet networks.
---

[DDW-574] Bump Cardano-sl version to the tip of develop branch

---

CHANGELOG.md
package.json

This PR bumps Daedalus version to `0.13.0`.
---

[DDW-578] Bump Daedalus version

---

CHANGELOG.md
cardano-sl-src.json
source/renderer/app/api/api.js
source/renderer/app/api/nodes/types.js
source/renderer/app/api/utils/patchAdaApi.js
source/renderer/app/config/timingConfig.js
source/renderer/app/stores/NetworkStatusStore.js

This PR updates the way NTP API response is handled.
The API now exposes `localTimeInformation.status` field which allows us to track the state of Node's NTP check. This change fixes the flashing-red-screen issue during polled NTP force-checks.
This PR also removes NTP force-check poller since Node itself runs the NTP force-check every 30 mins.
---

[DDW-585] Update NTP API response handling

---

appveyor.yml

the CERT_PASS has been encrypted and only appveyor can decrypt it:
https://www.appveyor.com/docs/build-configuration/#secure-variables
(cherry picked from commit 24921f99bdd2ef2a306b03cfadaa202b1c99553d)
- Screenshot
---

[DEVOPS-1238] Update the Windows signing certificate and secret

---

appveyor.yml

This reverts commit c47e7297a73243788d668d527877bf1cd86dc551.
- Screenshot
---

Revert "[DEVOPS-1238] update the windows signing certificate and secret"

---

cardano-sl-src.json

Bump Cardano revision to the tip of the release/3.0.0 branch

---

CHANGELOG.md
source/common/types/environment.types.js
source/main/environment.js
source/main/webpack.config.js
source/renderer/webpack.config.js

This PR removes the `REPORT_URL` env variable.
Description: We no longer use and need the REPORT_URL handling so it can be completely removed from the code base.
---

[DDW-591] Removal of the REPORT_URL env variable

---

cardano-sl-src.json

bump cardano rev to tip of cardano-sl develop

---

.prettierignore
CHANGELOG.md
package.json
source/main/windows/main.js
source/renderer/app/containers/Root.js

This PR changes the `pre-push` hook to just do a formatting check … so the developer has to fix the formatting manually and commit those changes appropriately.
---

[DDW-597] Fix pre-push hook

---

cardano-sl-src.json

[DEVOPS-1250] bump cardano-sl-rev for 0.13.1

---

appveyor.yml

This PR fixes the broken AppVeyor builds which are failing due to an expired signing certificate originally fixed in: https://github.com/input-output-hk/daedalus/commit/e27a4296babd481a90fd150d37fa38f06601a16b
---

Revert '[DEVOPS-1238] update the windows signing certificate and secret'

---

CHANGELOG.md
source/renderer/app/components/profile/terms-of-use/TermsOfUseForm.js
source/renderer/app/components/wallet/WalletCreateDialog.js
source/renderer/app/components/wallet/WalletRestoreDialog.js
source/renderer/app/components/wallet/WalletSendConfirmationDialog.js
source/renderer/app/components/wallet/WalletSendForm.js
source/renderer/app/components/wallet/ada-redemption/AdaRedemptionForm.js
source/renderer/app/components/wallet/paper-wallet-certificate/PrintDialog.js
source/renderer/app/components/wallet/paper-wallet-certificate/SecuringPasswordDialog.js
source/renderer/app/components/wallet/paper-wallet-certificate/VerificationDialog.js
source/renderer/app/components/wallet/receive/WalletReceive.js
source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
source/renderer/app/components/wallet/settings/ExportWalletToFileDialog.js

This PR fixes broken "Submit form on enter" feature which was caused by https://github.com/input-output-hk/daedalus/pull/1352
[Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1554205928036300)
We need to test all the forms which have submit-on-enter enabled such as Wallet Create/Restore forms, Send form, Generate address form on Receive screen (on wallet which has a spending password set), Wallet settings (changing password, setting a password, deleting wallet), Ada redemption form and also the whole Paper-Wallet-Certificate generation flow.
---

[DDW-628] Fix broken "Submit form on enter" feature

---

.github/pull_request_template.md
CHANGELOG.md

This PR updates our PR template.
[Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1554365783051100)
---

[DDW-603] Updated PR template

---

CHANGELOG.md
features/README.md
features/mnemonics-generation-and-validation.feature
features/tests/unit/steps/mnemonics-steps.js
package.json

This PR adds unit tests for generating and validating large amounts of mnemonics (to ensure that our crypto primitives work flawlessly)
**Note:** This PR targets #1378 since it's based on it … this can be changed as soon as the base branch has been merged into `develop`
`@unbound` tests run as long as you keep them running (never end except if an error occurs)
Example: `yarn test:unit:unbound --tags @mnemonics` generates and validates mnemonics as long as you keep it running (the number of executions is updated in the terminal)
You alwas have to specify `--tags X` for unbound tests since only one test case can be run endlessly (obviously) 💃 in this example the test case for generating and validating mnemonics was picked.
No QA required here.
---

[DDW-614] Add unit tests for mnemonics

---

CHANGELOG.md
source/renderer/app/components/wallet/WalletCreateDialog.js
source/renderer/app/components/wallet/WalletRestoreDialog.js
source/renderer/app/utils/ReactToolboxMobxForm.js
source/renderer/app/utils/waitForExist.js

In the Create and Restore wallet dialogs, sometimes the error messages may be not visible. This PR implements scrolling the error message into view.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1555947856001800)
---

[DDW-619] Scroll error message into view

---

default.nix
installers/nix/nix-installer.nix

This PR fixes a wrong date on Linux.
---
* [DEVOPS Slack thread](https://input-output-rnd.slack.com/archives/C7PJ29FME/p1557514403109300)
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1557514343148800)
---

[DDW-661] Linux Daedalus localtime fix

---

yarn2nix.nix

This PR misc a file that node-gyp leaves behind for incremental builds.
Nix doesn't support incremental builds, so it is of zero benefit and a side-effect of keeping that file, is that nix has to download ~1600 source tarballs (so keeping it greatly increases the time it takes to open a nix shell for the derivation).
As a result of this change both CI and nix-shell should speed up.
- Screenshot
---
---

Reduce the closure size of node-modules by ~1600 items

---

CHANGELOG.md
package.json

This PR adds a build script for storybook so that it can be built and deployed with [Netilfy](https://www.netlify.com/) so that the QA team can review and test our Daedalus components in the Chrome browser.
Netlify automatically builds PR previews, which means that each PR will be ready to be reviewed separately (in parallel to any other builds).
**Note:** I disabled the additional Netlify checks (see below) for any future deploys … so only this PR will have these 4 check statuses
---
- For any PR on Github you can now click on "Details" under "deploy/netlify" status and you will be directed to the storybook build for this PR. Here is the builds for this branch: https://deploy-preview-1391--daedalus-storybook.netlify.com
---

[DDW-662] Setup automatic storybook builds on netlify

---

CHANGELOG.md
installers/dhall/demo.dhall
source/renderer/app/config/urlsConfig.js

This PR changes the EKG port used in development from 8083 to 8085 in order to avoid port collision with a demo cluster node's API port. This collision caused `yarn dev` to fail on Linux, but it now works.

[DDW-666] Fixed EKG server port collision in development mode

---

CHANGELOG.md
features/generate-filename-with-timestamp.feature
features/tests/e2e/steps/wallets-steps.js
features/tests/unit/steps/generate-filename-with-timestamp-steps.js
source/common/utils/files.js
source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/InstructionsDialogContainer.js

This PR fixes broken "Navigate Wallet Tabs" e2e test and screenshots with .zip extension
---
---

[DDW-672] Fix broken Acceptance tests

---

CHANGELOG.md
source/renderer/app/components/wallet/receive/WalletReceive.scss

This PR fixes addresses not visible on Receive screen when Password is set for the wallet in minimized mode.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1559045891073400)
---

[DDW-678] Addresses are not visible on Receive screen

---

CHANGELOG.md
source/renderer/app/index.js
storybook/config.js
storybook/stories/support/DaedalusMenu.js
storybook/stories/support/DaedalusMenu.scss
storybook/stories/support/StoryDecorator.js
storybook/stories/support/StoryWrapper.js

This PR makes it possible to select theme and locale in Storybook.
---
---

[DDW-679] Enable theme and language change in Storybook

---

CHANGELOG.md
installers/Spec.hs
installers/dhall/cluster.type
installers/dhall/demo.dhall
installers/dhall/launcher.dhall
installers/dhall/mainnet.dhall
installers/dhall/staging.dhall
installers/dhall/testnet.dhall
launcher-config.yaml
source/main/cardano/config.js
source/main/config.js

This PR removes legacy references to the report server hosted by IOHK

[DDW 713] Remove legacy references to report server

---

CHANGELOG.md
package.json

This PR removes "0.13.2" release from the CHANGELOG and moves the entry from that section under "0.14.0" as the "0.13.2" release has been canceled.
In the scope of this task we also need to bump package.json version to 0.14.0.
---
- No QA required
---

[DDW-720] Remove 0.13.2 version from CHANGELOG

---

cardano-sl-src.json

This PR bumps the Cardano-SL revision to v3.0.2.
---
- No QA required
---

[DDW-721] Bump Cardano-SL revision

---

README.md
installers/common/MacInstaller.hs
release.nix

This PR fixes cardano-sl build issues on OSX Mojave by modifiying the daedalus-installer to obey $TMP.
**NO QA REQUIRED**
---

[DEVOPS] OSX Mojave build fix

---

.eslintrc
CHANGELOG.md
package.json
yarn.lock

This PR introduces a fix for dependency vulnerabilities.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1563196136364700)
---

[DDW-752] Fix dependency vulnerabilities

---

CHANGELOG.md
source/renderer/app/i18n/locales/en-US.json

This PR introduces app name typo fix.
---
---

[DDW-758] Fix app name typos

---

CHANGELOG.md
source/renderer/app/components/wallet/transactions/Transaction.js
source/renderer/app/components/wallet/transactions/Transaction.scss
storybook/stories/support/utils.js

This PR fixes the Transaction info, which currently shows the **To addresses:** in the same line.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1563373251409900)
---

[DDW-761] Fix 'To addresses' in the same line

---

CHANGELOG.md
source/renderer/app/components/loading/syncing-connecting/ReportIssue.js

This PR fixes broken 'Read the Article' button
---
---

[DDW-762] Fix broken 'Read the Article' button

---

CHANGELOG.md
source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/InstructionsDialogContainer.js

This PR fixes moment localized date format handling of the timestamp used on the paper wallet certificate.
---
---

[DDW-764] Fix timestamp date format handling

---

CHANGELOG.md
source/main/locales/en-US.json
source/main/locales/ja-JP.json
source/main/menus/osx.js
source/main/menus/win-linux.js

This PR implements a link to "Feature requests" in the app menu.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1563984168041900)
---

[DDW-777] Implement link to feature requests

---

CHANGELOG.md
source/renderer/app/components/loading/syncing-connecting/ReportIssue.js

This PR reverses the order of buttons on Having trouble connecting/syncing notification.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1564079013054200)
---

[DDW-785] Reverse the order of buttons on Having trouble connecting/syncing notification

---

source/renderer/app/components/loading/syncing-connecting/SyncingConnectingTitle.scss
source/renderer/app/themes/mixins/animations.scss
storybook/stories/WalletScreens.stories.js

This PR fixes a truncated dot in the connecting screen.
---
---

[DDW-780] Truncated third Loading Dot

---

CHANGELOG.md
source/main/utils/buildAppMenus.js

This PR fixes the focused button of the "Blank Screen fix" prompt on Windows.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1564352877070200)
---

[DDW-789] Fix focused button of the 'Blank Screen fix' prompt on Windows

---

appveyor.yml
cardano-sl-src.json
default.nix
installers/daedalus-installer.nix
lib.nix
release-build.nix
release.nix
scripts/build-cross-windows.sh
shell.nix
yarn2nix.nix

* HSM signing of daedalus
* New daedalus-bridge nix architecture
* nix builds of windows installers
* New testnet support
* Shelley staging environment support (not built by CI by default)
- Screenshot
---
---

[DDW-775] Cardano SL 3.0.3 integration

---

cardano-sl-src.json

This PR updates changelog typo in cardano-sl
- Screenshot
---
---

bump cardano-sl to include CHANGELOG fix

---

scripts/build-cross-windows.sh

disable signing with the test keys

---

cardano-sl-src.json

bump cardano-sl to latest 3.0.3

---

CHANGELOG.md
source/renderer/app/components/status/DaedalusDiagnostics.js

This PR removes "Realtime statistics monitor" link in Testnet builds.
---
---

[DDW-815] Remove "Realtime statistics monitor" link in Testnet builds

---

CHANGELOG.md
source/renderer/app/components/status/BlockConsolidationStatus.js
source/renderer/app/components/status/BlockConsolidationStatus.scss
source/renderer/app/components/status/DaedalusDiagnostics.js
source/renderer/app/components/status/DaedalusDiagnostics.scss
source/renderer/app/i18n/locales/defaultMessages.json

This PR fixes styling inconsistencies in the  "Daedalus Diagnostics" and "Block consolidation status" close buttons.
---
---

[DDW-812] Fix application dialog close button colour

---

CHANGELOG.md
source/renderer/app/containers/Root.js
source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js

This PR fixing "copy-state-path" notification z-index issue on "Daedalus Diagnostics" screen which was broken by: https://github.com/input-output-hk/daedalus/pull/1517.
In the scope of the same PR, a minor routing issue which allowed the Main UI to be shown "underneath" the "Block consolidation status" dialog while Daedalus is still syncing has been fixed.
---
---

[DDW-812] Fix notification z-index issue on Daedalus Diagnostics screen

---

CHANGELOG.md
source/renderer/app/components/wallet/utxo/WalletUtxo.js
source/renderer/app/components/wallet/utxo/WalletUtxo.scss
source/renderer/app/containers/wallet/WalletUtxoPage.js
source/renderer/app/i18n/locales/de-DE.json
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/i18n/locales/en-US.json
source/renderer/app/i18n/locales/hr-HR.json
source/renderer/app/i18n/locales/ja-JP.json
source/renderer/app/i18n/locales/ko-KR.json
source/renderer/app/i18n/locales/zh-CN.json
storybook/stories/WalletScreens-Utxo.stories.js

This PR adds a 'Find out more' link to the 'Wallet UTXO distribution' screen which opens a Support portal article.
---
```
Link text:
- EN: Find out more
- JP: もっと詳しく
Support portal article links:
- EN: https://iohk.zendesk.com/hc/en-us/articles/360034118013
- JP: https://iohk.zendesk.com/hc/ja/articles/360034118013
```
---

[DDW-783] Link to support portal article explaining UTXO distribution

---

bors.toml
cardano-sl-src.json
release-build.nix

fixes size of linux installer

---

CHANGELOG.md
source/renderer/app/themes/overrides/ModalOverrides.scss

This PR fixes a problem within Storybook where the dialog content would spill out of its wrapper in the latest version of Chrome (v76+).
---
---

[DDW-830] Fix dialog content issues in the latest version of Chrome

---

CHANGELOG.md
source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.js
source/renderer/app/components/staking/delegation-center/DonutRing.js
source/renderer/app/components/staking/delegation-center/helpers.js
source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
source/renderer/app/i18n/locales/defaultMessages.json
storybook/stories/Staking-DelegationCenter.stories.js
storybook/stories/Staking.stories.js

This PR fix delegation section issues.
_Delegation Centre header percentage rounding_
_Delegation setup dialog with 1ADA selected_
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1566471885250400)
---

[DDW-839] Delegation setup improvements

---

CHANGELOG.md
source/renderer/app/App.js
source/renderer/app/stores/NetworkStatusStore.js

This PR fixed theme blinking issue on overlay.
[YouTrack Ticket](https://iohk.myjetbrains.com/youtrack/issue/DDW-870)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1567510947021100)

[DDW-870]: Overlay screens displayed on default theme rather than current one for a second

---

CHANGELOG.md
features/send-money-to-receiver.feature
features/tests/e2e/steps/select-language-steps.js
features/tests/e2e/steps/settings-steps.js
package.json
source/renderer/app/components/wallet/WalletSendForm.js
source/renderer/app/i18n/locales/defaultMessages.json
yarn.lock

This PR Introduces latest develop merged into v2-integration branch.
Commit log:
`commit 8c5ba05845946dc8b7d0d18441489defb0567240 (HEAD -> v2-integration-with-latest-develop, origin/v2-integration-with-latest-develop, v2-integration)`
Develop branch HEAD: `dfa7ab91568a4b1f05febe03648bd058fcb7035a`
---
_No testing needed_
---

V2 integration with latest develop

---

CHANGELOG.md
source/renderer/app/themes/daedalus/yellow.js

This PR fixes wrong text color on "Newsfeed" sidebar messages on Yellow theme.
- Before
- After
---
- No QA required
---

[DDW-901] Fix yellow theme newsfeed sidebar message text color

---

CHANGELOG.md
source/renderer/app/components/notifications/AutomaticUpdateNotification.js
source/renderer/app/config/urlsConfig.js
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/i18n/locales/en-US.json
source/renderer/app/i18n/locales/ja-JP.json

This PR updates newsfeed JSON and verification files hosting URLs.
This PR also includes the removal of 'v' from Daedalus version on Automatic update overlay.
---
---

[DDW-911] Update newsfeed JSON and verification files hosting URLs

---

.flowconfig
.gitignore
CHANGELOG.md
README.md
package.json
utils/js-launcher/README.md
utils/js-launcher/index.js
utils/js-launcher/launcher-config-base.yaml
utils/js-launcher/lib/rimraf.js
utils/js-launcher/lib/x509.js
yarn.lock

This PR adds utility scripts to allow launching Daedalus in frontend only mode, without any nix dependencies.
No QA required. Its utility we can refine as required.

[DDW-952] Allow nix-free frontend only mode

---

installers/cardano-configuration.yaml

This PR bumps staging `applicationVersion` to `27`.
- Screenshot
---
---

[DEVOPS] Staging applicationVersion bump -> 27

---

CHANGELOG.md
storybook/webpack.config.js

This PR improves build performance of storybook in development (not CI, since the auto DLL is not useful in CI).
---
---

[DDW-981] Speedup storybook builds in development

---

CHANGELOG.md
features/send-money-to-receiver.feature
package.json
source/renderer/app/api/api.js
source/renderer/app/components/wallet/WalletSendForm.js
source/renderer/app/stores/WalletsStore.js
yarn.lock

This PR introduces new address validation way using `cardano-js` npm package.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1571659811189300)
---

[DDW-968] Introduce address validator

---

CHANGELOG.md
tests/nodes/e2e/steps/helpers.js
tests/wallets/e2e/steps/wallets.js

This PR Fixes E2E broken 'Delete Wallet' test.
---
---

[DDW-1016] Fix E2E broken 'Delete Wallet' test

---

CHANGELOG.md
source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStep3Dialog.js

This fixes an issue with missing Japanese translation for recovery phrase verification:
- Screenshot
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1572324882248100)
---

[DDW-1022] Fix missing Japanese translation for recovery phrase verification

---

installers/cardano-configuration.yaml

This PR bumps Daedalus `applicationVersion`:
- staging -> 28
- testnet -> 5
---

[DEVOPS] Bump Daedalus application versions (staging -> 28, testnet -> 5)

---

.buildkite/pipeline.yml

This PR introduces:
* Changes OSX to build on Daedalus Buildkite queue
* Backports signing fixes
---

[DEVOPS] Enable macOS builds signing

---

.buildkite/pipeline.yml

Green CI path by removing failing check-hydra script

Remove check-hydra script from CI

---

CHANGELOG.md
source/renderer/app/stores/WalletsStore.js

This PR introduces a fix for paper wallet certificate restoration
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1573151719378500)
---

[DDW-1055] Fix paper wallet certificate restoration

---

CHANGELOG.md
features/node-update-notification.feature
source/renderer/app/App.js
source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
source/renderer/app/containers/loading/LoadingPage.js
source/renderer/app/containers/loading/SyncingConnectingPage.js
source/renderer/app/stores/NodeUpdateStore.js
storybook/stories/Loading-SyncingConnecting.stories.js

This PR blocks manual update notification for Incentivized Testnet
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1573208299382200)
---

[DDW-1044] Disable manual update notification for Incentivized Testnet

---

installers/cardano-configuration.yaml
package.json

This PR bumps Daedalus `applicationVersion` for the upcoming hotfix release.
---
---

[DEVOPS] Daedalus applicationVersion: bump all environments

---

CHANGELOG.md
source/renderer/app/api/utils/externalRequest.js

[DDW-1056] Newsfeed content loading issue

---

README.md
nix/sources.json

This PR updates cardano-wallet to revision: v2019-11-07.
---
---

[DDW-1057] Update cardano-wallet revision

---

CHANGELOG.md
yarn.lock

This PR reverts yarn.lock changes which fixes Linux and Windows builds.
---
---

[DDW-983] Revert yarn.lock changes

---

CHANGELOG.md
installers/cardano-configuration.yaml
package.json
source/renderer/app/api/utils/externalRequest.js

This PR merges `master` code into `develop` branch.

Merge master into develop branch

---

default.nix

This PR fixes wrong icons on Linux SelfNode, QA and Nightly Testnet networks builds.
---
---

[DDW-979] Fix icons for SelfNode, QA, and Nightly Testnet networks builds

---

source/common/types/environment.types.js
source/main/environment.js
source/renderer/app/components/status/DaedalusDiagnostics.js
source/renderer/app/components/wallet/transactions/Transaction.js
source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
source/renderer/app/config/urlsConfig.js
source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
source/renderer/app/containers/wallet/WalletSummaryPage.js
source/renderer/app/containers/wallet/WalletTransactionsPage.js
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/utils/network.js
storybook/stories/WalletScreens.stories.js
storybook/stories/WalletTransactionsList.stories.js

This PR implements correct Cardano Explorer links for Incentivized Testnet network.
---
---

[DDW-1051] Update Cardano Explorer links

---

CHANGELOG.md
source/renderer/app/components/layout/TopBar.js
source/renderer/app/components/notifications/LegacyNotification.js
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/i18n/locales/en-US.json
source/renderer/app/i18n/locales/ja-JP.json

This PR introduces changes that hide legacy wallet notification during wallet restoration / syncing.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1573468284414100)
---

[DDW-1065] Hide legacy wallet notification during wallet restoration/syncing

---

package.json
source/renderer/app/components/notifications/LegacyNotification.js
source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.scss
source/renderer/app/components/staking/delegation-center/WalletRow.scss
source/renderer/app/components/staking/rewards/StakingRewards.scss
source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
source/renderer/app/i18n/locales/defaultMessages.json

This PR changes the link colors for incentivised testnet links across the app.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1573488892437700)
---

[DDW-1054] Make links for incentivised testnet theme consistent color

---

package.json
source/main/cardano/CardanoNode.js
source/main/cardano/CardanoWalletLauncher.js
source/main/cardano/setupCardanoNodeMode.js
source/main/config.js
yarn.lock

This PR makes sure Daedalus log packing includes cardano-node log.
Implementation summary:
- Rotate logs with the use of rotating-file-stream and stdio pipe of child process
- Move node logs into pub directory
- Update ALLOWED_NODE_LOGS regex
---
---

[DDW-1069] Rotating logs

---

CHANGELOG.md
source/renderer/app/components/sidebar/SidebarCategory.scss
source/renderer/app/components/wallet/settings/DeleteWalletButton.scss
source/renderer/app/themes/daedalus/cardano.js
source/renderer/app/themes/daedalus/dark-blue.js
source/renderer/app/themes/daedalus/dark-cardano.js
source/renderer/app/themes/daedalus/incentivized-testnet.js
source/renderer/app/themes/daedalus/light-blue.js

This PR fixes remaining theming issues:
- Delete button text vertical centering
- Disabled dialog buttons opacity
- Network info label animation
---
---

[DDW-1071] Incentivized Testnet Theme Fixes

---

nix/sources.json

cardano-wallet: update to release 2019-11-14

---

CHANGELOG.md
package.json

This PR bumps Daedalus version to `1.1.0-ITN0`.
---
---

[DDW-1084] Bump Daedalus version to 1.1.0-ITN0

---

shell.nix

This PR fixes devops shell to only have niv as a dependency.
---
---

[DEVOPS] Remove wallet and jormungandr binaries from devops shell

---

CHANGELOG.md
nix/launcher-config.nix
nix/sources.json
source/renderer/app/config/timingConfig.js

This PR bumps sync threshold to 10 mins as well as the sync report-issue threshold.
The same PR bumps the cardano-wallet version to the latest available - 2019.11.18.
---
---

[DDW-1085] Bump sync report issue timer threshold to 10 mins

---

CHANGELOG.md
source/renderer/app/components/status/DaedalusDiagnostics.scss

This PR Introduces a fix for a yellow frame around "Diagnostics" dialog.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1574090400072100)
---

[DDW-992] Yellow frame displayed around the Diagnostics Dialog

---

CHANGELOG.md
source/renderer/app/api/api.js

This PR fixed incorrect wallet password change issue
[YouTrack Ticket](https://iohk.myjetbrains.com/youtrack/issue/DDW-1086)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1574206723076400)

[DDW-1086]: Fix incorrect wallet password change issue

---

CHANGELOG.md
tests/navigation/e2e/features/navigate-general-settings-menu.feature
tests/settings/e2e/features/select-language.feature
tests/settings/e2e/steps/general-settings.js

This PR fixes the broken select language tests.
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1574206481075600)
---

[DDW-1017] Fix Select Language Tests

---

CHANGELOG.md
gulpfile.js
source/renderer/app/themes/utils/constants.js
source/renderer/app/themes/utils/createTheme.js

This PR fixes the `themes:check:createTheme` script and updates the `createTheme` object with the latest CSS variables.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1574300887098500)
---

[DDW-1088] Fix themes:check:createTheme Script

---

CHANGELOG.md

This PR merges the latest `develop` into `v2-integration` branch.

Merge latest develop into v2 integration

---

CHANGELOG.md
source/renderer/app/components/staking/delegation-center/DelegationCenter.js
source/renderer/app/components/staking/delegation-center/DelegationCenterBody.js
source/renderer/app/components/staking/delegation-center/WalletRow.js
source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.js
source/renderer/app/components/staking/stake-pools/StakePools.js
source/renderer/app/components/staking/stake-pools/StakePoolsList.js
source/renderer/app/containers/staking/DelegationCenterPage.js
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/stores/StakingStore.js
source/renderer/app/utils/colors.js
storybook/stories/staking/DelegationCenter.stories.js

This PR adjusts the Stake pool logic for ranking color to account for the total number of stake pools.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1574430735119400)
---

[DDW-1081] Adjust Stake pool logic for ranking color

---

CHANGELOG.md
source/main/locales/en-US.json
source/main/locales/ja-JP.json

This PR adds link icon to the 'Safety Tips' menu item.
---
---

[DDW-1025] Adds link icon to the 'Safety Tips' menu item

---

CHANGELOG.md
source/renderer/app/containers/TopBarContainer.js

This PR fixed missing 'hamburger' icon on wallets menu while there are only legacy wallets in the UI.
---
---

[DDW-1106] Missing hamburger icon

---

CHANGELOG.md
package.json
source/renderer/app/components/wallet/WalletSendForm.js
source/renderer/app/containers/wallet/WalletSendPage.js
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/utils/formatters.js
storybook/stories/wallets/send/WalletSend.stories.js
yarn.lock

This PR integrates the configurable number formats with the improved `NumericInput` in react-polymorph.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1575405184257000)
---

[DDW-1018] Configure numeric input number formats

---

CHANGELOG.md
package.json
source/renderer/app/themes/overrides/CheckboxOverrides.scss
source/renderer/app/themes/overrides/index.js
yarn.lock

This PR replaces the checkbox theme overrides with the new them var introduced in react-polymorph@0.9.0-rc.25
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1575626733271200)
---

[DDW-1031] Add theme var for Checkbox icon color

---

CHANGELOG.md
nix/sources.json
utils/jormungandr/selfnode/genesis.yaml

This PR updates `cardano-wallet` to latest master revision `d45719527cd6accf515486a154da417f52d5ff9f`.
---
---

[DDW-1117] Update cardano-wallet to latest master

---

CHANGELOG.md
source/renderer/app/stores/SidebarStore.js

This PR enables "Delegation" UI in Daedalus builds.
---
---

[DDW-1123] Enable Delegation UI in Daedalus builds

---

CHANGELOG.md
source/renderer/app/api/api.js
source/renderer/app/api/staking/requests/getDelegationFee.js
source/renderer/app/api/staking/types.js
source/renderer/app/containers/staking/DelegationCenterPage.js
source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
source/renderer/app/stores/StakingStore.js

This PR introduces stake pool join/quit fee estimation API V2 endpoint.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1575988541339500)
---

[DDW-1116] Integrate stake pool join/quit fee estimation API endpoint

---

CHANGELOG.md
source/renderer/app/api/api.js

This PR updated stake pool ranking logic
[YouTrack Ticket](https://iohk.myjetbrains.com/youtrack/issue/DDW-1115)

[DDW-1115]: Update stake pool ranking logic

---

CHANGELOG.md
package.json
yarn.lock

This PR updated `serialize-javascript` package dependency
[YouTrack Ticket](https://iohk.myjetbrains.com/youtrack/issue/DDW-1120)
https://github.com/input-output-hk/daedalus/network/alert/yarn.lock/serialize-javascript/open

[DDW-1120]: Update serialize-javascript dependency

---

CHANGELOG.md
source/renderer/app/components/layout/TopBar.js
source/renderer/app/components/notifications/LegacyNotification.js
source/renderer/app/containers/TopBarContainer.js
source/renderer/app/stores/WalletsStore.js
storybook/stories/_support/StoryLayout.js

This PR fixes an issue with "Balance" wallet notification which was not offering an option to create a "Rewards" wallet in case none were available.
---
---

[DDW-1126] Fix legacy wallet migration notification

---

CHANGELOG.md
nix/sources.json
utils/jormungandr/selfnode/genesis.yaml

This PR updates `cardano-wallet` to latest master revision `555b5e820c4d9598602acfa75ec7bb23e2a3aa7a `.
---
---

[DDW-1127] Updates cardano-wallet to latest master

---

CHANGELOG.md
package.json
yarn.lock

This PR updated package dependencies to prevent vulnerability issues
[YouTrack Ticket](https://iohk.myjetbrains.com/youtrack/issue/DDW-1133)

[DDW-1133]: Update package dependencies

---

CHANGELOG.md
source/renderer/app/components/splash/Network.scss

This PR improves font rendering on "Network" splash screen.
---
---

[DDW-1134] Improve font rendering on Network splash screen

---

CHANGELOG.md
package.json
source/renderer/app/components/loading/syncing-connecting/SyncingConnectingTitle.scss
yarn.lock

This fixes an error where the global listeners
have been toggling the options although they
were not in the DOM anymore (Dropdown)
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1576242007403900)
---

[DDW-1128] React-polymorph Error is showed after app resizing

---

CHANGELOG.md
source/renderer/app/api/api.js
source/renderer/app/api/staking/types.js
source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
source/renderer/app/config/stakingStakePools.dummy.json
source/renderer/app/domains/StakePool.js
source/renderer/app/i18n/locales/defaultMessages.json

This PR adds profit margin & costs to stake pool details.
- Screenshot
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1576251176001800)
---

[DDW-1136] - Add cost and profit margin to stake pool details

---

CHANGELOG.md
nix/sources.json
source/renderer/app/api/api.js
source/renderer/app/stores/StakingStore.js
utils/jormungandr/selfnode/genesis.yaml

This PR updates `cardano-wallet` to `2019.12.13` version which includes `Jormungandr`version  `0.8.1`.
---
---

[DDW-1138] Update cardano-wallet to latest release

---

CHANGELOG.md
nix/sources.json
source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsIntroDialog.js
source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.js

This PR bumps `cardano-wallet` revision to `v2019-12-16`.
This PR also removes "Learn more" links from "Rewards" screen and "Delegation" wizard.
English:
Japanese:
---
---

Cardano wallet version bump

---

CHANGELOG.md
source/renderer/app/components/splash/Network.scss

This PR fixes network screen responsiveness on all screens.
- Screenshot
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1576853936013000)
---

[DDW-1155] - Network info screen should be responsive

---

CHANGELOG.md
nix/launcher-config.nix
nix/sources.json
source/renderer/app/components/loading/syncing-connecting/ReportIssue.js
source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
source/renderer/app/components/splash/Network.scss
source/renderer/app/containers/loading/SyncingConnectingPage.js
source/renderer/app/i18n/locales/de-DE.json
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/i18n/locales/en-US.json
source/renderer/app/i18n/locales/hr-HR.json
source/renderer/app/i18n/locales/ja-JP.json
source/renderer/app/i18n/locales/ko-KR.json
source/renderer/app/i18n/locales/zh-CN.json
source/renderer/app/stores/NetworkStatusStore.js
storybook/stories/nodes/syncing/SyncingConnecting.stories.js

This PR introduces changed ITN "Having trouble syncing" URL to point to one specific to TestNet
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1576835240005800)
**NOTES:**
_This is only the case for ITN when there is SYNC problem, otherwise, https://iohk.zendesk.com/hc/en-us/articles/360011536933 article should be opened
To simulate syncing type command **`daedalus.stores.networkStatus._setSyncing()`** in `devTools -> console` and wait 10 minutes for syncing issue notification_
---

[DDW-1157] Incent TestNet - Change "Having trouble syncing" URL to point to one specific to TestNet

---

CHANGELOG.md
package.json

Prepare 2.1.0-ITN1 release

---

CHANGELOG.md
nix/sources.json
source/renderer/app/api/api.js
source/renderer/app/api/transactions/requests/deleteLegacyTransaction.js
source/renderer/app/api/transactions/requests/getLegacyWalletTransactionHistory.js
source/renderer/app/api/utils/index.js
source/renderer/app/api/wallets/requests/deleteLegacyWallet.js
source/renderer/app/api/wallets/requests/transferFunds.js
source/renderer/app/api/wallets/requests/transferFundsCalculateFee.js

This PR resolves issues caused by duplicate wallet IDs when you restore Balance and Rewards Yoroi wallet from the same recovery phrase.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1577159215030300)
---

[DDW-1160] Add wallet type to route path

---

CHANGELOG.md
nix/sources.json
source/renderer/app/api/utils/patchAdaApi.js
source/renderer/app/domains/News.js
utils/jormungandr/selfnode/genesis.yaml

This PR bumps the `cardano-wallet` revision to release https://github.com/input-output-hk/cardano-wallet/releases/tag/v2020-01-27: `23e12d1a26d282bf4acf9d8df3de9803e7e9baf5 ` which includes Jormungandr 0.8.7.
---
---

[DDW-1190] Bump cardano-wallet revision

---

CHANGELOG.md
nix/sources.json
source/renderer/app/api/utils/patchAdaApi.js
source/renderer/app/domains/News.js
utils/jormungandr/selfnode/genesis.yaml

This PR merges the latest `release/2.1.0-ITN1` into `v2-integration` branch with the only change being https://github.com/input-output-hk/daedalus/pull/1828

Merge release/2.1.0-ITN1 into v2-integration

---

CHANGELOG.md
tests/stake-pools/e2e/features/stake-pools.feature

This PR introduces a fix for broken acceptance tests.
Tests got broken by an incorrect merge of v2-integration changes into https://github.com/input-output-hk/daedalus/pull/1816
---
---

[DDW-1191] Fix broken acceptance tests

---

CHANGELOG.md
nix/sources.json

This PR bumps the `cardano-wallet` revision to `23e12d1a26d282bf4acf9d8df3de9803e7e9baf5 ` which includes Jormungandr 0.8.9.
---
---

[DDW-1192] Bump cardano-wallet revision

---

CHANGELOG.md
source/renderer/app/components/loading/syncing-connecting/ReportIssue.scss

This PR fixes download logs link underline color on all themes.
Ticket: https://iohk.myjetbrains.com/youtrack/issue/DDW-1187
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1580404883078700)
---

[DDW-1187] - Download logs link underline color fix

---

CHANGELOG.md
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/i18n/locales/en-US.json
source/renderer/app/i18n/locales/ja-JP.json

This PR renames "Profit margin" into "Pool margin" on the stake pool tooltip.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1580989865006700)
---

[DDW-1195] Stake pool tooltip update

---

.github/pull_request_template.md
CHANGELOG.md

This PR improves GitHub PR review template (checklist).
---
- No QA required
---

[DDW-1196] Improve PR review checklist

---

CHANGELOG.md
nix/sources.json

This PR updates `cardano-wallet` dependency to `edc42a9c9a79dc3d6e76363f9c03e8e6009de993`.
---

[DDW-1201] bump cardano-wallet dependency

---

CHANGELOG.md
default.nix
nix/sources.json

2.1.0 wallet bump

---

nix/sources.json

2.1.0 wallet 0.8.9

---

CHANGELOG.md
storybook/stories/staking/DelegationCenter.stories.js
storybook/stories/staking/Staking.stories.js

This PR introduces a fix for delegation countdown storybook story.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1582544951003400)
_Storybook countdown testing:_
---

[DDW-1175] Storybook - Decentralization Countdown

---

CHANGELOG.md
default.nix
nix/jormungandr-bridge.nix
nix/sources.json

This PR merges the latest `release/2.2.0-ITN1` into `v2-integration` branch

Merge release/2.2.0-ITN1 into v2-integration

---

CHANGELOG.md
package.json

This PR bumps Daedalus version to `2.3.0-ITN1` and prepares the CHANGELOG for the release.
---
---

[DDW-1221] Bump Daedalus version to 2.3.0-ITN1

---

CHANGELOG.md
source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
source/renderer/app/components/widgets/LoadingSpinner.scss

This PR removes Daedalus wallet spinner click and mark functionality
- Screenshot
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/G7ZA8AFGD/p1583936959009500)
---

[DDW-1202] Daedalus wallet restoration spinner improvement

---

package.json
shell.nix
yarn.lock
yarn2nix.nix

This PR updated node and yarn package versions.
[YouTrack Ticket](https://iohk.myjetbrains.com/youtrack/issue/DDW-854)

[DDW-854] Update node and yarn

---

CHANGELOG.md
nix/sources.json

This PR updates `cardano-wallet` to the `v2020-03-16`: `8316bffdd05596e8830da9129f3a3907c6fba684 ` which introduces API fixes and uses Jormungandr `0.8.14`.
---
---

[DDW-1230] Bump cardano wallet revision

---

CHANGELOG.md
default.nix
installer-clusters.cfg
installers/Installer.hs
installers/common/Config.hs
installers/common/MacInstaller.hs
installers/common/Types.hs
installers/common/Util.hs
installers/common/WindowsInstaller.hs
nix/cardano-bridge.nix
nix/launcher-config.nix
nix/sources.json
release.nix
scripts/build-cross-windows.sh
scripts/build-installer-nix.sh
scripts/build-installer-unix.sh

This PR adds support for building both `jormungandr` (Rust) and `cardano-node` (Haskell) installers.
---
---

[DDW-27] Update installers to bundle the new services as determined by the cardano-wallet dependency

---

nix/launcher-config.nix
source/main/cardano/CardanoNode.js
source/main/cardano/CardanoWalletLauncher.js
source/main/cardano/utils.js
source/main/utils/mainErrorHandler.js

This PR implements start-time injection into genesis file for selfnode cluster
---
---

[DDW-65] Inject start-time into genesis file for selfnode cluster

---

nix/launcher-config.nix
source/renderer/app/api/api.js

Extra bins launcher config

---

default.nix
installers/common/MacInstaller.hs
installers/common/WindowsInstaller.hs
nix/launcher-config.nix
scripts/build-installer-unix.sh
shell.nix

This PR refactors the launcher config.
---
---

[DDW-60] Refactor launcher config

---

CHANGELOG.md
source/renderer/app/api/api.js

This PR enables wallet name editing in "Wallet settings"
---
---

[DDW-49] Enable wallet name editing in "Wallet settings"

---

CHANGELOG.md
source/renderer/app/api/api.js

This PR enables Wallet UTxO distribution for Byron wallets
---
---

[DDW-51] Enable Wallet UTxO distribution for Byron wallets

---

nix/sources.json

[DEVOPS] Update cardano-sl for latest export-wallets

---

nix/launcher-config.nix

This PR fixes various build and migration issues.
---
---

Fix migration issues

---

CHANGELOG.md
source/renderer/app/config/timingConfig.js

This PR reduces connection timeout limit for byron rebook builds to 5 minutes.
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1585557507073400)
---

[DDW-91] Reduce connection timeout limit for Byron Reboot builds

---

CHANGELOG.md
source/renderer/app/api/news/requests/getNews.js
source/renderer/app/api/news/requests/getNewsHash.js

This PR configures Daedalus Flight to use it's own newsfeed.
---
---

[DDW-89] Adds Daedalus Flight newsfeed

---

CHANGELOG.md
source/main/locales/en-US.json
source/main/locales/ja-JP.json

This PR updated text copy of "Automatic wallet migration" warning dialog
[Jira Ticket](https://jira.iohk.io/browse/DDW-84)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1585579886079000)

[DDW-84] Update copy of "Automatic wallet migration" warning dialog

---

nix/cardano-bridge.nix

fix node-version for cardano-wallet

---

default.nix
installers/common/Types.hs

This PR fixes "mainnet_flight" network name handling on Linux builds.
---
---

[DEVOPS] Fix Linux mainnet_flight name

---

default.nix
shell.nix

This PR includes:
* defaults to false (no installers will use overridden node version)
* node version can be updated with `niv update cardano-node -b <branch>`
* to test: `nix-shell --argstr cluster mainnet_flight --arg useLocalNode true`
---
---

[DEVOPS] Add useLocalNode flag for development testing

---

default.nix
installers/common/MacInstaller.hs
nix/launcher-config.nix
release-build.nix
source/renderer/app/components/splash/SplashNetworkFlight.js

This PR merges `release/1.0.0-FC1`  into `develop`  branch.

Merge release/1.0.0-FC1 into develop

---

installers/common/MacInstaller.hs
scripts/build-installer-unix.sh

This PR fixes ITN selfnode
- Screenshot
---
---

[DEVOPS] Fix OSX installer to contain genesis/secrets for itn_selfnode build

---

CHANGELOG.md
source/main/cardano/CardanoNode.js
source/main/cardano/CardanoWalletLauncher.js
source/main/preload.js

This PR fixes the `EPERM` errors thrown in the console upon changing wallet name on the "Wallet Settings" screen.
---
---

[DDW-116] Fix electron-storage implementation

---

CHANGELOG.md
source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js

This PR fixes wallet restoration validation which previously allowed to submit 1st step of restoration dialog without selecting Daedalus wallet type (12-words vs 27-words).
---
---

[DDW-114] Fix restoration validation

---

nix/sources.json

[SRE] cardano-wallet: bump to 563c28f05c1f38c9741277f480a8983d37b05a68

---

nix/sources.json

This PR merges `release/1.0.0-FC2` into `develop` branch.

Merge release/1.0.0-FC2 into develop

---

CHANGELOG.md
README.md

This PR updates the README file: https://github.com/input-output-hk/daedalus/blob/chore/ddw-92-update-readme/README.md.

[DDW-92] Update README

---

nix/sources.json

This PR bumps `cardano-wallet` to the revision which contains `cardano-node` 1.10.0.
- Screenshot
---
---

[SRE] Bump cardano-wallet: supports cardano-node 1.10.0

---

CHANGELOG.md
nix/sources.json

This PR bumps `cardano-wallet` dependency to fix the fee estimation issue.
- Screenshot
---
---

Bump cardano-wallet dependency to `745aaad67004855a84c51e400c6fa1d10edb910`

---

CHANGELOG.md
nix/sources.json

This PR merges `release/1.0.0-FC3` into `develop` branch.

Merge release/1.0.0-FC3 into develop

---

CHANGELOG.md
source/renderer/app/components/splash/SplashNetworkFlight.js

This PR restores the 'Automatic wallet migration' paragraph on the Daedalus Flight 'Splash' screen.
---
---

[DDW-159] Restore the "wallet migration" paragraph on the Daedalus Flight "Splash" screen

---

CHANGELOG.md
nix/sources.json

This PR depends on https://github.com/input-output-hk/cardano-shell/pull/361.
---
---

[DDW-155] Persist "Blank screen fix" / "--safe-mode" flag between Daedalus restarts

---

CHANGELOG.md
default.nix
installers/common/Types.hs
scripts/build-cross-windows.sh

This PR updates the Daedalus installer file names so that they contain only Daedalus version, cluster and the build number: 
- Mac: `daedalus-1.0.0-FC4-mainnet_flight-12442.pkg`
- Linux: `daedalus-1.0.0-FC4-mainnet_flight-12442.bin`
- Windows: `daedalus-1.0.0-FC4-mainnet_flight-12442.exe`
---
---

[DDW-157] Update Daedalus installer file name

---

CHANGELOG.md
source/renderer/app/stores/WalletMigrationStore.js

This PR orders exported wallets shown on the "Wallet Import" 2nd step by ID instead of the name.
---
---

[DDW-172] Order exported wallets by ID

---

CHANGELOG.md
source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.js
source/renderer/app/containers/wallet/dialogs/WalletImportDialogContainer.js
source/renderer/app/stores/WalletMigrationStore.js

This PR improves "Wallet import" dialog state handling such that the dialog is closed and reset in case of switching to "Connecting" screen or display of red error "NTP" or "Low diskspace" overlays.
---
---

[DDW-175] Improve wallet import dialog state handling

---

CHANGELOG.md
installers/common/WindowsInstaller.hs

This PR prevents Daedalus installation on Windows OS older than version 8.1 (based on https://nsis.sourceforge.io/Get_Windows_version).
---
---

[SRE-86] Block installing on anything older than Windows 8.1

---

CHANGELOG.md
source/renderer/app/components/loading/syncing-connecting/LogosDisplay.scss
source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.scss
source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.scss
source/renderer/app/components/notifications/LegacyNotification.scss
source/renderer/app/components/staking/delegation-center/UndelegateConfirmationDialog.scss
source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.scss
source/renderer/app/components/staking/epochs/StakingEpochs.scss
source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
source/renderer/app/components/status/DaedalusDiagnostics.js
source/renderer/app/stores/NodeUpdateStore.js

This PR fixes issues with Daedalus logo animation display on the "Loading" screens on macOS platform.
---
---

[DDW-177] Fixed Daedalus logo animation display on macOS

---

CHANGELOG.md
package.json

This PR bumps Daedalus version for the upcoming Daedalus Flight 1.1.0-FC1 release.
---
---

[DDW-170] Bump Daedalus version

---

CHANGELOG.md
package.json

This PR bumps Daedalus version for the 1.1.0 release.
---
---

[DDW-192] Bump Daedalus version

---

CHANGELOG.md
source/renderer/app/api/api.js
source/renderer/app/api/staking/requests/getDelegationFee.js
source/renderer/app/api/staking/types.js
source/renderer/app/components/sidebar/Sidebar.js
source/renderer/app/routes-config.js

This PR updates delegation fee calculation.
---
---

[DDW-247] Update transaction fee estimation Api endpoint implementation

---

CHANGELOG.md
source/renderer/app/components/hardware-wallet/settings/ConnectHardwareWallet.scss
source/renderer/app/themes/daedalus/cardano.js
source/renderer/app/themes/daedalus/dark-blue.js
source/renderer/app/themes/daedalus/dark-cardano.js
source/renderer/app/themes/daedalus/flight-candidate.js
source/renderer/app/themes/daedalus/incentivized-testnet.js
source/renderer/app/themes/daedalus/light-blue.js
source/renderer/app/themes/daedalus/white.js
source/renderer/app/themes/daedalus/yellow.js

This PR adds different theme styling for hardware wallet screens.
- Screenshot
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1590593189057400)
---

[DDW-250] - Improve hardware wallets theming

---

source/renderer/app/config/timingConfig.js

This PR merges `release/2.4.0-ITN1` into `develop` branch.

Merge release/2.4.0-ITN1 into develop

---

CHANGELOG.md
nix/sources.json

This PR bumps cardano-wallet revision to the tip of the latest master branch.
---
---

Bump cardano-wallet revision

---

CHANGELOG.md
source/renderer/app/Routes.js

This PR fixed landing page rendering issue by configuring wallets root redirection config
[Jira Ticket](https://jira.iohk.io/browse/DDW-276)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1591814114034700)
---

[DDW-276]: Fix wallets root redirection route config

---

nix/sources.json

Adds support for checking and using reward balances
- Screenshot
---
---

bump wallet/node versions

---

nix/sources.json

cardano-shell: switch from branch to master

---

CHANGELOG.md
source/renderer/app/stores/SidebarStore.js

This PR removes the ITN rewards icon from the sidebar in production builds.
---
---

Remove ITN rewards icon from production builds

---

CHANGELOG.md
source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.js
source/renderer/app/components/widgets/Dialog.js
source/renderer/app/config/cryptoConfig.js

This PR updates "ITN rewards redemption" wizard to ask for 15-word recovery phrase.
---
---

[DDW-310] Update ITN rewards redemption to ask for 15-word recovery phrase

---

CHANGELOG.md
source/renderer/app/components/static/About.js

This PR fixes `cardano-wallet` info shown on the "About" screen.
---
---

[DDW-313] Update cardano-wallet info shown on the "About" screen

---

nix/sources.json

This PR is needed to get past shelley hard fork tomorrow.
- Screenshot
---
---

testnet: fix shelley genesis

---

CHANGELOG.md
source/renderer/app/api/api.js
source/renderer/app/api/network/types.js
source/renderer/app/api/utils/patchAdaApi.js
source/renderer/app/api/wallets/types.js
source/renderer/app/assets/images/sand-clock-xs.inline.svg
source/renderer/app/components/staking/delegation-center/DelegationCenter.js
source/renderer/app/components/status/DaedalusDiagnostics.js
source/renderer/app/components/status/DaedalusDiagnostics.scss
source/renderer/app/containers/staking/DelegationCenterPage.js
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/stores/NetworkStatusStore.js
storybook/stories/nodes/status/Diagnostics.stories.js
storybook/stories/staking/DelegationCenter.stories.js
storybook/stories/staking/Staking.stories.js

This PR introduces update for network-info API endpoint integration. When `networkTip` / `nextEpoch` or data related to them are not presented, delegation center page will only show loading spinner and data about epoch / slot on Diagnostics screen will be replaced with sand clock (instead spinner)
---
---

[DDW-319] Update network-info Api endpoint integration

---

installer-clusters.cfg

remove itn_selfnode from list of installers to build

---

CHANGELOG.md
source/renderer/app/api/api.js
source/renderer/app/api/utils/patchAdaApi.js
source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.js
source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsSuccessDialog.js
source/renderer/app/config/epochsConfig.js

This PR fixes epoch length and slots count info used on the delegation screens.
---
---

[DDW-327] Fix epoch length and slot count info

---

CHANGELOG.md
source/renderer/app/i18n/locales/en-US.json
source/renderer/app/i18n/locales/ja-JP.json

This PR fixes the text copy on the "Delegation center" screen.
Correct text copy: https://docs.google.com/document/d/17VgszvVPWdXiN4BI3OvKizdLwHeyMjZq0S102Z8mrPo/edit
---
---

[DDW-333] Fix text copy on the "Delegation center" screen

---

CHANGELOG.md
source/renderer/app/components/loading/syncing-connecting/LogosDisplay.scss
source/renderer/app/components/widgets/splash/Splash.scss

This PR fixes Daedalus logo animation on the "Loading" screen.
The issue was present on RETINA screens only!
- Before
- After
---
---

[DDW-322] Fix Daedalus logo animation

---

CHANGELOG.md
source/renderer/app/components/wallet/WalletAdd.js
source/renderer/app/containers/wallet/WalletAddPage.js
storybook/stories/wallets/addWallet/Add.stories.js

This PR disables wallet creation prior to Shelley HF which in fact enables only Shelley wallet creation.
In other words, it is no longer possible to create a wallet during syncing progress of the Byron era.
---
---

[DDW-336] Disabled wallet creation before the Shelley HF

---

CHANGELOG.md
nix/sources.json
source/renderer/app/api/transactions/requests/createTransaction.js
source/renderer/app/api/transactions/requests/getTransactionFee.js

This PR updates request to the API with breaking changes introduced by PR #1967.
```md
* Rename the `?withdrawReward` query parameter in the transaction endpoint into `?withdrawal`
* The `?withdrawal` field can take two kind of values:
- The string `self`, which would behaves exactly as the `?withdrawReward` flag right now;
- A recovery phrase, which would then withdraw rewards from the wallet from this phrase.
* The same goes for the fee estimation endpoint.
```
---
---

[DDW-331] Update API request breaking changes

---

source/renderer/app/components/staking/redeem-itn-rewards/NoWalletsDialog.scss
source/renderer/app/components/staking/redeem-itn-rewards/Step2ConfirmationDialog.scss
source/renderer/app/components/staking/redeem-itn-rewards/Step3FailureDialog.scss
source/renderer/app/components/staking/redeem-itn-rewards/Step3SuccessDialog.scss
source/renderer/app/components/widgets/DialogFullSizeOverride.scss

This PR fixes ada redemption styling issues.
- Screenshot
---
---

[DDW-346] Fix Ada Redemption styling issues - Part 2

---

CHANGELOG.md
nix/sources.json
source/renderer/app/api/api.js
source/renderer/app/components/staking/redeem-itn-rewards/NoWalletsDialog.scss
source/renderer/app/components/staking/redeem-itn-rewards/Step2ConfirmationDialog.scss
source/renderer/app/components/staking/redeem-itn-rewards/Step3FailureDialog.scss
source/renderer/app/components/staking/redeem-itn-rewards/Step3SuccessDialog.scss
source/renderer/app/components/widgets/DialogFullSizeOverride.scss

This PR merges `release/2.1.0` into `develop` branch.

Merge release/2.1.0 into develop

---

CHANGELOG.md
nix/launcher-config.nix
nix/sources.json
package.json
source/main/config.js
yarn.lock

This PR updates cardano-launcher to the latest version which includes support for passing `smashUrl` param and adds `smashUrl` to the launcher config.
---
---

[DDW-338] Update cardano-launcher and set up SMASH

---

CHANGELOG.md
nix/sources.json
source/renderer/app/config/stakingConfig.js
source/renderer/app/containers/staking/StakePoolsListPage.js

This PR bumps the cardan-wallet revision to the tip of the latest master: `75b583a1 `.
**This PR also re-enables stake pool rankings!**
---
---

Cardano-wallet bump

---

nix/sources.json

Remove SMASH 1.0.1 usage

---

CHANGELOG.md
source/renderer/app/actions/staking-actions.js
source/renderer/app/components/staking/stake-pools/StakePools.js
source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
source/renderer/app/containers/staking/StakePoolsListPage.js
source/renderer/app/stores/StakingStore.js
storybook/stories/staking/StakePools.stories.js

This PR removes one second delay on changing wallet selection and selecting delegating stake slider value on the "Stake pools" screen.
---
---

[DDW-379] Remove one second delay on ranking stake pools

---

CHANGELOG.md
source/renderer/app/components/staking/widgets/ThumbPool.js
source/renderer/app/components/staking/widgets/ThumbPool.scss
source/renderer/app/components/staking/widgets/ThumbPoolContent.scss
source/renderer/app/components/staking/widgets/ThumbSelectedPool.js
source/renderer/app/components/staking/widgets/ThumbSelectedPool.scss
source/renderer/app/components/staking/widgets/TooltipPool.scss
source/renderer/app/themes/daedalus/dark-cardano.js
source/renderer/app/themes/daedalus/flight-candidate.js
source/renderer/app/themes/daedalus/incentivized-testnet.js
source/renderer/app/themes/daedalus/shelley-testnet.js
source/renderer/app/themes/daedalus/yellow.js

This PR fixes stake pool tooltip 'Delegate to this pool' button background colors.
---
---

[DDW-378] "Delegate to this pool" button styles

---

CHANGELOG.md
source/renderer/app/Routes.js

This PR sets the "Delegation center" as the default staking screen which you get to see when clicking on the "Staking" icon in the sidebar.
---
---

[DDW-394] Open ‘Delegation center’ as default staking screen

---

CHANGELOG.md
package.json

This PR merges `release/2.3.0-FC2` into `develop` branch.

Merge release/2.3.0-FC2 into develop

---

CHANGELOG.md
package.json

This PR merges `release/2.3.0` into `develop` branch.

Merge release/2.3.0 into develop

---

CHANGELOG.md
source/renderer/app/config/urlsConfig.js
tests/paper-wallets/e2e/steps/paper-wallets-certificate.js

This PR changes cardanoexplorer.com domain to explorer.cardano.org.
Also fixes testnet and staging URLs
---

[DDW-408] Fix cardanoexplorer.com domain to explorer.cardano.org

---

CHANGELOG.md
source/renderer/app/components/staking/widgets/TooltipPool.js
source/renderer/app/components/staking/widgets/TooltipPool.scss
source/renderer/app/themes/daedalus/shelley-testnet.js

This PR fixed stake pool tooltip height changing issue when hovering ID.
[Jira Ticket](https://jira.iohk.io/browse/DDW-402)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1602297024095800)

[DDW-402]: Fix stake pool tooltip height changing issue when hovering id

---

CHANGELOG.md
package.json

This PR merges `release/2.4.1` into `develop` branch.

Merge release/2.4.1 into develop

---

CHANGELOG.md
source/renderer/app/config/walletRestoreConfig.js

This PR hided hardware wallet restoration support in time for the Ledger and Trezor support launch.
[Jira Ticket](https://jira.iohk.io/browse/DDW-433)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1604623766359200)
- English
- Japanese

[DDW-433]: Hide hardware wallet restoration support

---

CHANGELOG.md
README.md
installers/common/Config.hs
installers/common/MacInstaller.hs
installers/common/Types.hs
installers/common/Util.hs
installers/common/WindowsInstaller.hs
nix/jormungandr-bridge.nix
nix/sources.json
source/main/cardano/CardanoWalletLauncher.js

This PR updates cardano-wallet to the latest release `2020-11-17`: https://github.com/input-output-hk/cardano-wallet/releases/tag/v2020-11-17.
---
---
Regression testing document for DDW-483 is [here](https://docs.google.com/spreadsheets/d/17VphWn2H1eco81chp5hZa1WdIQoFtk5K-HdQXQx2yGE/edit#gid=0)

[DDW-483] Bumps cardano-wallet version

---

CHANGELOG.md
package.json

This PR merges `release/2.5.0` into `develop` branch.

Merge release/2.5.0 into develop

---

CHANGELOG.md
source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss

This PR fixes the overlap of the X button in the stake pools search box:
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1606404167472100)
---

[DDW-455] Fix X Button Overlap in Stake Pools Search

---

CHANGELOG.md
nix/sources.json

This PR bumps `cardano-wallet` to v2020-12-08 and `cardano-node` to 1.24.2.
- Screenshot
---
---

[DDW-525] Ranking improvements, bumps cardano-wallet to v2020-12-08 and cardano-node to 1.24.2

---

source/main/index.js
source/main/ipc/getHardwareWalletChannel.js
source/main/webpack.config.js
source/renderer/app/components/hardware-wallet/HardwareWalletStatus.js
source/renderer/app/components/staking/stake-pools/StakePoolsRanking.scss
source/renderer/app/stores/HardwareWalletsStore.js

This PR fixes all of the remaining Ledger hardware wallet issues.
Testing report: https://docs.google.com/spreadsheets/d/1brvW8SkXcCSyUgKsJOX_EoBl-TZ4Gn7TEZewM3cMUEA/edit#gid=2082244573
---
[Link to Test Document](https://docs.google.com/spreadsheets/d/1brvW8SkXcCSyUgKsJOX_EoBl-TZ4Gn7TEZewM3cMUEA/edit#gid=2082244573)
---

[DDW-197] Fix remaining Ledger hardware wallet issues

---

CHANGELOG.md
package.json
source/main/ipc/getHardwareWalletChannel.js
source/renderer/app/utils/hardwareWalletUtils.js
source/renderer/app/utils/shelleyLedger.js
yarn.lock

This PR introduces an `@cardano-foundation/ledgerjs-hw-app-cardano` package version update to `2.1.0`.
---
---

[DDW-513] Update ledgerjs-hw-app-cardano package version to 2.1.0

---

CHANGELOG.md
nix/sources.json

This PR updates `iohk-nix` to the latest available version.
When Allegra support was added, `91c8928bd` from allegra-wallet branch wasn't used resulting in a large number of additional unnecessary logs. This bumps iohk-nix to fix the verbose logs.
---
---

[DEVOPS] Update iohk-nix

---

CHANGELOG.md
source/common/types/hardware-wallets.types.js
source/renderer/app/api/addresses/requests/inspectAddress.js
source/renderer/app/api/addresses/types.js
source/renderer/app/api/api.js
source/renderer/app/components/settings/SettingsLayout.js
source/renderer/app/config/hardwareWalletsConfig.js
source/renderer/app/domains/WalletAddress.js
source/renderer/app/stores/AddressesStore.js
source/renderer/app/stores/HardwareWalletsStore.js
source/renderer/app/utils/shelleyLedger.js

This PR introduces a fix for Ledger TXs to the Byron address.
[JIRA](https://jira.iohk.io/browse/DDW-534)
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1610453612143400)
---
**Scenario 1: Send ADA from Ledger Nano S to Byron wallet**
_(Regression template: row 32)_
```Gherkin
Given a Ledger Nano S wallet is added to Daedalus
And a Byron wallet is added to Daedalus
And both wallets are synced
And the Ledger Nano S wallet balance is >=2
When I access the "Send" screen for the Shelley wallet
And I paste an address from the Byron wallet on the "Receiver" input
And I insert a valid amount on the "Amount" input
And I click on "Next"
And I plug, unlock and export the public key on the device
And confirm the transaction on the dialog
Then the transaction is …
```

[DDW-534] Fix Ledger TXs to Byron addresses

---

CHANGELOG.md
nix/sources.json
source/renderer/app/api/api.js
source/renderer/app/api/network/types.js
source/renderer/app/api/transactions/requests/selectCoins.js
source/renderer/app/api/transactions/types.js
source/renderer/app/api/wallets/types.js
source/renderer/app/components/settings/SettingsLayout.js

This PR updates cardano-wallet version to the latest release `2021-01-12`: https://github.com/input-output-hk/cardano-wallet/releases/tag/v2021-01-12
In the scope of this PR, all updated Api endpoint types have been updated (check the "API Changes" section of the cardano-wallet release notes - link is in the line above ☝️).
**Still, the data (mainly fee and deposit) has not been propagated to the affected domains (e.g. Transaction).**
---
---
The regression document is on [this link](https://docs.google.com/spreadsheets/d/1jJZ857sF_hEzZcdu8DMkIhIxBJ40IevZVY_GgDYiApI/edit?usp=sharing).
---

[DDW-540] Update cardano-wallet version

---

CHANGELOG.md
package.json
source/renderer/app/i18n/locales/ja-JP.json

This PR merges `release/3.2.0-FC1` into `develop` branch.

Merge release/3.2.0-FC1 into develop

---

CHANGELOG.md
package.json

This PR merges `release/3.2.0` into `develop` branch.

Merge release/3.2.0 into develop

---

CHANGELOG.md
package.json

- Daedalus version change from `3.2.0-FC1` to `3.2.0`

Merge release/3.2.0 into master

---

CHANGELOG.md
source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js

This PR fixed error thrown when closing delegation wizard while transaction fees are being calculated.
[Jira Ticket](https://jira.iohk.io/browse/DDW-507)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1612262741127000)

[DDW-507] Closing delegation wizard while transaction fees are being calculated throws error in the console

---

CHANGELOG.md
source/renderer/app/components/wallet/wallet-restore/widgets/WalletRestoreDialog.js

This PR removes the "Step 1 of 3" subtitle from the "Success" step of the "Wallet restoration" wizard.
---
---

[DDW-545] Remove step counter from the wallet restoration "success" dialog step

---

CHANGELOG.md
source/main/config.js
source/main/ipc/get-logs.js

This PR fixes cardano-wallet logs packing count.
---
---

[DDW-562] Fix the count of packed cardano-wallet logs

---

CHANGELOG.md
source/renderer/app/components/voting/VotingInfo.js
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/i18n/locales/en-US.json
source/renderer/app/i18n/locales/ja-JP.json

This PR fixes the Catalyst Android app download link.
The following link is used for both English and Japanese language: https://play.google.com/store/apps/details?id=io.iohk.vitvoting
---
---

[VIT-895] Fix Catalyst Android app download link

---

CHANGELOG.md
package.json
source/renderer/app/stores/SidebarStore.js

This PR merges `release/3.3.0-FC1` into `develop` branch.

Merge release/3.3.0-FC1 into develop

---

CHANGELOG.md
nix/sources.json

Update to https://github.com/input-output-hk/cardano-wallet/releases/tag/v2021-02-12
---
Regression test document is located [here](https://docs.google.com/spreadsheets/d/1HSkGARf8g-x-GDAAO9eGROSw_RS-kptlxScx0LYkHvg/edit#gid=0)
---

[DDW-568] Update cardano-wallet to v2021-02-12

---

CHANGELOG.md
source/renderer/app/stores/HardwareWalletsStore.js

This PR introduces a fix for hardware wallets delegation.
---
---

Fix Hardware Wallets delegation

---

CHANGELOG.md
package.json
source/renderer/app/stores/HardwareWalletsStore.js
source/renderer/app/stores/SidebarStore.js

This PR merges `release/3.3.0` into `develop` branch.

Merge release/3.3.0 into develop

---

CHANGELOG.md
source/renderer/app/components/wallet/WalletSendForm.js

This PR updated wallet send form to fix bug when trying to send certain amounts
[Jira Ticket](https://jira.iohk.io/browse/DDW-578)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1613641156269000)

[DDW-578] Wallet send form does not work with certain amounts

---

CHANGELOG.md
source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
source/renderer/app/components/staking/widgets/TooltipPool.js
source/renderer/app/utils/formatters.js
storybook/stories/staking/DelegationSteps.stories.js

This PR fixes broken stake pool tooltip stories as preparation work to https://jira.iohk.io/browse/DDW-544
- When clicking on any pool thumb / ticker in the various lists BigNumber crashed due to unsafe calling of functions
- formatters expected BigNumber but had no check
- delegation wizard steps have been broken 
---
---

[DDW-544] Fix broken stake pool tooltip stories

---

CHANGELOG.md
source/renderer/app/components/wallet/transactions/FilterDialog.scss

This PR fixed filter dialog calendar styles on transaction list screen
[Jira Ticket](https://jira.iohk.io/browse/DDW-556)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1613733153306900)

[DDW-556] The calendar is displayed inside the "Filter" modal

---

CHANGELOG.md
package.json

This PR merges `release/3.3.1` into `develop` branch.

Merge release/3.3.1 into develop

---

CHANGELOG.md
nix/launcher-config.nix

launcher-config: remove socketFile

---

CHANGELOG.md
source/renderer/app/components/widgets/forms/InlineEditingInput.js

This PR fixed InlineEditingInput common component so that wallet name input works well
[Jira Ticket](https://jira.iohk.io/browse/DDW-560)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1614339262035800)

[DDW-560] Red outlining in "Wallet Name" input 

---

CHANGELOG.md
package.json
source/renderer/app/components/wallet/WalletSendForm.js
source/renderer/app/components/wallet/send-form/messages.js
source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
source/renderer/app/components/wallet/transactions/WalletTransactionsList.scss
source/renderer/app/i18n/locales/defaultMessages.json

This PR merges `release/4.0.0-FC1` into `develop` branch.

Merge release/4.0.0-FC1 into develop

---

CHANGELOG.md
source/renderer/app/api/api.js
source/renderer/app/components/wallet/summary/WalletSummaryNoTokens.scss
source/renderer/app/stores/TransactionsStore.js

This PR fixes transaction fee calculation errors.
---
---

[DDW-589] Fixes transaction fee calculation errors

---

CHANGELOG.md
nix/sources.json

This PR updates `iohk-nix` to the tip of the latest master branch which includes updated native token metadata registry server URLs.
---
---

Updates iohk-nix to the tip of the latest master branch

---

CHANGELOG.md
source/renderer/app/components/wallet/send-form/WalletSendAssetsConfirmationDialog.js
source/renderer/app/config/stakingConfig.js
source/renderer/app/config/walletsConfig.js
source/renderer/app/domains/Asset.js
source/renderer/app/i18n/locales/defaultMessages.json

This PR adds config variable for native token formatted amount display.
It is now possible to toggle native token amount formatting by updating the following variable:
```
IS_WALLET_ASSETS_AMOUNT_FORMATTING_ENABLED
```
This PR also disabled the "Tile rewards view" on "Flight" builds. It remains available only for "Staging" and "Testnet" builds.
---
---

[DDW-598] Adds config variable for native token formatted amount display

---

CHANGELOG.md
package.json
source/renderer/app/components/widgets/AssetToken.js
source/renderer/app/components/widgets/AssetToken.scss
source/renderer/app/config/walletsConfig.js

This PR merges `release/4.0.2-FC3` into `develop` branch.

Merge release/4.0.2-FC3 into develop

---

CHANGELOG.md
source/renderer/app/components/voting/VotingInfo.scss

This PR restored global link style on voting registration over screen
[Jira Ticket](https://jira.iohk.io/browse/DDW-593)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1615798338284600)

[DDW-593] Link style missing

---

CHANGELOG.md
source/renderer/app/components/appUpdate/AppUpdateOverlay.js
source/renderer/app/components/widgets/ProgressBarLarge.scss
source/renderer/app/containers/voting/dialogs/VotingRegistrationDialogContainer.js
storybook/stories/news/AppUpdateOverlay.stories.js

This PR fixes animation and positioning issues in the progress bar
- [JIRA](https://jira.iohk.io/browse/DDW-600) 
- [Storybook](http://localhost:6006/?path=/story/news-overlays--update#themeName=White&localeName=English&osName=Linux)
- To test the misalignment issue on Storybook, set the following parameters:
- Scenario: Download complete
- isLinux: true
- isWaitingToQuitDaedalus: true
- To reproduce the issue, add the class `AppUpdateOverlay_actions` to the parent div of `AppUpdateOverlay_progressBar`
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1615838673300500)
**Incorrect**
**Correct**
**Incorrect**
**Correct**
---
---
**Scenario 1 - Validate alignment of the progress bar in Linux**
```gherkin
Given that I am running Daedalus on Linux
And an update is …
```

[DDW-600] Progress bar animation and positioning issues

---

CHANGELOG.md
source/renderer/app/api/api.js
source/renderer/app/api/voting/types.js
source/renderer/app/stores/HardwareWalletsStore.js
source/renderer/app/stores/NetworkStatusStore.js
source/renderer/app/stores/VotingStore.js

This PR adds absolute slot number to the Catalyst voting registration transaction metadata under "61284" key as per: https://github.com/cardano-foundation/CIPs/pull/75/files#diff-85c19a6cf11b2c056d55b158cce2fbc702668844b10743ce82c2bc277ea75bafR59
Transaction details: https://explorer.cardano-testnet.iohkdev.io/en/transaction?id=fe27e046dabc8e6133b2440d671e833595ad9c5826e94f0afd18134dada65f10
---
---

[DDW-616] Add "slot_number" to Catalyst voting registration transaction metadata

---

CHANGELOG.md
source/renderer/app/stores/HardwareWalletsStore.js
source/renderer/app/utils/shelleyLedger.js

This PR introduces a public keys exporting improvement while signing transaction witnesses. The user is not prompted to export a public key for each witness returned from an already signed transaction.
**Dedicated QA:** @miorsufianiohk 
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1616749426140200)
```Gherkin
Scenario 1: Sending tx or delegating
Given I am (sending a tx|delegating) with Ledger
When I am signing the tx
Then on the device, ‘Confirm Transaction’ is the last step
And I am not asked to export multiple public keys anymore
```
_**NOTE:**_
_It is a regular signing and delegating process. Before you were prompted to export multiple public keys on the device after you confirmed the transaction. Now "Confirm Transaction" is the last step and you …

[DDW-567] Improve exporting public keys while signing witnesses

---

CHANGELOG.md
nix/sources.json
source/renderer/app/config/votingConfig.js

This PR updates Catalyst Fund4 registration and voting dates.
This PR also updates `cardano-wallet` to the tip of the latest master `7df30796` which includes important Catalyst registration related change: https://github.com/input-output-hk/cardano-wallet/pull/2589
---
---

[DDW-634] Update Catalyst Fund4 dates

---

CHANGELOG.md
source/renderer/app/components/wallet/transactions/metadata/TransactionMetadataView.js
storybook/stories/_support/utils.js

This PR fixes a minor bug in the tx metadata parsing: empty strings haven been shown as `null` as reported in #2492
---
---

[DDW-638] Handle empty strings in tx metadata

---

CHANGELOG.md
source/renderer/app/api/api.js
source/renderer/app/stores/HardwareWalletsStore.js
source/renderer/app/stores/WalletsStore.js

This PR introduces a fix for the spending password issue.
Also, few more logs added so we can reproduce HW issues a little bit easier.
It is related to the issue reported by the user:
https://github.com/input-output-hk/daedalus/issues/2493
---
---

[DDW-652] Hardware Wallets spending password issue with Trezor

---

CHANGELOG.md
source/renderer/app/stores/HardwareWalletsStore.js

This PR introduces a fix for HW crashes when a device is "busy".
[JIRA Ticket](https://jira.iohk.io/browse/DDW-577)
---
---

[DDW-577] Daedalus confirmation for HW crashes after unlocking the device for inactivity

---

CHANGELOG.md
package.json
source/common/types/hardware-wallets.types.js
source/main/ipc/getHardwareWalletChannel.js
source/renderer/app/stores/HardwareWalletsStore.js
source/renderer/app/utils/shelleyLedger.js
yarn.lock

This PR introduces the Ledger JS Library update and migration to version 3.0.0. and 
_**Check breaking changes related to multiassets and add improvement / migration (BIG NUM is not working as before)**_
- It is not covered with the latest LedgerJs update! https://input-output-rnd.slack.com/archives/G010N9UFDNH/p1616681875008200
_- No Screenshots_
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1619082189420700)
---

[DDW-655] Update and migrate Ledger JS library to version 3.0.0.

---

CHANGELOG.md
package.json
yarn.lock

This PR introduces trezor-connect library update to version 8.1.26
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1619083980421900)
---

[DDW-658] Update trezor-connect dependency to version 8.1.26

---

CHANGELOG.md
source/renderer/app/utils/shelleyLedger.js

This PR introduces a fix for HW transactions issue with the native tokens
---
---

[DDW-669] Fix hardware wallets transactions with native tokens grouping issue

---

CHANGELOG.md
package.json
source/renderer/app/stores/HardwareWalletsStore.js
source/renderer/app/utils/shelleyLedger.js

This PR merges `release/4.1.0-FC1` into develop branch.

Merge release/4.1.0-FC1 into develop

---

CHANGELOG.md
source/renderer/app/actions/currency-actions.js
source/renderer/app/actions/index.js
source/renderer/app/actions/wallets-actions.js
source/renderer/app/containers/settings/categories/WalletsSettingsPage.js
source/renderer/app/containers/wallet/WalletSummaryPage.js
source/renderer/app/stores/CurrencyStore.js
source/renderer/app/stores/WalletsStore.js
source/renderer/app/stores/index.js

This PR move the currency related code into dedicated store and actions.
---
---
(Scenarios from the [regression template](https://docs.google.com/spreadsheets/d/1l7khPZ9beM38C0jZTifZO24JK7hIr5E6sfsEwaRfIBs/edit?usp=sharing))
Scenario 1 - Validate "Wallets" tab from "Settings" screen
```gherkin
Given that I am on the "Wallets" tab on the "Settings" screen
When I validate its content
Then I can see a brief description of the feature 
And a switch to enable or disable it
And by default, it's enabled
And "US Dollar" is the default option in the dropdown
```
Scenario 2 - Disable displaying ada on other currencies
```gherkin
Given that a wallet is synced on Daedalus
And I am on the "Wallets" tab on the ""Settings"" …
```

[DDW-622] Move currency related code into a dedicated store

---

CHANGELOG.md
source/renderer/app/stores/VotingStore.js

This PR updates Catalyst voting registration to include rewards address instead of the payment one.
---
---

[DDW-661] Replace payment with stake address in Catalyst voting registration

---

CHANGELOG.md
default.nix

This PR defaults the cardano-cli version packed with Daedalus to the from cardano-wallet.
---
---

cardano-cli: default to version from cardano-wallet

---

CHANGELOG.md
source/renderer/app/api/wallets/requests/getAccountPublicKey.js

This PR fixes a bug within the "View wallet public key" feature which was caused by the cardano-wallet Api change which was not properly handled on Daedalus side.
---
---

[DDW-697] "An error occurred" is displayed when trying to reveal the public key

---

CHANGELOG.md
package.json
source/renderer/app/config/votingConfig.js
source/renderer/app/stores/SidebarStore.js

This PR merges `release/4.1.0` into develop branch.

Merge release/4.1.0 into develop

---

CHANGELOG.md
source/renderer/app/components/wallet/summary/WalletSummaryAssets.scss

This PR fixes asset search in Japanese.
https://user-images.githubusercontent.com/1504716/124141742-07f2cb80-da60-11eb-8509-ef7dcab8ba67.mp4
---
---

[DDW-711] Fix asset search in Japanese

---

CHANGELOG.md
package.json
source/renderer/app/components/wallet/summary/WalletSummaryAssets.scss

This PR merges `release/4.2.0-FC1` into develop branch.

Merge release/4.2.0-FC1 into develop

---

CHANGELOG.md
package.json
source/renderer/app/stores/SidebarStore.js

This PR merges `release/4.2.0` into develop branch.

Merge release/4.2.0 into develop

---

CHANGELOG.md
source/renderer/app/components/wallet/WalletSendForm.js

Fix enter key
---
```Gherkin
Scenario 1: Pressing Enter key displays 'Confirm Transaction' dialog
Given I am on Wallet Send tab
And the wallet has sufficient ADA for transaction
And the fields 'Receiver' and 'Ada' have been correctly filled
When the focus is on ('Receiver' | 'Ada' | 'Send button')
And I press the 'Enter' key
Then 'Confirm Transaction' dialog is displayed
And there is no error displayed on Console
```
---

[DDW-715] Enter key not working on send

---

CHANGELOG.md
source/renderer/app/components/staking/navigation/StakingNavigation.js
source/renderer/app/containers/TopBarContainer.js

This PR removes the "Decentralization countdown" tada icon and info tab.
---
---
**Scenario 1 - Check "Info" tab is not visible**
```gherkin
Given that Daedalus is synced
When I access to Staking Center
Then I can see that the "Info" tab is no longer visible
```
**Scenario 2 - Check "tada" icon is not visible**
```gherkin
Given that Daedalus is synced
When I check the top bar
Then I can see the "tada" icon is no longer displayed
```
---

[DDW-713] Remove "Decentralization countdown" tada icon and info tab

---

CHANGELOG.md
source/renderer/app/i18n/locales/en-US.json
source/renderer/app/i18n/locales/ja-JP.json

This PR fixes ‘Stakepool Metadata Aggregation Server (SMASH)’ link returning 404 error.
---
```Gherkin
Scenario1: Page opens up displaying correct info
Given I am on Settings->Stake pools
When I navigate via link on 'Stakepool Metadata Aggregation Server (SMASH)'
Then a browser opens up displaying the page 'SMASH metadata management' 
```
---

[DDW-733] Fix ‘Stakepool Metadata Aggregation Server (SMASH)’ link url

---

CHANGELOG.md
package.json

This PR merges `release/4.3.0` into develop branch.

Merge release/4.3.0 into develop

---

CHANGELOG.md
nix/sources.json

This PR bumps CWB to the tip of the master branch (revision `9ae2d48b9e5b75ebde36d035b3bac5b4c99b067e`) which includes a fix for hardware wallet issues in Alonzo era: https://github.com/input-output-hk/cardano-wallet/pull/2874
---
---

[DDW-739] Enable hardware wallet support in Alonzo era

---

CHANGELOG.md
source/renderer/app/components/wallet/tokens/WalletToken.js

This PR fixes the missing buttons in the Token's area.

[DDW-694] Fix: Buttons missing in Tokens footer

---

CHANGELOG.md
package.json
source/renderer/app/components/wallet/tokens/WalletToken.js

This PR merges `release/4.4.0` into develop branch.

Merge release/4.4.0 into develop

---

CHANGELOG.md
README.md

This PR introduces a README update with solution steps for the nix SSL issue.
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1635516238050300)
---

[DDW-778] Add solution for the nix SSL issue to the README

---

CHANGELOG.md
source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
source/renderer/app/i18n/locales/defaultMessages.json
source/renderer/app/stores/StakingStore.js

This PR fixes an issue with hardware wallets delegating to stake pools.
---

[DDW-759] Fixed hardware wallet delegation

---

source/renderer/app/actions/app-actions.js
source/renderer/app/api/utils/localStorage.js
source/renderer/app/features/discreet-mode/api/index.js
source/renderer/app/features/discreet-mode/context.js
source/renderer/app/features/discreet-mode/feature.js
source/renderer/app/features/discreet-mode/index.js
source/renderer/app/features/index.js
source/renderer/app/index.js
source/renderer/app/stores/AppStore.js

This PR extracts discreet mode logic from AppStore to its own mobx feature store. 
---
---

[DDW-813] - Use cardano explorer mobx-feature pattern

---

CHANGELOG.md
default.nix
installers/nix/electron.nix
installers/overlays/required.nix
nix/sources.json
shell.nix

This PR fixes issues introduced in the following [commit](https://github.com/input-output-hk/daedalus/pull/2735/commits/e01ff8c87bfa05d5ebd6ef54c091beda2968c242) which caused issues with Ledger hardware devices on Linux.
---
---

[DDW-815] Fix broken Ledger support on Linux

---

CHANGELOG.md
package.json
source/common/ipc/api.js
source/common/types/no-disk-space.types.js
source/main/config.js
source/main/index.js
source/main/utils/handleDiskSpace.js
source/renderer/app/stores/NetworkStatusStore.js
tests/app/e2e/steps/no-disk-space.js
yarn.lock

This PR adds latest hotfixes from release/4.5.2 and RTS Flags

Update develop with release 4.5.2 and rts flags

---

source/main/cardano/CardanoWalletLauncher.js

This PR removes the unstable RTS Flags

Removed unstable rts flags

---

CHANGELOG.md

Fixed duplicated text, wrong order

---

CHANGELOG.md
package.json

No unstable RTS flags are going to be released

Bump version to 4.6.0

---

CHANGELOG.md
source/main/environment.js

This PR reduces the RAM threshold for RTS mode recommendation to take into account cases where the actual RAM size might slightly vary (eg. 15.99 GB).
Addresses the issue found on Windows.
---

[DDW-920] Reduce the RAM threshold for RTS mode recommendation

---

.github/workflows/chromatic.yml

This PR triggers Chromatic job for develop branch 
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1644498036951289)
---

[DDW-968] Missing baseline screenshots for Chromatic

---

CHANGELOG.md
source/renderer/app/components/appUpdate/AppUpdateOverlay.scss
source/renderer/app/components/knownIssues/RTSFlagsRecommendationOverlay/RTSFlagsRecommendationOverlay.scss
source/renderer/app/components/news/AlertsOverlay.scss
source/renderer/app/components/news/IncidentOverlay.scss
source/renderer/app/components/news/NewsFeed.scss
source/renderer/app/themes/mixins/layers.scss

This PR increases z-index for dialogs
---

[DDW-983][BUG] - Fix the RAM Splash Screen | Main UI overlap

---

CHANGELOG.md
source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss

This PR fixes the gap for when the reward list button is not present. 
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1645802518561539)
---

[DDW-994] [BUG] Fix the "gap" between "Stake Pool View" options in Mainnet.

---

CHANGELOG.md
package.json
source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
yarn.lock

This PR merges the latest release back into develop

Merge the latest release back into develop

---

CHANGELOG.md
installers/common/MacInstaller.hs
package.json
yarn.lock

(cherry picked from commit 3688959)
This PR updates release 4.9.1 into develop branch

Update release 4.9.1 into develop branch

---

yarn.lock

_Internal PR to fix builds failing on `develop`._
/cc @danielmain

Fix yarn.lock after release

---

installers/common/MacInstaller.hs

_Internal_
Sign missing binaries for the release.
/cc @jbgi @danielmain @LaurenceIO

[release-4.10.0] Sign remaining macOS binaries

---

README.md

This PR updates the `nix.conf` setup in our README.md in order to enable experimental [nix flakes](https://nixos.wiki/wiki/Flakes) feature.

Update README.md with new nix.conf setup

---

default.nix
nix/cardano-wallet--node-1.35.1.patch
nix/sources.json
source/main/environment.ts

Internal PR (also patching `cardano-wallet`, just from here)

Update `cardano-node` to 1.35.1

---

CHANGELOG.md
default.nix
nix/sources.json

This PR updates `cardano-wallet` to v2022-10-06
*n/a*
*n/a*
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1665140832300109)
---

[DDW-1150] Integrate `cardano-wallet` v2022-10-06

---

CHANGELOG.md
nix/sources.json

This PR updates `cardano-node` configs for the respinning of the Preprod environment
*n/a*
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1666354725318589)
---

[DDW-1165] Update configs for Preprod respin

---

CHANGELOG.md
source/main/config.ts

This PR increases the `DISK_SPACE_REQUIRED` constant from 2gb to 4gb
[JIRA ticket](https://input-output.atlassian.net/browse/DDW-1167)

[DDW-1167] Increased minumum free disk space from 2gb to 4gb

---

CHANGELOG.md
storybook/stories/settings/general/General.stories.tsx
storybook/stories/settings/language/Language.stories.tsx
storybook/stories/settings/utils/helpers.tsx

The General stories of Storybook were either not handling the state of some props in storybook, or knobs weren't working. So now they should display the behaviour they are expected to have.
[Jira ticket](https://input-output.atlassian.net/browse/DDW-1152)
---

[DDW-1152] Fix general stories

---

CHANGELOG.md
package.json

This PR merges release 5.1.1 into `develop`.

Merge release 5.1.1 into `develop`

---

CHANGELOG.md
source/renderer/app/config/urlsConfig.ts

This PR updates the Catalyst API URL
- [Slack QA thread]()
---

[DDW-1175] Catalyst API URL updated

---

CHANGELOG.md
source/renderer/app/analytics/MatomoClient.ts
source/renderer/app/utils/formatters.ts

This PR addresses the issue of too many RAM size entries with very similar numbers.
Jira: https://input-output.atlassian.net/browse/DDW-1161

[DDW-1161] Round RAM size in analytics

---

CHANGELOG.md
source/renderer/app/analytics/MatomoAnalyticsTracker.ts
source/renderer/app/analytics/MatomoClient.ts
source/renderer/app/analytics/getCustomDimensions.ts
source/renderer/app/config/analyticsConfig.ts
source/renderer/app/index.tsx

This PR adds additional dimensions that will help us understand the percentage of users who still use legacy Byron wallets and usage of hardware wallets.
n/a
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1670590862190569)
- [Jira ticket](https://input-output.atlassian.net/browse/DDW-1174)
---

[DDW-1174] Add custom dimension to track legacy and hardware wallets

---

CHANGELOG.md
README.md
package.json

This PR merges the release 5.2.0 branch into develop branch

Merge release/5.2.0 into develop

---

CHANGELOG.md
flake.lock
flake.nix

[LW-10329](https://input-output.atlassian.net/browse/LW-10329)
This PR updates `cardano-node` to 8.9.2.
n/a
---

[LW-10329] Update cardano-node to 8.9.2

---

CHANGELOG.md
nix/internal/cardano-wallet--bump-cardano-node-1-35-5.patch
nix/internal/old-default.nix
package.json

This PR merged the code released in 5.3.1 into `main`.

Merge release 5.3.1 into main

---

source/main/ipc/compress-logs.ts

This PR introduces a fix for broken Daedalus logs download feature
[JIRA ticket](https://input-output.atlassian.net/browse/LW-10658)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1717158770331649)
---

[LW-10658] Fix logs download

---

source/renderer/app/stores/HardwareWalletsStore.ts
source/renderer/app/utils/dataSerialization.ts
source/renderer/app/utils/hardwareWalletUtils.ts
source/renderer/app/utils/shelleyLedger.ts
source/renderer/app/utils/shelleyTrezor.ts

This PR introduces a fix for broken Hardware Wallets tx serialization logic
[JIRA ticket](https://input-output.atlassian.net/browse/LW-10570)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1716890081700829)
---

[LW-10570] Fix hardware wallets tx logic

---

CHANGELOG.md
flake.lock
flake.nix
nix/internal/cardano-bridge.nix
nix/internal/common.nix

This PR updates `cardano-node` to 9.1.1.
_n/a_
_n/a_
_n/a_

[LW-11421] Update `cardano-node` to a 9.1.1 (hotfix for the ledger replay bug)

---

CHANGELOG.md
flake.lock
flake.nix
nix/internal/cardano-bridge.nix
nix/internal/common.nix
nix/internal/x86_64-linux.nix
package.json

_Internal PR._
You can see that it's the exact same commit that we released:
```
❯ git log --oneline --graph -n 2
*   d00870191 (HEAD -> merge-6-0-1-into-main, origin/merge-6-0-1-into-main) Merge tag '6.0.1' into merge-6-0-1-into-main
|\
| * 9d752528f (tag: 6.0.1, origin/release/6.0.1, release/6.0.1) Release version 6.0.1 (all networks)
```

Merge release 6.0.1 into main

---

CHANGELOG.md
package.json

Merge `main` with 6.0.1 into `develop`

---

CHANGELOG.md
source/renderer/app/stores/AppUpdateStore.ts

[LW-11428](https://input-output.atlassian.net/browse/LW-11428)
This PR unsets `APP-AUTOMATIC-UPDATE-FAILED` on every application startup to try again if we ever failed in the past; otherwise, auto-update would be broken forever on such a machine.
_n/a_
_n/a_
Tracked in Jira.
---
[LW-11428]: https://input-output.atlassian.net/browse/LW-11428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LW-11428] Un-brick auto-update on devices where it failed in the past

---

CHANGELOG.md
nix/internal/launcher-config.nix
source/main/config.ts

[LW-11497](https://input-output.atlassian.net/browse/LW-11497)
This PR fixes token metadata server URL on all networks, after switching to sourcing network configs from https://github.com/input-output-hk/cardano-playground.
_n/a_
_n/a_
Tracked in Jira.
---
[LW-11497]: https://input-output.atlassian.net/browse/LW-11497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LW-11497] Fix token metadata server URL on all networks

---

README.md

Small PR - Commit 96420415e50c550e7f3565a3912f86e53d3271bd renamed `mnemonics.js` to be `mnemonics.ts`. This PR adjusts sources to changes.
---

docs: update `mnemonics` reference

---

CHANGELOG.md

[LW-11505](https://input-output.atlassian.net/browse/LW-11505)
This PR corrects the `CHANGELOG.md` entry from:
* #3229
[LW-11505]: https://input-output.atlassian.net/browse/LW-11505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Found by @szymonmaslowski.

[LW-11505] Update the changelog with node 10.1.2

---

source/renderer/app/components/voting/voting-governance/VotingPowerDelegation.tsx

This PR fixes a form bug for the governance features
https://input-output.atlassian.net/browse/LW-11906

fix: drep chosen despite change to abstain [LW-11906]

---

source/renderer/app/components/voting/voting-governance/VotingPowerDelegation.scss
source/renderer/app/components/voting/voting-governance/VotingPowerDelegation.tsx

https://input-output.atlassian.net/browse/LW-11924

fix: [LW-11924] fix links styling

---

source/renderer/app/containers/wallet/dialogs/send-confirmation/SendConfirmation.view.tsx

- not blocking the send button when there is an error (https://input-output.atlassian.net/browse/LW-11949)
- blocking the send button when the submission is in progress (https://input-output.atlassian.net/browse/LW-11946)

fix: disabled state of confirm button of send confirmation dialog
